package auth

import (
	"context"
	"errors"
	"strings"

	"github.com/erp/backend/internal/db"
	"github.com/jackc/pgx/v5/pgtype"
	"golang.org/x/crypto/bcrypt"
)

var (
	ErrInvalidCredentials = errors.New("invalid email or password")
	ErrUserNotFound       = errors.New("user not found")
	ErrUserInactive       = errors.New("user inactive")
)

type AuthService struct {
	queries *db.Queries
}

func NewAuthService(queries *db.Queries) *AuthService {
	return &AuthService{queries: queries}
}

// Login now uses Email and returns the custom Row struct generated by the JOIN query
func (s *AuthService) Login(ctx context.Context, email, password string) (*db.GetUserWithRoleByEmailRow, error) {
	normalizedEmail := strings.TrimSpace(strings.ToLower(email))
	// 1. Fetch user by email with the role JOIN (Matches your new auth.sql)
	user, err := s.queries.GetUserWithRoleByEmail(ctx, normalizedEmail)
	if err != nil {
		return nil, ErrUserNotFound
	}

	if !user.IsActive {
		return nil, ErrUserInactive
	}

	// 2. Compare password
	err = bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(password))
	if err != nil {
		return nil, ErrInvalidCredentials
	}

	return &user, nil
}

func (s *AuthService) GetActiveUserProfileByEmail(ctx context.Context, email string) (*db.GetUserWithRoleByEmailRow, error) {
	normalizedEmail := strings.TrimSpace(strings.ToLower(email))
	user, err := s.queries.GetUserWithRoleByEmail(ctx, normalizedEmail)
	if err != nil {
		return nil, ErrUserNotFound
	}

	if !user.IsActive {
		return nil, ErrUserInactive
	}

	return &user, nil
}

func (s *AuthService) GetActiveUserProfileByID(ctx context.Context, userID pgtype.UUID) (*db.GetUserWithRoleByIDRow, error) {
	user, err := s.queries.GetUserWithRoleByID(ctx, userID)
	if err != nil {
		return nil, ErrUserNotFound
	}
	if !user.IsActive {
		return nil, ErrUserInactive
	}
	return &user, nil
}
