// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enterprise.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChartOfAccounts = `-- name: CountChartOfAccounts :one
SELECT COUNT(*) FROM chart_of_accounts WHERE tenant_id = $1
`

func (q *Queries) CountChartOfAccounts(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChartOfAccounts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompanyCodes = `-- name: CountCompanyCodes :one
SELECT COUNT(*) FROM company_codes WHERE tenant_id = $1
`

func (q *Queries) CountCompanyCodes(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanyCodes, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCostCenters = `-- name: CountCostCenters :one
SELECT COUNT(*) FROM cost_centers WHERE tenant_id = $1
`

func (q *Queries) CountCostCenters(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCostCenters, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGLAccounts = `-- name: CountGLAccounts :one
SELECT COUNT(*) FROM gl_accounts WHERE tenant_id = $1
`

func (q *Queries) CountGLAccounts(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGLAccounts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGLAccountsByChart = `-- name: CountGLAccountsByChart :one
SELECT COUNT(*) FROM gl_accounts WHERE tenant_id = $1 AND chart_of_accounts_id = $2
`

type CountGLAccountsByChartParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID `json:"chart_of_accounts_id"`
}

func (q *Queries) CountGLAccountsByChart(ctx context.Context, arg CountGLAccountsByChartParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGLAccountsByChart, arg.TenantID, arg.ChartOfAccountsID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlants = `-- name: CountPlants :one
SELECT COUNT(*) FROM plants WHERE tenant_id = $1
`

func (q *Queries) CountPlants(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlants, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChartOfAccounts = `-- name: CreateChartOfAccounts :one
INSERT INTO chart_of_accounts (tenant_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, code, name, created_at
`

type CreateChartOfAccountsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateChartOfAccounts(ctx context.Context, arg CreateChartOfAccountsParams) (ChartOfAccount, error) {
	row := q.db.QueryRow(ctx, createChartOfAccounts, arg.TenantID, arg.Code, arg.Name)
	var i ChartOfAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createCompanyCode = `-- name: CreateCompanyCode :one
INSERT INTO company_codes (tenant_id, code, name, country_code, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, code, name, country_code, currency, created_at, updated_at
`

type CreateCompanyCodeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Currency    string      `json:"currency"`
}

func (q *Queries) CreateCompanyCode(ctx context.Context, arg CreateCompanyCodeParams) (CompanyCode, error) {
	row := q.db.QueryRow(ctx, createCompanyCode,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.CountryCode,
		arg.Currency,
	)
	var i CompanyCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCostCenter = `-- name: CreateCostCenter :one
INSERT INTO cost_centers (tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
`

type CreateCostCenterParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	CompanyCodeID      pgtype.UUID `json:"company_code_id"`
	Code               string      `json:"code"`
	Name               string      `json:"name"`
	ParentCostCenterID pgtype.UUID `json:"parent_cost_center_id"`
	IsBlocked          bool        `json:"is_blocked"`
}

func (q *Queries) CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, createCostCenter,
		arg.TenantID,
		arg.CompanyCodeID,
		arg.Code,
		arg.Name,
		arg.ParentCostCenterID,
		arg.IsBlocked,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyCodeID,
		&i.Code,
		&i.Name,
		&i.ParentCostCenterID,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}

const createGLAccount = `-- name: CreateGLAccount :one
INSERT INTO gl_accounts (tenant_id, chart_of_accounts_id, account_number, account_type, group_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
`

type CreateGLAccountParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID `json:"chart_of_accounts_id"`
	AccountNumber     string      `json:"account_number"`
	AccountType       string      `json:"account_type"`
	GroupCode         pgtype.Text `json:"group_code"`
}

func (q *Queries) CreateGLAccount(ctx context.Context, arg CreateGLAccountParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, createGLAccount,
		arg.TenantID,
		arg.ChartOfAccountsID,
		arg.AccountNumber,
		arg.AccountType,
		arg.GroupCode,
	)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChartOfAccountsID,
		&i.AccountNumber,
		&i.AccountType,
		&i.GroupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlant = `-- name: CreatePlant :one
INSERT INTO plants (tenant_id, code, name, company_code_id, time_zone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, code, name, company_code_id, time_zone, created_at, updated_at
`

type CreatePlantParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	TimeZone      pgtype.Text `json:"time_zone"`
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) (Plant, error) {
	row := q.db.QueryRow(ctx, createPlant,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.CompanyCodeID,
		arg.TimeZone,
	)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CompanyCodeID,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChartOfAccounts = `-- name: DeleteChartOfAccounts :exec
DELETE FROM chart_of_accounts WHERE id = $1 AND tenant_id = $2
`

type DeleteChartOfAccountsParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteChartOfAccounts(ctx context.Context, arg DeleteChartOfAccountsParams) error {
	_, err := q.db.Exec(ctx, deleteChartOfAccounts, arg.ID, arg.TenantID)
	return err
}

const deleteCompanyCode = `-- name: DeleteCompanyCode :exec
DELETE FROM company_codes WHERE id = $1 AND tenant_id = $2
`

type DeleteCompanyCodeParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCompanyCode(ctx context.Context, arg DeleteCompanyCodeParams) error {
	_, err := q.db.Exec(ctx, deleteCompanyCode, arg.ID, arg.TenantID)
	return err
}

const deleteCostCenter = `-- name: DeleteCostCenter :exec
DELETE FROM cost_centers WHERE id = $1 AND tenant_id = $2
`

type DeleteCostCenterParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCostCenter(ctx context.Context, arg DeleteCostCenterParams) error {
	_, err := q.db.Exec(ctx, deleteCostCenter, arg.ID, arg.TenantID)
	return err
}

const deleteGLAccount = `-- name: DeleteGLAccount :exec
DELETE FROM gl_accounts WHERE id = $1 AND tenant_id = $2
`

type DeleteGLAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteGLAccount(ctx context.Context, arg DeleteGLAccountParams) error {
	_, err := q.db.Exec(ctx, deleteGLAccount, arg.ID, arg.TenantID)
	return err
}

const deletePlant = `-- name: DeletePlant :exec
DELETE FROM plants WHERE id = $1 AND tenant_id = $2
`

type DeletePlantParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePlant(ctx context.Context, arg DeletePlantParams) error {
	_, err := q.db.Exec(ctx, deletePlant, arg.ID, arg.TenantID)
	return err
}

const getChartOfAccounts = `-- name: GetChartOfAccounts :one
SELECT id, tenant_id, code, name, created_at
FROM chart_of_accounts
WHERE id = $1 AND tenant_id = $2
`

type GetChartOfAccountsParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetChartOfAccounts(ctx context.Context, arg GetChartOfAccountsParams) (ChartOfAccount, error) {
	row := q.db.QueryRow(ctx, getChartOfAccounts, arg.ID, arg.TenantID)
	var i ChartOfAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getChartOfAccountsByCode = `-- name: GetChartOfAccountsByCode :one
SELECT id, tenant_id, code, name, created_at
FROM chart_of_accounts
WHERE tenant_id = $1 AND code = $2
`

type GetChartOfAccountsByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetChartOfAccountsByCode(ctx context.Context, arg GetChartOfAccountsByCodeParams) (ChartOfAccount, error) {
	row := q.db.QueryRow(ctx, getChartOfAccountsByCode, arg.TenantID, arg.Code)
	var i ChartOfAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyCode = `-- name: GetCompanyCode :one
SELECT id, tenant_id, code, name, country_code, currency, created_at, updated_at
FROM company_codes
WHERE id = $1 AND tenant_id = $2
`

type GetCompanyCodeParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCompanyCode(ctx context.Context, arg GetCompanyCodeParams) (CompanyCode, error) {
	row := q.db.QueryRow(ctx, getCompanyCode, arg.ID, arg.TenantID)
	var i CompanyCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyCodeByCode = `-- name: GetCompanyCodeByCode :one
SELECT id, tenant_id, code, name, country_code, currency, created_at, updated_at
FROM company_codes
WHERE tenant_id = $1 AND code = $2
`

type GetCompanyCodeByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetCompanyCodeByCode(ctx context.Context, arg GetCompanyCodeByCodeParams) (CompanyCode, error) {
	row := q.db.QueryRow(ctx, getCompanyCodeByCode, arg.TenantID, arg.Code)
	var i CompanyCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCostCenter = `-- name: GetCostCenter :one
SELECT id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
FROM cost_centers
WHERE id = $1 AND tenant_id = $2
`

type GetCostCenterParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCostCenter(ctx context.Context, arg GetCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, getCostCenter, arg.ID, arg.TenantID)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyCodeID,
		&i.Code,
		&i.Name,
		&i.ParentCostCenterID,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}

const getCostCenterByCode = `-- name: GetCostCenterByCode :one
SELECT id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
FROM cost_centers
WHERE tenant_id = $1 AND company_code_id = $2 AND code = $3
`

type GetCostCenterByCodeParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	Code          string      `json:"code"`
}

func (q *Queries) GetCostCenterByCode(ctx context.Context, arg GetCostCenterByCodeParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, getCostCenterByCode, arg.TenantID, arg.CompanyCodeID, arg.Code)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyCodeID,
		&i.Code,
		&i.Name,
		&i.ParentCostCenterID,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}

const getGLAccount = `-- name: GetGLAccount :one
SELECT id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
FROM gl_accounts
WHERE id = $1 AND tenant_id = $2
`

type GetGLAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetGLAccount(ctx context.Context, arg GetGLAccountParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, getGLAccount, arg.ID, arg.TenantID)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChartOfAccountsID,
		&i.AccountNumber,
		&i.AccountType,
		&i.GroupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGLAccountByNumber = `-- name: GetGLAccountByNumber :one
SELECT id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
FROM gl_accounts
WHERE tenant_id = $1 AND chart_of_accounts_id = $2 AND account_number = $3
`

type GetGLAccountByNumberParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID `json:"chart_of_accounts_id"`
	AccountNumber     string      `json:"account_number"`
}

func (q *Queries) GetGLAccountByNumber(ctx context.Context, arg GetGLAccountByNumberParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, getGLAccountByNumber, arg.TenantID, arg.ChartOfAccountsID, arg.AccountNumber)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChartOfAccountsID,
		&i.AccountNumber,
		&i.AccountType,
		&i.GroupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlant = `-- name: GetPlant :one
SELECT id, tenant_id, code, name, company_code_id, time_zone, created_at, updated_at
FROM plants
WHERE id = $1 AND tenant_id = $2
`

type GetPlantParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPlant(ctx context.Context, arg GetPlantParams) (Plant, error) {
	row := q.db.QueryRow(ctx, getPlant, arg.ID, arg.TenantID)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CompanyCodeID,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlantByCode = `-- name: GetPlantByCode :one
SELECT id, tenant_id, code, name, company_code_id, time_zone, created_at, updated_at
FROM plants
WHERE tenant_id = $1 AND code = $2
`

type GetPlantByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetPlantByCode(ctx context.Context, arg GetPlantByCodeParams) (Plant, error) {
	row := q.db.QueryRow(ctx, getPlantByCode, arg.TenantID, arg.Code)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CompanyCodeID,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChartOfAccounts = `-- name: ListChartOfAccounts :many
SELECT id, tenant_id, code, name, created_at
FROM chart_of_accounts
WHERE tenant_id = $1
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type ListChartOfAccountsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Chart of accounts
func (q *Queries) ListChartOfAccounts(ctx context.Context, arg ListChartOfAccountsParams) ([]ChartOfAccount, error) {
	rows, err := q.db.Query(ctx, listChartOfAccounts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChartOfAccount
	for rows.Next() {
		var i ChartOfAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyCodes = `-- name: ListCompanyCodes :many
SELECT id, tenant_id, code, name, country_code, currency, created_at, updated_at
FROM company_codes
WHERE tenant_id = $1
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type ListCompanyCodesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Company codes
func (q *Queries) ListCompanyCodes(ctx context.Context, arg ListCompanyCodesParams) ([]CompanyCode, error) {
	rows, err := q.db.Query(ctx, listCompanyCodes, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyCode
	for rows.Next() {
		var i CompanyCode
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CountryCode,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCenters = `-- name: ListCostCenters :many
SELECT id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
FROM cost_centers
WHERE tenant_id = $1
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type ListCostCentersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Cost centers
func (q *Queries) ListCostCenters(ctx context.Context, arg ListCostCentersParams) ([]CostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCenters, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyCodeID,
			&i.Code,
			&i.Name,
			&i.ParentCostCenterID,
			&i.IsBlocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCentersByCompanyCode = `-- name: ListCostCentersByCompanyCode :many
SELECT id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
FROM cost_centers
WHERE tenant_id = $1 AND company_code_id = $2
ORDER BY code ASC
LIMIT $3 OFFSET $4
`

type ListCostCentersByCompanyCodeParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListCostCentersByCompanyCode(ctx context.Context, arg ListCostCentersByCompanyCodeParams) ([]CostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCentersByCompanyCode,
		arg.TenantID,
		arg.CompanyCodeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyCodeID,
			&i.Code,
			&i.Name,
			&i.ParentCostCenterID,
			&i.IsBlocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGLAccounts = `-- name: ListGLAccounts :many
SELECT id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
FROM gl_accounts
WHERE tenant_id = $1
ORDER BY chart_of_accounts_id, account_number ASC
LIMIT $2 OFFSET $3
`

type ListGLAccountsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// G/L accounts (require chart_of_accounts_id; company_code comes from chart/usage)
func (q *Queries) ListGLAccounts(ctx context.Context, arg ListGLAccountsParams) ([]GlAccount, error) {
	rows, err := q.db.Query(ctx, listGLAccounts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlAccount
	for rows.Next() {
		var i GlAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChartOfAccountsID,
			&i.AccountNumber,
			&i.AccountType,
			&i.GroupCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGLAccountsByChart = `-- name: ListGLAccountsByChart :many
SELECT id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
FROM gl_accounts
WHERE tenant_id = $1 AND chart_of_accounts_id = $2
ORDER BY account_number ASC
LIMIT $3 OFFSET $4
`

type ListGLAccountsByChartParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID `json:"chart_of_accounts_id"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

func (q *Queries) ListGLAccountsByChart(ctx context.Context, arg ListGLAccountsByChartParams) ([]GlAccount, error) {
	rows, err := q.db.Query(ctx, listGLAccountsByChart,
		arg.TenantID,
		arg.ChartOfAccountsID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlAccount
	for rows.Next() {
		var i GlAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChartOfAccountsID,
			&i.AccountNumber,
			&i.AccountType,
			&i.GroupCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlants = `-- name: ListPlants :many
SELECT id, tenant_id, code, name, company_code_id, time_zone, created_at, updated_at
FROM plants
WHERE tenant_id = $1
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type ListPlantsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Plants
func (q *Queries) ListPlants(ctx context.Context, arg ListPlantsParams) ([]Plant, error) {
	rows, err := q.db.Query(ctx, listPlants, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CompanyCodeID,
			&i.TimeZone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChartOfAccounts = `-- name: UpdateChartOfAccounts :one
UPDATE chart_of_accounts
SET name = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, created_at
`

type UpdateChartOfAccountsParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

func (q *Queries) UpdateChartOfAccounts(ctx context.Context, arg UpdateChartOfAccountsParams) (ChartOfAccount, error) {
	row := q.db.QueryRow(ctx, updateChartOfAccounts, arg.ID, arg.TenantID, arg.Name)
	var i ChartOfAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompanyCode = `-- name: UpdateCompanyCode :one
UPDATE company_codes
SET name = $3, country_code = $4, currency = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, country_code, currency, created_at, updated_at
`

type UpdateCompanyCodeParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Currency    string      `json:"currency"`
}

func (q *Queries) UpdateCompanyCode(ctx context.Context, arg UpdateCompanyCodeParams) (CompanyCode, error) {
	row := q.db.QueryRow(ctx, updateCompanyCode,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CountryCode,
		arg.Currency,
	)
	var i CompanyCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCostCenter = `-- name: UpdateCostCenter :one
UPDATE cost_centers
SET name = $3, parent_cost_center_id = $4, is_blocked = $5
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, company_code_id, code, name, parent_cost_center_id, is_blocked, created_at
`

type UpdateCostCenterParams struct {
	ID                 pgtype.UUID `json:"id"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	ParentCostCenterID pgtype.UUID `json:"parent_cost_center_id"`
	IsBlocked          bool        `json:"is_blocked"`
}

func (q *Queries) UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, updateCostCenter,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ParentCostCenterID,
		arg.IsBlocked,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyCodeID,
		&i.Code,
		&i.Name,
		&i.ParentCostCenterID,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateGLAccount = `-- name: UpdateGLAccount :one
UPDATE gl_accounts
SET account_type = $3, group_code = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, chart_of_accounts_id, account_number, account_type, group_code, created_at, updated_at
`

type UpdateGLAccountParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	AccountType string      `json:"account_type"`
	GroupCode   pgtype.Text `json:"group_code"`
}

func (q *Queries) UpdateGLAccount(ctx context.Context, arg UpdateGLAccountParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, updateGLAccount,
		arg.ID,
		arg.TenantID,
		arg.AccountType,
		arg.GroupCode,
	)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChartOfAccountsID,
		&i.AccountNumber,
		&i.AccountType,
		&i.GroupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlant = `-- name: UpdatePlant :one
UPDATE plants
SET name = $3, company_code_id = $4, time_zone = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, company_code_id, time_zone, created_at, updated_at
`

type UpdatePlantParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          string      `json:"name"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	TimeZone      pgtype.Text `json:"time_zone"`
}

func (q *Queries) UpdatePlant(ctx context.Context, arg UpdatePlantParams) (Plant, error) {
	row := q.db.QueryRow(ctx, updatePlant,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CompanyCodeID,
		arg.TimeZone,
	)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CompanyCodeID,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
