// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountingDocumentHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CompanyCodeID  pgtype.UUID        `json:"company_code_id"`
	DocumentNumber string             `json:"document_number"`
	FiscalYear     int32              `json:"fiscal_year"`
	PostingDate    pgtype.Date        `json:"posting_date"`
	DocumentDate   pgtype.Date        `json:"document_date"`
	DocumentType   string             `json:"document_type"`
	Currency       string             `json:"currency"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AccountingDocumentItem struct {
	ID               pgtype.UUID    `json:"id"`
	TenantID         pgtype.UUID    `json:"tenant_id"`
	DocumentHeaderID pgtype.UUID    `json:"document_header_id"`
	LineNumber       int32          `json:"line_number"`
	GlAccountID      pgtype.UUID    `json:"gl_account_id"`
	Amount           pgtype.Numeric `json:"amount"`
	DebitCredit      string         `json:"debit_credit"`
	Currency         string         `json:"currency"`
	CostCenterID     pgtype.UUID    `json:"cost_center_id"`
	ProfitCenterID   pgtype.UUID    `json:"profit_center_id"`
	ReferenceID      pgtype.UUID    `json:"reference_id"`
	ReferenceType    pgtype.Text    `json:"reference_type"`
	Text             pgtype.Text    `json:"text"`
}

type ActivityType struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CostCenterID  pgtype.UUID        `json:"cost_center_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	UnitOfMeasure string             `json:"unit_of_measure"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ActivityTypeText struct {
	ID             pgtype.UUID `json:"id"`
	ActivityTypeID pgtype.UUID `json:"activity_type_id"`
	LanguageCode   string      `json:"language_code"`
	Description    pgtype.Text `json:"description"`
}

type Address struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Street    pgtype.Text        `json:"street"`
	Street2   pgtype.Text        `json:"street2"`
	City      pgtype.Text        `json:"city"`
	State     pgtype.Text        `json:"state"`
	StateCode pgtype.Text        `json:"state_code"`
	Pincode   pgtype.Text        `json:"pincode"`
	Country   string             `json:"country"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AddressType struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AssessmentCycleHeader struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SourceCostElementID pgtype.UUID        `json:"source_cost_element_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AssessmentCycleReceiver struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CycleHeaderID      pgtype.UUID        `json:"cycle_header_id"`
	ReceiverType       string             `json:"receiver_type"`
	ReceiverID         pgtype.UUID        `json:"receiver_id"`
	ReceiverPercentage pgtype.Numeric     `json:"receiver_percentage"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AssessmentCycleSource struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CycleHeaderID    pgtype.UUID        `json:"cycle_header_id"`
	CostCenterID     pgtype.UUID        `json:"cost_center_id"`
	CostElementID    pgtype.UUID        `json:"cost_element_id"`
	SenderPercentage pgtype.Numeric     `json:"sender_percentage"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Operation  string             `json:"operation"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BankAccount struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	BankMasterID  pgtype.UUID        `json:"bank_master_id"`
	AccountID     string             `json:"account_id"`
	AccountHolder pgtype.Text        `json:"account_holder"`
	Currency      string             `json:"currency"`
	IsBlocked     bool               `json:"is_blocked"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BankDetail struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	BankMasterID  pgtype.UUID        `json:"bank_master_id"`
	AccountHolder string             `json:"account_holder"`
	AccountNumber pgtype.Text        `json:"account_number"`
	Iban          pgtype.Text        `json:"iban"`
	SwiftCode     pgtype.Text        `json:"swift_code"`
	BranchName    pgtype.Text        `json:"branch_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BankMaster struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	BankKey     string             `json:"bank_key"`
	Name        string             `json:"name"`
	SwiftCode   pgtype.Text        `json:"swift_code"`
	CountryCode string             `json:"country_code"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BankStatementHeader struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	BankAccountID   pgtype.UUID        `json:"bank_account_id"`
	StatementNumber string             `json:"statement_number"`
	StatementDate   pgtype.Date        `json:"statement_date"`
	OpeningBalance  pgtype.Numeric     `json:"opening_balance"`
	ClosingBalance  pgtype.Numeric     `json:"closing_balance"`
	Currency        string             `json:"currency"`
	ImportedAt      pgtype.Timestamptz `json:"imported_at"`
}

type BankStatementItem struct {
	ID                  pgtype.UUID    `json:"id"`
	TenantID            pgtype.UUID    `json:"tenant_id"`
	StatementHeaderID   pgtype.UUID    `json:"statement_header_id"`
	LineNumber          int32          `json:"line_number"`
	ValueDate           pgtype.Date    `json:"value_date"`
	Amount              pgtype.Numeric `json:"amount"`
	DebitCredit         string         `json:"debit_credit"`
	ReferenceText       pgtype.Text    `json:"reference_text"`
	CounterpartyName    pgtype.Text    `json:"counterparty_name"`
	CounterpartyAccount pgtype.Text    `json:"counterparty_account"`
}

type BillingBlock struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BillingDocumentHeader struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	BillingNumber string             `json:"billing_number"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	SalesOrderID  pgtype.UUID        `json:"sales_order_id"`
	BillingDate   pgtype.Date        `json:"billing_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BillingDocumentItem struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	BillingHeaderID   pgtype.UUID        `json:"billing_header_id"`
	LineNumber        int32              `json:"line_number"`
	ProductID         pgtype.UUID        `json:"product_id"`
	Description       pgtype.Text        `json:"description"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	Amount            pgtype.Numeric     `json:"amount"`
	InvoiceLineItemID pgtype.UUID        `json:"invoice_line_item_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Bom struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Name      string             `json:"name"`
	Version   string             `json:"version"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BomItem struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	BomID              pgtype.UUID        `json:"bom_id"`
	ComponentProductID pgtype.UUID        `json:"component_product_id"`
	Quantity           pgtype.Numeric     `json:"quantity"`
	Instructions       pgtype.Text        `json:"instructions"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CapacityPlanningHeader struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	PlanNumber string             `json:"plan_number"`
	PlanDate   pgtype.Date        `json:"plan_date"`
	PlantID    pgtype.UUID        `json:"plant_id"`
	Status     string             `json:"status"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CapacityPlanningItem struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	PlanHeaderID      pgtype.UUID        `json:"plan_header_id"`
	WorkCenterID      pgtype.UUID        `json:"work_center_id"`
	PlanningDate      pgtype.Date        `json:"planning_date"`
	PlannedLoad       pgtype.Numeric     `json:"planned_load"`
	AvailableCapacity pgtype.Numeric     `json:"available_capacity"`
	CapacityUnit      string             `json:"capacity_unit"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ChartOfAccount struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChartOfAccountsText struct {
	ID                pgtype.UUID `json:"id"`
	ChartOfAccountsID pgtype.UUID `json:"chart_of_accounts_id"`
	LanguageCode      string      `json:"language_code"`
	Description       pgtype.Text `json:"description"`
}

type CoilConsumptionLog struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	OperationDate pgtype.Date        `json:"operation_date"`
	StartingKg    pgtype.Numeric     `json:"starting_kg"`
	ScrapKg       pgtype.Numeric     `json:"scrap_kg"`
	ShortlengthKg pgtype.Numeric     `json:"shortlength_kg"`
	UsedKg        pgtype.Numeric     `json:"used_kg"`
	RemainingKg   pgtype.Numeric     `json:"remaining_kg"`
	CoilEnded     bool               `json:"coil_ended"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CompanyCode struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	CountryCode string             `json:"country_code"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CompanyCodePlant struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	PlantID       pgtype.UUID `json:"plant_id"`
}

type CompanyCodeText struct {
	ID            pgtype.UUID `json:"id"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	LanguageCode  string      `json:"language_code"`
	Description   pgtype.Text `json:"description"`
}

type CompanyProfile struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CompanyName  string             `json:"company_name"`
	AddressLine1 pgtype.Text        `json:"address_line1"`
	AddressLine2 pgtype.Text        `json:"address_line2"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Pincode      pgtype.Text        `json:"pincode"`
	Country      pgtype.Text        `json:"country"`
	GstNumber    pgtype.Text        `json:"gst_number"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StateCode    pgtype.Text        `json:"state_code"`
	Tan          pgtype.Text        `json:"tan"`
}

type ConditionRecord struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	ConditionTypeID       pgtype.UUID        `json:"condition_type_id"`
	ProductID             pgtype.UUID        `json:"product_id"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
	SalesOrganizationID   pgtype.UUID        `json:"sales_organization_id"`
	DistributionChannelID pgtype.UUID        `json:"distribution_channel_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Percent               pgtype.Numeric     `json:"percent"`
	Currency              string             `json:"currency"`
	ValidFrom             pgtype.Date        `json:"valid_from"`
	ValidTo               pgtype.Date        `json:"valid_to"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ContactPerson struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	FirstName string             `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Mobile    pgtype.Text        `json:"mobile"`
	JobTitle  pgtype.Text        `json:"job_title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContractHeader struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	ContractNumber           string             `json:"contract_number"`
	VendorID                 pgtype.UUID        `json:"vendor_id"`
	PurchasingOrganizationID pgtype.UUID        `json:"purchasing_organization_id"`
	Status                   string             `json:"status"`
	ValidFrom                pgtype.Date        `json:"valid_from"`
	ValidTo                  pgtype.Date        `json:"valid_to"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type ContractItem struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ContractHeaderID pgtype.UUID        `json:"contract_header_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	NetValue         pgtype.Numeric     `json:"net_value"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CostCenter struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CompanyCodeID      pgtype.UUID        `json:"company_code_id"`
	Code               string             `json:"code"`
	Name               string             `json:"name"`
	ParentCostCenterID pgtype.UUID        `json:"parent_cost_center_id"`
	IsBlocked          bool               `json:"is_blocked"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CostCenterActivityRate struct {
	ID             pgtype.UUID    `json:"id"`
	TenantID       pgtype.UUID    `json:"tenant_id"`
	ActivityTypeID pgtype.UUID    `json:"activity_type_id"`
	FiscalYear     int32          `json:"fiscal_year"`
	PeriodNumber   int32          `json:"period_number"`
	PricePerUnit   pgtype.Numeric `json:"price_per_unit"`
	Currency       string         `json:"currency"`
}

type CostCenterProfitCenter struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	CostCenterID   pgtype.UUID `json:"cost_center_id"`
	ProfitCenterID pgtype.UUID `json:"profit_center_id"`
	ValidFrom      pgtype.Date `json:"valid_from"`
	ValidTo        pgtype.Date `json:"valid_to"`
}

type CostCenterText struct {
	ID           pgtype.UUID `json:"id"`
	CostCenterID pgtype.UUID `json:"cost_center_id"`
	LanguageCode string      `json:"language_code"`
	Description  pgtype.Text `json:"description"`
}

type CostElement struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID        `json:"chart_of_accounts_id"`
	CostElementNumber string             `json:"cost_element_number"`
	CostElementType   string             `json:"cost_element_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CostElementText struct {
	ID            pgtype.UUID `json:"id"`
	CostElementID pgtype.UUID `json:"cost_element_id"`
	LanguageCode  string      `json:"language_code"`
	Name          string      `json:"name"`
}

type CurrencyRate struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	FromCurrency string             `json:"from_currency"`
	ToCurrency   string             `json:"to_currency"`
	RateDate     pgtype.Date        `json:"rate_date"`
	Rate         pgtype.Numeric     `json:"rate"`
	RateType     pgtype.Text        `json:"rate_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CustomField struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EntityType   string             `json:"entity_type"`
	FieldName    string             `json:"field_name"`
	FieldType    string             `json:"field_type"`
	SortOrder    int32              `json:"sort_order"`
	Required     bool               `json:"required"`
	DefaultValue pgtype.Text        `json:"default_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	BillingAddress     pgtype.Text        `json:"billing_address"`
	ShippingAddress    pgtype.Text        `json:"shipping_address"`
	TaxID              pgtype.Text        `json:"tax_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Gstin              pgtype.Text        `json:"gstin"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	Pan                pgtype.Text        `json:"pan"`
}

type CustomerMaterialInfo struct {
	ID                          pgtype.UUID        `json:"id"`
	TenantID                    pgtype.UUID        `json:"tenant_id"`
	CustomerID                  pgtype.UUID        `json:"customer_id"`
	ProductID                   pgtype.UUID        `json:"product_id"`
	CustomerMaterialNumber      pgtype.Text        `json:"customer_material_number"`
	CustomerMaterialDescription pgtype.Text        `json:"customer_material_description"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type DefectCode struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Description   string             `json:"description"`
	DefectGroupID pgtype.UUID        `json:"defect_group_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DefectCodeGroup struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DeliveryBlock struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DeliveryHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DeliveryNumber string             `json:"delivery_number"`
	SalesOrderID   pgtype.UUID        `json:"sales_order_id"`
	ShipmentID     pgtype.UUID        `json:"shipment_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	DeliveryDate   pgtype.Date        `json:"delivery_date"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DeliveryItem struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	DeliveryHeaderID pgtype.UUID        `json:"delivery_header_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	SalesOrderItemID pgtype.UUID        `json:"sales_order_item_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DistributionChannel struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Division struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DocumentAttachment struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	DocumentHeaderID pgtype.UUID        `json:"document_header_id"`
	FileName         string             `json:"file_name"`
	FilePath         string             `json:"file_path"`
	MimeType         pgtype.Text        `json:"mime_type"`
	FileSizeBytes    pgtype.Int8        `json:"file_size_bytes"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DocumentHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DocumentTypeID pgtype.UUID        `json:"document_type_id"`
	DocumentNumber pgtype.Text        `json:"document_number"`
	Description    pgtype.Text        `json:"description"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DocumentLineAccountAssignment struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DocumentItemID pgtype.UUID        `json:"document_item_id"`
	AssignmentType string             `json:"assignment_type"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DocumentLink struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	DocumentHeaderID pgtype.UUID        `json:"document_header_id"`
	EntityType       string             `json:"entity_type"`
	EntityID         pgtype.UUID        `json:"entity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DocumentNumberSeries struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	DocumentType string      `json:"document_type"`
	Year         int32       `json:"year"`
	LastNumber   int32       `json:"last_number"`
	Prefix       string      `json:"prefix"`
}

type DocumentType struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Equipment struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	EquipmentNumber      string             `json:"equipment_number"`
	Name                 string             `json:"name"`
	FunctionalLocationID pgtype.UUID        `json:"functional_location_id"`
	PlantID              pgtype.UUID        `json:"plant_id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	WarrantyExpiry       pgtype.Date        `json:"warranty_expiry"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ExportQueue struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ExportType   string             `json:"export_type"`
	Parameters   []byte             `json:"parameters"`
	Status       string             `json:"status"`
	FilePath     pgtype.Text        `json:"file_path"`
	RequestedBy  pgtype.UUID        `json:"requested_by"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

type ExportQueueItem struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ExportQueueID pgtype.UUID        `json:"export_queue_id"`
	RecordCount   pgtype.Int4        `json:"record_count"`
	Details       []byte             `json:"details"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type FiscalPeriod struct {
	ID                  pgtype.UUID `json:"id"`
	TenantID            pgtype.UUID `json:"tenant_id"`
	CompanyCodeID       pgtype.UUID `json:"company_code_id"`
	FiscalYearVariantID pgtype.UUID `json:"fiscal_year_variant_id"`
	FiscalYear          int32       `json:"fiscal_year"`
	PeriodNumber        int32       `json:"period_number"`
	StartDate           pgtype.Date `json:"start_date"`
	EndDate             pgtype.Date `json:"end_date"`
	IsPostingAllowed    bool        `json:"is_posting_allowed"`
}

type FiscalYearVariant struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	StartMonth int32              `json:"start_month"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type FunctionalLocation struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	PlantID   pgtype.UUID        `json:"plant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GlAccount struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ChartOfAccountsID pgtype.UUID        `json:"chart_of_accounts_id"`
	AccountNumber     string             `json:"account_number"`
	AccountType       string             `json:"account_type"`
	GroupCode         pgtype.Text        `json:"group_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type GlAccountCompanyCode struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	GlAccountID   pgtype.UUID `json:"gl_account_id"`
	CompanyCodeID pgtype.UUID `json:"company_code_id"`
	IsBlocked     bool        `json:"is_blocked"`
	TaxCategory   pgtype.Text `json:"tax_category"`
}

type GlAccountText struct {
	ID           pgtype.UUID `json:"id"`
	GlAccountID  pgtype.UUID `json:"gl_account_id"`
	LanguageCode string      `json:"language_code"`
	Name         string      `json:"name"`
}

type GoodsReceipt struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PoID          pgtype.UUID        `json:"po_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	ReceiptNumber string             `json:"receipt_number"`
	ReceiptDate   pgtype.Date        `json:"receipt_date"`
	ReceivedBy    pgtype.UUID        `json:"received_by"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InboundMessageLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	MessageType  string             `json:"message_type"`
	Payload      []byte             `json:"payload"`
	Source       pgtype.Text        `json:"source"`
	Status       string             `json:"status"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type InspectionLotCharacteristic struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	InspectionLotID    pgtype.UUID        `json:"inspection_lot_id"`
	CharacteristicCode string             `json:"characteristic_code"`
	CharacteristicName pgtype.Text        `json:"characteristic_name"`
	UnitOfMeasure      pgtype.Text        `json:"unit_of_measure"`
	TargetValue        pgtype.Numeric     `json:"target_value"`
	UpperLimit         pgtype.Numeric     `json:"upper_limit"`
	LowerLimit         pgtype.Numeric     `json:"lower_limit"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type InspectionLotHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	LotNumber      string             `json:"lot_number"`
	ProductID      pgtype.UUID        `json:"product_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	InspectionType string             `json:"inspection_type"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceID       pgtype.UUID        `json:"source_id"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InspectionLotResult struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CharacteristicID pgtype.UUID        `json:"characteristic_id"`
	MeasuredValue    pgtype.Numeric     `json:"measured_value"`
	Result           string             `json:"result"`
	RecordedBy       pgtype.UUID        `json:"recorded_by"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
}

type IntegrationError struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	MessageID  pgtype.UUID        `json:"message_id"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	ErrorText  string             `json:"error_text"`
	RetryCount int32              `json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type InterfaceMappingRule struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	RuleName       string             `json:"rule_name"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	TargetSystem   pgtype.Text        `json:"target_system"`
	SourceField    string             `json:"source_field"`
	TargetField    string             `json:"target_field"`
	Transformation pgtype.Text        `json:"transformation"`
	Config         []byte             `json:"config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InternalOrder struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CompanyCodeID  pgtype.UUID        `json:"company_code_id"`
	OrderNumber    string             `json:"order_number"`
	Name           string             `json:"name"`
	OrderType      string             `json:"order_type"`
	CostCenterID   pgtype.UUID        `json:"cost_center_id"`
	ProfitCenterID pgtype.UUID        `json:"profit_center_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InternalOrderSettlementRule struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	InternalOrderID pgtype.UUID        `json:"internal_order_id"`
	ReceiverType    string             `json:"receiver_type"`
	ReceiverID      pgtype.UUID        `json:"receiver_id"`
	Percentage      pgtype.Numeric     `json:"percentage"`
	ValidFrom       pgtype.Date        `json:"valid_from"`
	ValidTo         pgtype.Date        `json:"valid_to"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InternalOrderText struct {
	ID              pgtype.UUID `json:"id"`
	InternalOrderID pgtype.UUID `json:"internal_order_id"`
	LanguageCode    string      `json:"language_code"`
	Description     pgtype.Text `json:"description"`
}

type InventoryCycleCountSchedule struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ProductID           pgtype.UUID        `json:"product_id"`
	WarehouseID         pgtype.UUID        `json:"warehouse_id"`
	CycleCountIndicator string             `json:"cycle_count_indicator"`
	CountFrequencyDays  int32              `json:"count_frequency_days"`
	LastCountDate       pgtype.Date        `json:"last_count_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type InventoryReservation struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	ReferenceType string             `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	Status        string             `json:"status"`
	ReservedAt    pgtype.Timestamptz `json:"reserved_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InventoryRevaluationHeader struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	RevaluationNumber string             `json:"revaluation_number"`
	RevaluationDate   pgtype.Date        `json:"revaluation_date"`
	Status            string             `json:"status"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type InventoryRevaluationItem struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	RevaluationHeaderID pgtype.UUID        `json:"revaluation_header_id"`
	ProductID           pgtype.UUID        `json:"product_id"`
	WarehouseID         pgtype.UUID        `json:"warehouse_id"`
	OldPrice            pgtype.Numeric     `json:"old_price"`
	NewPrice            pgtype.Numeric     `json:"new_price"`
	Quantity            pgtype.Numeric     `json:"quantity"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type InventoryTransaction struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	WarehouseID       pgtype.UUID        `json:"warehouse_id"`
	BatchID           pgtype.UUID        `json:"batch_id"`
	TransactionType   string             `json:"transaction_type"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	ReferenceID       pgtype.UUID        `json:"reference_id"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TransactionReason pgtype.Text        `json:"transaction_reason"`
}

type Invoice struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	SoID               pgtype.UUID        `json:"so_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	InvoiceDate        pgtype.Date        `json:"invoice_date"`
	DueDate            pgtype.Date        `json:"due_date"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	InvoiceType        string             `json:"invoice_type"`
	Subtotal           pgtype.Numeric     `json:"subtotal"`
	CgstTotal          pgtype.Numeric     `json:"cgst_total"`
	SgstTotal          pgtype.Numeric     `json:"sgst_total"`
	IgstTotal          pgtype.Numeric     `json:"igst_total"`
}

type InvoiceLineItem struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	InvoiceID    pgtype.UUID        `json:"invoice_id"`
	Description  string             `json:"description"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	UnitPrice    pgtype.Numeric     `json:"unit_price"`
	TotalLine    pgtype.Numeric     `json:"total_line"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	HsnSac       pgtype.Text        `json:"hsn_sac"`
	TaxableValue pgtype.Numeric     `json:"taxable_value"`
	Cgst         pgtype.Numeric     `json:"cgst"`
	Sgst         pgtype.Numeric     `json:"sgst"`
	Igst         pgtype.Numeric     `json:"igst"`
}

type InvoiceNumberSequence struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Year       int32       `json:"year"`
	LastNumber int32       `json:"last_number"`
}

type Machine struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ProductionLineID pgtype.UUID        `json:"production_line_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceOrderConfirmation struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	OrderHeaderID     pgtype.UUID        `json:"order_header_id"`
	OperationID       pgtype.UUID        `json:"operation_id"`
	ActualWorkMinutes pgtype.Numeric     `json:"actual_work_minutes"`
	ConfirmationText  pgtype.Text        `json:"confirmation_text"`
	ConfirmedBy       pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceOrderHeader struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	OrderNumber          string             `json:"order_number"`
	EquipmentID          pgtype.UUID        `json:"equipment_id"`
	FunctionalLocationID pgtype.UUID        `json:"functional_location_id"`
	PlanHeaderID         pgtype.UUID        `json:"plan_header_id"`
	OrderType            string             `json:"order_type"`
	Status               string             `json:"status"`
	Priority             string             `json:"priority"`
	ScheduledStart       pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd         pgtype.Timestamptz `json:"scheduled_end"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceOrderOperation struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	OrderHeaderID          pgtype.UUID        `json:"order_header_id"`
	OperationNumber        int32              `json:"operation_number"`
	TaskListOperationID    pgtype.UUID        `json:"task_list_operation_id"`
	WorkCenterID           pgtype.UUID        `json:"work_center_id"`
	Description            pgtype.Text        `json:"description"`
	PlannedDurationMinutes pgtype.Numeric     `json:"planned_duration_minutes"`
	ActualDurationMinutes  pgtype.Numeric     `json:"actual_duration_minutes"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type MaintenancePlanHeader struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PlanNumber  string             `json:"plan_number"`
	Name        string             `json:"name"`
	Strategy    string             `json:"strategy"`
	CycleLength pgtype.Int4        `json:"cycle_length"`
	CycleUnit   pgtype.Text        `json:"cycle_unit"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MaintenancePlanItem struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PlanHeaderID  pgtype.UUID        `json:"plan_header_id"`
	ActivityType  string             `json:"activity_type"`
	Description   pgtype.Text        `json:"description"`
	IntervalValue int32              `json:"interval_value"`
	IntervalUnit  string             `json:"interval_unit"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceTaskListHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	TaskListNumber string             `json:"task_list_number"`
	Name           string             `json:"name"`
	PlantID        pgtype.UUID        `json:"plant_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceTaskListOperation struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	TaskListHeaderID pgtype.UUID        `json:"task_list_header_id"`
	OperationNumber  int32              `json:"operation_number"`
	WorkCenterID     pgtype.UUID        `json:"work_center_id"`
	Description      pgtype.Text        `json:"description"`
	DurationMinutes  pgtype.Numeric     `json:"duration_minutes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MaterialConsumption struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkOrderID pgtype.UUID        `json:"work_order_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	WarehouseID pgtype.UUID        `json:"warehouse_id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	RecordedBy  pgtype.UUID        `json:"recorded_by"`
}

type MaterialDocumentHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DocumentNumber string             `json:"document_number"`
	FiscalYear     int32              `json:"fiscal_year"`
	DocumentDate   pgtype.Date        `json:"document_date"`
	PostingDate    pgtype.Date        `json:"posting_date"`
	DocumentType   string             `json:"document_type"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MaterialDocumentItem struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	DocumentHeaderID pgtype.UUID        `json:"document_header_id"`
	LineNumber       int32              `json:"line_number"`
	ProductID        pgtype.UUID        `json:"product_id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	BatchID          pgtype.UUID        `json:"batch_id"`
	MovementType     string             `json:"movement_type"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitOfMeasure    string             `json:"unit_of_measure"`
	ReferenceID      pgtype.UUID        `json:"reference_id"`
	ReferenceType    pgtype.Text        `json:"reference_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MaterialGroup struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	ParentGroupID pgtype.UUID        `json:"parent_group_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MaterialType struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MeterReading struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EquipmentID  pgtype.UUID        `json:"equipment_id"`
	CounterType  string             `json:"counter_type"`
	ReadingValue pgtype.Numeric     `json:"reading_value"`
	ReadingDate  pgtype.Date        `json:"reading_date"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OperationConfirmation struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	WorkOrderID        pgtype.UUID        `json:"work_order_id"`
	RoutingOperationID pgtype.UUID        `json:"routing_operation_id"`
	ConfirmedQuantity  pgtype.Numeric     `json:"confirmed_quantity"`
	YieldQuantity      pgtype.Numeric     `json:"yield_quantity"`
	ScrapQuantity      pgtype.Numeric     `json:"scrap_quantity"`
	LaborTimeMinutes   pgtype.Numeric     `json:"labor_time_minutes"`
	MachineTimeMinutes pgtype.Numeric     `json:"machine_time_minutes"`
	ConfirmedBy        pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt        pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OutboundMessageLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	MessageType  string             `json:"message_type"`
	Payload      []byte             `json:"payload"`
	Destination  pgtype.Text        `json:"destination"`
	Status       string             `json:"status"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PartyAddress struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	AddressID     pgtype.UUID        `json:"address_id"`
	AddressTypeID pgtype.UUID        `json:"address_type_id"`
	VendorID      pgtype.UUID        `json:"vendor_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	IsDefault     bool               `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PartyBankDetail struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	BankDetailID pgtype.UUID        `json:"bank_detail_id"`
	VendorID     pgtype.UUID        `json:"vendor_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PartyContact struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ContactPersonID pgtype.UUID        `json:"contact_person_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	IsPrimary       bool               `json:"is_primary"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	RecordedBy      pgtype.UUID        `json:"recorded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PaymentTerm struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Code            string             `json:"code"`
	Description     pgtype.Text        `json:"description"`
	DaysUntilDue    int32              `json:"days_until_due"`
	DiscountPercent pgtype.Numeric     `json:"discount_percent"`
	DiscountDays    pgtype.Int4        `json:"discount_days"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PaymentTermsText struct {
	ID             pgtype.UUID `json:"id"`
	PaymentTermsID pgtype.UUID `json:"payment_terms_id"`
	LanguageCode   string      `json:"language_code"`
	Name           pgtype.Text `json:"name"`
}

type PhysicalInventoryHeader struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DocumentNumber string             `json:"document_number"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	CountDate      pgtype.Date        `json:"count_date"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PhysicalInventoryItem struct {
	ID                        pgtype.UUID        `json:"id"`
	TenantID                  pgtype.UUID        `json:"tenant_id"`
	PhysicalInventoryHeaderID pgtype.UUID        `json:"physical_inventory_header_id"`
	ProductID                 pgtype.UUID        `json:"product_id"`
	BatchID                   pgtype.UUID        `json:"batch_id"`
	BookQuantity              pgtype.Numeric     `json:"book_quantity"`
	CountedQuantity           pgtype.Numeric     `json:"counted_quantity"`
	Difference                pgtype.Numeric     `json:"difference"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type Plant struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	TimeZone      pgtype.Text        `json:"time_zone"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PlantPurchasingOrg struct {
	ID                       pgtype.UUID `json:"id"`
	TenantID                 pgtype.UUID `json:"tenant_id"`
	PlantID                  pgtype.UUID `json:"plant_id"`
	PurchasingOrganizationID pgtype.UUID `json:"purchasing_organization_id"`
}

type PlantSalesOrg struct {
	ID                  pgtype.UUID `json:"id"`
	TenantID            pgtype.UUID `json:"tenant_id"`
	PlantID             pgtype.UUID `json:"plant_id"`
	SalesOrganizationID pgtype.UUID `json:"sales_organization_id"`
}

type PlantText struct {
	ID           pgtype.UUID `json:"id"`
	PlantID      pgtype.UUID `json:"plant_id"`
	LanguageCode string      `json:"language_code"`
	Description  pgtype.Text `json:"description"`
}

type PostingPeriodLock struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	FiscalYear    int32              `json:"fiscal_year"`
	PeriodNumber  int32              `json:"period_number"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type PricingConditionType struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	CalculationType string             `json:"calculation_type"`
	PlusMinus       string             `json:"plus_minus"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Name         string             `json:"name"`
	Sku          string             `json:"sku"`
	Price        pgtype.Numeric     `json:"price"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReorderPoint pgtype.Numeric     `json:"reorder_point"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int32              `json:"lead_time_days"`
	Uom          string             `json:"uom"`
	ProductType  pgtype.Text        `json:"product_type"`
	StockStatus  pgtype.Text        `json:"stock_status"`
	TrNotes      pgtype.Text        `json:"tr_notes"`
	Brand        pgtype.Text        `json:"brand"`
	HsnSac       pgtype.Text        `json:"hsn_sac"`
	GstRate      pgtype.Numeric     `json:"gst_rate"`
}

type ProductBatch struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	BatchNumber     string             `json:"batch_number"`
	ManufactureDate pgtype.Date        `json:"manufacture_date"`
	ExpiryDate      pgtype.Date        `json:"expiry_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProductCategory struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProductDescription struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ProductID    pgtype.UUID `json:"product_id"`
	LanguageCode string      `json:"language_code"`
	ShortText    pgtype.Text `json:"short_text"`
	LongText     pgtype.Text `json:"long_text"`
}

type ProductPlantDatum struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	ProductID                pgtype.UUID        `json:"product_id"`
	PlantID                  pgtype.UUID        `json:"plant_id"`
	MrpType                  pgtype.Text        `json:"mrp_type"`
	LotSize                  pgtype.Text        `json:"lot_size"`
	PlanningDeliveryTimeDays pgtype.Int4        `json:"planning_delivery_time_days"`
	GrProcessingTimeDays     pgtype.Int4        `json:"gr_processing_time_days"`
	SafetyStock              pgtype.Numeric     `json:"safety_stock"`
	ReorderPoint             pgtype.Numeric     `json:"reorder_point"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type ProductPurchasingDatum struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	ProductID                pgtype.UUID        `json:"product_id"`
	PurchasingOrganizationID pgtype.UUID        `json:"purchasing_organization_id"`
	PlanningDeliveryTimeDays pgtype.Int4        `json:"planning_delivery_time_days"`
	GrProcessingTimeDays     pgtype.Int4        `json:"gr_processing_time_days"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type ProductSalesDatum struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	ProductID             pgtype.UUID        `json:"product_id"`
	SalesOrganizationID   pgtype.UUID        `json:"sales_organization_id"`
	DistributionChannelID pgtype.UUID        `json:"distribution_channel_id"`
	MinOrderQuantity      pgtype.Numeric     `json:"min_order_quantity"`
	DeliveryGroup         pgtype.Text        `json:"delivery_group"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ProductStorageLocationDatum struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	PlantID           pgtype.UUID        `json:"plant_id"`
	StorageLocationID pgtype.UUID        `json:"storage_location_id"`
	ReorderPoint      pgtype.Numeric     `json:"reorder_point"`
	MaxStock          pgtype.Numeric     `json:"max_stock"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProductSupplySource struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	PlantID         pgtype.UUID        `json:"plant_id"`
	SupplyType      string             `json:"supply_type"`
	DefaultVendorID pgtype.UUID        `json:"default_vendor_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProductUomConversion struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	AlternateUom string             `json:"alternate_uom"`
	Numerator    pgtype.Numeric     `json:"numerator"`
	Denominator  pgtype.Numeric     `json:"denominator"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ProductValuation struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	ValuationAreaID    pgtype.UUID        `json:"valuation_area_id"`
	ValuationType      string             `json:"valuation_type"`
	StandardPrice      pgtype.Numeric     `json:"standard_price"`
	MovingAveragePrice pgtype.Numeric     `json:"moving_average_price"`
	Currency           string             `json:"currency"`
	PriceControl       string             `json:"price_control"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProductionLine struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProductionLog struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkOrderID pgtype.UUID        `json:"work_order_id"`
	WarehouseID pgtype.UUID        `json:"warehouse_id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	ProducedAt  pgtype.Timestamptz `json:"produced_at"`
	RecordedBy  pgtype.UUID        `json:"recorded_by"`
	Notes       pgtype.Text        `json:"notes"`
}

type ProductionOrder struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	PoNumber         string             `json:"po_number"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	ProductionLineID pgtype.UUID        `json:"production_line_id"`
	Status           string             `json:"status"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProductionVersion struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	PlantID   pgtype.UUID        `json:"plant_id"`
	BomID     pgtype.UUID        `json:"bom_id"`
	RoutingID pgtype.UUID        `json:"routing_id"`
	Version   string             `json:"version"`
	ValidFrom pgtype.Date        `json:"valid_from"`
	ValidTo   pgtype.Date        `json:"valid_to"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProfitCenter struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	ParentProfitCenterID pgtype.UUID        `json:"parent_profit_center_id"`
	CompanyCodeID        pgtype.UUID        `json:"company_code_id"`
	IsBlocked            bool               `json:"is_blocked"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ProfitCenterText struct {
	ID             pgtype.UUID `json:"id"`
	ProfitCenterID pgtype.UUID `json:"profit_center_id"`
	LanguageCode   string      `json:"language_code"`
	Description    pgtype.Text `json:"description"`
}

type ProfitabilitySegment struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Segment1       pgtype.Text        `json:"segment_1"`
	Segment2       pgtype.Text        `json:"segment_2"`
	Segment3       pgtype.Text        `json:"segment_3"`
	ProfitCenterID pgtype.UUID        `json:"profit_center_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProfitabilitySegmentText struct {
	ID                     pgtype.UUID `json:"id"`
	ProfitabilitySegmentID pgtype.UUID `json:"profitability_segment_id"`
	LanguageCode           string      `json:"language_code"`
	Description            pgtype.Text `json:"description"`
}

type PurchaseOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	VendorID             pgtype.UUID        `json:"vendor_id"`
	PoNumber             string             `json:"po_number"`
	Status               string             `json:"status"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrderHistory struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	PurchaseOrderID       pgtype.UUID        `json:"purchase_order_id"`
	PurchaseOrderItemID   pgtype.UUID        `json:"purchase_order_item_id"`
	HistoryType           string             `json:"history_type"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	Amount                pgtype.Numeric     `json:"amount"`
	ReferenceDocumentID   pgtype.UUID        `json:"reference_document_id"`
	ReferenceDocumentType pgtype.Text        `json:"reference_document_type"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PurchaseOrderItem struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	PoID       pgtype.UUID        `json:"po_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	UnitPrice  pgtype.Numeric     `json:"unit_price"`
	TotalPrice pgtype.Numeric     `json:"total_price"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PurchaseRequisition struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	ReqNumber            string             `json:"req_number"`
	Department           pgtype.Text        `json:"department"`
	RequesterID          pgtype.UUID        `json:"requester_id"`
	Status               string             `json:"status"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	Budget               pgtype.Numeric     `json:"budget"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseRequisitionItem struct {
	ID            pgtype.UUID        `json:"id"`
	RequisitionID pgtype.UUID        `json:"requisition_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PurchasingGroup struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	Code                     string             `json:"code"`
	Name                     string             `json:"name"`
	PurchasingOrganizationID pgtype.UUID        `json:"purchasing_organization_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type PurchasingInfoRecord struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	VendorID                 pgtype.UUID        `json:"vendor_id"`
	ProductID                pgtype.UUID        `json:"product_id"`
	PurchasingOrganizationID pgtype.UUID        `json:"purchasing_organization_id"`
	PlantID                  pgtype.UUID        `json:"plant_id"`
	NetPrice                 pgtype.Numeric     `json:"net_price"`
	Currency                 string             `json:"currency"`
	DeliveryDays             pgtype.Int4        `json:"delivery_days"`
	MinOrderQuantity         pgtype.Numeric     `json:"min_order_quantity"`
	ValidFrom                pgtype.Date        `json:"valid_from"`
	ValidTo                  pgtype.Date        `json:"valid_to"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type PurchasingInfoRecordCondition struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	InfoRecordID  pgtype.UUID        `json:"info_record_id"`
	ConditionType string             `json:"condition_type"`
	Amount        pgtype.Numeric     `json:"amount"`
	Percent       pgtype.Numeric     `json:"percent"`
	Currency      string             `json:"currency"`
	ValidFrom     pgtype.Date        `json:"valid_from"`
	ValidTo       pgtype.Date        `json:"valid_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PurchasingOrgText struct {
	ID                       pgtype.UUID `json:"id"`
	PurchasingOrganizationID pgtype.UUID `json:"purchasing_organization_id"`
	LanguageCode             string      `json:"language_code"`
	Description              pgtype.Text `json:"description"`
}

type PurchasingOrganization struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QualityCertificate struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	CertificateNumber string             `json:"certificate_number"`
	ProductID         pgtype.UUID        `json:"product_id"`
	BatchID           pgtype.UUID        `json:"batch_id"`
	VendorID          pgtype.UUID        `json:"vendor_id"`
	CertificateType   pgtype.Text        `json:"certificate_type"`
	ValidFrom         pgtype.Date        `json:"valid_from"`
	ValidTo           pgtype.Date        `json:"valid_to"`
	DocumentID        pgtype.UUID        `json:"document_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QualityInfoRecord struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	VendorID       pgtype.UUID        `json:"vendor_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	PlantID        pgtype.UUID        `json:"plant_id"`
	InspectionType string             `json:"inspection_type"`
	ValidFrom      pgtype.Date        `json:"valid_from"`
	ValidTo        pgtype.Date        `json:"valid_to"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type QualityInspection struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkOrderID pgtype.UUID        `json:"work_order_id"`
	Result      string             `json:"result"`
	InspectorID pgtype.UUID        `json:"inspector_id"`
	Notes       pgtype.Text        `json:"notes"`
	InspectedAt pgtype.Timestamptz `json:"inspected_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type QualityNotificationHeader struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	NotificationNumber string             `json:"notification_number"`
	NotificationType   string             `json:"notification_type"`
	ProductID          pgtype.UUID        `json:"product_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	VendorID           pgtype.UUID        `json:"vendor_id"`
	Status             string             `json:"status"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type QualityNotificationItem struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	NotificationHeaderID pgtype.UUID        `json:"notification_header_id"`
	DefectCodeID         pgtype.UUID        `json:"defect_code_id"`
	Quantity             pgtype.Numeric     `json:"quantity"`
	Description          pgtype.Text        `json:"description"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type QuotaArrangement struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	PlantID   pgtype.UUID        `json:"plant_id"`
	ValidFrom pgtype.Date        `json:"valid_from"`
	ValidTo   pgtype.Date        `json:"valid_to"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QuotaArrangementItem struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	QuotaArrangementID pgtype.UUID        `json:"quota_arrangement_id"`
	VendorID           pgtype.UUID        `json:"vendor_id"`
	Percentage         pgtype.Numeric     `json:"percentage"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReportAccessLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ReportType   string             `json:"report_type"`
	Parameters   []byte             `json:"parameters"`
	ExportFormat pgtype.Text        `json:"export_format"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ReportVariant struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ReportType  string             `json:"report_type"`
	VariantName string             `json:"variant_name"`
	Parameters  []byte             `json:"parameters"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReservationItem struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ReservationID     pgtype.UUID        `json:"reservation_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	RequirementDate   pgtype.Date        `json:"requirement_date"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	QuantityWithdrawn pgtype.Numeric     `json:"quantity_withdrawn"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Routing struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	PlantID       pgtype.UUID        `json:"plant_id"`
	RoutingNumber string             `json:"routing_number"`
	Version       string             `json:"version"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RoutingOperation struct {
	ID                      pgtype.UUID        `json:"id"`
	TenantID                pgtype.UUID        `json:"tenant_id"`
	RoutingID               pgtype.UUID        `json:"routing_id"`
	OperationNumber         int32              `json:"operation_number"`
	WorkCenterID            pgtype.UUID        `json:"work_center_id"`
	Description             pgtype.Text        `json:"description"`
	StandardDurationMinutes pgtype.Numeric     `json:"standard_duration_minutes"`
	SetupTimeMinutes        pgtype.Numeric     `json:"setup_time_minutes"`
	MachineTimeMinutes      pgtype.Numeric     `json:"machine_time_minutes"`
	LaborTimeMinutes        pgtype.Numeric     `json:"labor_time_minutes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type RoutingOperationMaterial struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	RoutingOperationID    pgtype.UUID        `json:"routing_operation_id"`
	ProductID             pgtype.UUID        `json:"product_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	ComponentScrapPercent pgtype.Numeric     `json:"component_scrap_percent"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SalesArea struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SalesOrganizationID   pgtype.UUID        `json:"sales_organization_id"`
	DistributionChannelID pgtype.UUID        `json:"distribution_channel_id"`
	DivisionID            pgtype.UUID        `json:"division_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SalesOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	CustomerID           pgtype.UUID        `json:"customer_id"`
	SoNumber             string             `json:"so_number"`
	Status               string             `json:"status"`
	ExpectedShippingDate pgtype.Date        `json:"expected_shipping_date"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderItem struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	SoID       pgtype.UUID        `json:"so_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	UnitPrice  pgtype.Numeric     `json:"unit_price"`
	TotalPrice pgtype.Numeric     `json:"total_price"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SalesOrderPartner struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	SalesOrderID    pgtype.UUID        `json:"sales_order_id"`
	PartnerFunction string             `json:"partner_function"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SalesOrderScheduleLine struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	SalesOrderID          pgtype.UUID        `json:"sales_order_id"`
	SalesOrderItemID      pgtype.UUID        `json:"sales_order_item_id"`
	ScheduleLineNumber    int32              `json:"schedule_line_number"`
	RequestedDeliveryDate pgtype.Date        `json:"requested_delivery_date"`
	ConfirmedQuantity     pgtype.Numeric     `json:"confirmed_quantity"`
	ConfirmedDate         pgtype.Date        `json:"confirmed_date"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SalesOrgText struct {
	ID                  pgtype.UUID `json:"id"`
	SalesOrganizationID pgtype.UUID `json:"sales_organization_id"`
	LanguageCode        string      `json:"language_code"`
	Description         pgtype.Text `json:"description"`
}

type SalesOrganization struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScheduledReport struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	Name           string             `json:"name"`
	ReportType     string             `json:"report_type"`
	Frequency      string             `json:"frequency"`
	ExportFormat   string             `json:"export_format"`
	RecipientEmail string             `json:"recipient_email"`
	Parameters     []byte             `json:"parameters"`
	LastRunAt      pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SchedulingAgreementHeader struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	AgreementNumber          string             `json:"agreement_number"`
	VendorID                 pgtype.UUID        `json:"vendor_id"`
	PurchasingOrganizationID pgtype.UUID        `json:"purchasing_organization_id"`
	PlantID                  pgtype.UUID        `json:"plant_id"`
	Status                   string             `json:"status"`
	ValidFrom                pgtype.Date        `json:"valid_from"`
	ValidTo                  pgtype.Date        `json:"valid_to"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type SchedulingAgreementItem struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	AgreementHeaderID pgtype.UUID        `json:"agreement_header_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ScheduleLineDate  pgtype.Date        `json:"schedule_line_date"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SerialNumber struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	SerialNumber string             `json:"serial_number"`
	BatchID      pgtype.UUID        `json:"batch_id"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SerialNumberHistory struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	SerialNumberID  pgtype.UUID        `json:"serial_number_id"`
	MovementType    string             `json:"movement_type"`
	FromWarehouseID pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID        `json:"to_warehouse_id"`
	ReferenceID     pgtype.UUID        `json:"reference_id"`
	ReferenceType   pgtype.Text        `json:"reference_type"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Shipment struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ShipmentNumber string             `json:"shipment_number"`
	SalesOrderID   pgtype.UUID        `json:"sales_order_id"`
	WarehouseID    pgtype.UUID        `json:"warehouse_id"`
	CarrierName    pgtype.Text        `json:"carrier_name"`
	TrackingNumber pgtype.Text        `json:"tracking_number"`
	Status         string             `json:"status"`
	ShippedAt      pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ShipmentLine struct {
	ID         pgtype.UUID        `json:"id"`
	ShipmentID pgtype.UUID        `json:"shipment_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SourceList struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	PlantID            pgtype.UUID        `json:"plant_id"`
	VendorID           pgtype.UUID        `json:"vendor_id"`
	PreferredIndicator bool               `json:"preferred_indicator"`
	ValidFrom          pgtype.Date        `json:"valid_from"`
	ValidTo            pgtype.Date        `json:"valid_to"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SourceListCondition struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SourceListID  pgtype.UUID        `json:"source_list_id"`
	ConditionType string             `json:"condition_type"`
	Amount        pgtype.Numeric     `json:"amount"`
	Percent       pgtype.Numeric     `json:"percent"`
	ValidFrom     pgtype.Date        `json:"valid_from"`
	ValidTo       pgtype.Date        `json:"valid_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type StorageLocation struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	PlantID   pgtype.UUID        `json:"plant_id"`
	Code      string             `json:"code"`
	Name      pgtype.Text        `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StorageLocationText struct {
	ID                pgtype.UUID `json:"id"`
	StorageLocationID pgtype.UUID `json:"storage_location_id"`
	LanguageCode      string      `json:"language_code"`
	Description       pgtype.Text `json:"description"`
}

type TaxRule struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Name         string             `json:"name"`
	Rate         pgtype.Numeric     `json:"rate"`
	Type         string             `json:"type"`
	ApplicableTo string             `json:"applicable_to"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantSetting struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	DisplayName          string             `json:"display_name"`
	FiscalYearStartMonth int32              `json:"fiscal_year_start_month"`
	BaseCurrency         string             `json:"base_currency"`
	Locale               string             `json:"locale"`
	Timezone             string             `json:"timezone"`
	FeatureFlags         []byte             `json:"feature_flags"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID     pgtype.UUID        `json:"user_id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type ValuationArea struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	CompanyCodeID pgtype.UUID        `json:"company_code_id"`
	PlantID       pgtype.UUID        `json:"plant_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Vendor struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	ContactPerson pgtype.Text        `json:"contact_person"`
	Email         pgtype.Text        `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	Address       pgtype.Text        `json:"address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	StatusNotes   pgtype.Text        `json:"status_notes"`
	Gstin         pgtype.Text        `json:"gstin"`
	Pan           pgtype.Text        `json:"pan"`
}

type VendorInvoice struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	VendorID      pgtype.UUID        `json:"vendor_id"`
	PoID          pgtype.UUID        `json:"po_id"`
	InvoiceNumber string             `json:"invoice_number"`
	InvoiceDate   pgtype.Date        `json:"invoice_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TdsSection    pgtype.Text        `json:"tds_section"`
	TdsRate       pgtype.Numeric     `json:"tds_rate"`
	TdsAmount     pgtype.Numeric     `json:"tds_amount"`
	TdsPaidAt     pgtype.Timestamptz `json:"tds_paid_at"`
	ChallanNumber pgtype.Text        `json:"challan_number"`
}

type Warehouse struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Location  pgtype.Text        `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WarehouseBin struct {
	ID        pgtype.UUID        `json:"id"`
	ShelfID   pgtype.UUID        `json:"shelf_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WarehouseRack struct {
	ID        pgtype.UUID        `json:"id"`
	ZoneID    pgtype.UUID        `json:"zone_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WarehouseShelf struct {
	ID        pgtype.UUID        `json:"id"`
	RackID    pgtype.UUID        `json:"rack_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WarehouseTransfer struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	FromWarehouseID pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID        `json:"to_warehouse_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type WarehouseZone struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WarehouseID pgtype.UUID        `json:"warehouse_id"`
	Code        string             `json:"code"`
	Name        pgtype.Text        `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkCenter struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CostCenterID pgtype.UUID        `json:"cost_center_id"`
	PlantID      pgtype.UUID        `json:"plant_id"`
	CapacityUnit string             `json:"capacity_unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WorkCenterCapacity struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkCenterID      pgtype.UUID        `json:"work_center_id"`
	CapacityType      string             `json:"capacity_type"`
	AvailableCapacity pgtype.Numeric     `json:"available_capacity"`
	CapacityUnit      string             `json:"capacity_unit"`
	ValidFrom         pgtype.Date        `json:"valid_from"`
	ValidTo           pgtype.Date        `json:"valid_to"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WoNumber          string             `json:"wo_number"`
	BomID             pgtype.UUID        `json:"bom_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	SalesOrderID      pgtype.UUID        `json:"sales_order_id"`
	Status            string             `json:"status"`
	PlannedQuantity   pgtype.Numeric     `json:"planned_quantity"`
	ProducedQuantity  pgtype.Numeric     `json:"produced_quantity"`
	StartDate         pgtype.Date        `json:"start_date"`
	EndDate           pgtype.Date        `json:"end_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProductionOrderID pgtype.UUID        `json:"production_order_id"`
	OperationType     pgtype.Text        `json:"operation_type"`
	Sequence          int32              `json:"sequence"`
	MachineID         pgtype.UUID        `json:"machine_id"`
	ScheduledStart    pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd      pgtype.Timestamptz `json:"scheduled_end"`
}

type WorkflowDefinition struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	EntityType  string             `json:"entity_type"`
	StepsConfig []byte             `json:"steps_config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkflowInstance struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	WorkflowDefinitionID pgtype.UUID        `json:"workflow_definition_id"`
	EntityType           string             `json:"entity_type"`
	EntityID             pgtype.UUID        `json:"entity_id"`
	CurrentStep          int32              `json:"current_step"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
