// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBOMItem(ctx context.Context, arg AddBOMItemParams) (BomItem, error)
	AddInvoiceLineItem(ctx context.Context, arg AddInvoiceLineItemParams) (AddInvoiceLineItemRow, error)
	AddPurchaseOrderItem(ctx context.Context, arg AddPurchaseOrderItemParams) (PurchaseOrderItem, error)
	AddSalesOrderItem(ctx context.Context, arg AddSalesOrderItemParams) (SalesOrderItem, error)
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CompleteWarehouseTransfer(ctx context.Context, arg CompleteWarehouseTransferParams) error
	CountChartOfAccounts(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountCompanyCodes(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountCostCenters(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountGLAccounts(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountGLAccountsByChart(ctx context.Context, arg CountGLAccountsByChartParams) (int64, error)
	CountPlants(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBOM(ctx context.Context, arg CreateBOMParams) (Bom, error)
	CreateChartOfAccounts(ctx context.Context, arg CreateChartOfAccountsParams) (ChartOfAccount, error)
	CreateCoilConsumptionLog(ctx context.Context, arg CreateCoilConsumptionLogParams) (CoilConsumptionLog, error)
	CreateCompanyCode(ctx context.Context, arg CreateCompanyCodeParams) (CompanyCode, error)
	CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error)
	CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error)
	CreateGLAccount(ctx context.Context, arg CreateGLAccountParams) (GlAccount, error)
	CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (GoodsReceipt, error)
	// Reservations
	CreateInventoryReservation(ctx context.Context, arg CreateInventoryReservationParams) (InventoryReservation, error)
	CreateInventoryTransaction(ctx context.Context, arg CreateInventoryTransactionParams) (CreateInventoryTransactionRow, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error)
	// Machines
	CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlant(ctx context.Context, arg CreatePlantParams) (Plant, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	// Batches (product_batches table)
	CreateProductBatch(ctx context.Context, arg CreateProductBatchParams) (ProductBatch, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	// Production lines
	CreateProductionLine(ctx context.Context, arg CreateProductionLineParams) (ProductionLine, error)
	// Production orders
	CreateProductionOrder(ctx context.Context, arg CreateProductionOrderParams) (ProductionOrder, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseRequisition(ctx context.Context, arg CreatePurchaseRequisitionParams) (PurchaseRequisition, error)
	CreatePurchaseRequisitionItem(ctx context.Context, arg CreatePurchaseRequisitionItemParams) (PurchaseRequisitionItem, error)
	// Quality inspections
	CreateQualityInspection(ctx context.Context, arg CreateQualityInspectionParams) (QualityInspection, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error)
	CreateScheduledReport(ctx context.Context, arg CreateScheduledReportParams) (ScheduledReport, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	CreateShipmentLine(ctx context.Context, arg CreateShipmentLineParams) (ShipmentLine, error)
	CreateTaxRule(ctx context.Context, arg CreateTaxRuleParams) (TaxRule, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (CreateVendorRow, error)
	CreateVendorInvoice(ctx context.Context, arg CreateVendorInvoiceParams) (CreateVendorInvoiceRow, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	CreateWarehouseBin(ctx context.Context, arg CreateWarehouseBinParams) (WarehouseBin, error)
	CreateWarehouseRack(ctx context.Context, arg CreateWarehouseRackParams) (WarehouseRack, error)
	CreateWarehouseShelf(ctx context.Context, arg CreateWarehouseShelfParams) (WarehouseShelf, error)
	// Warehouse transfers
	CreateWarehouseTransfer(ctx context.Context, arg CreateWarehouseTransferParams) (WarehouseTransfer, error)
	CreateWarehouseZone(ctx context.Context, arg CreateWarehouseZoneParams) (WarehouseZone, error)
	CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error)
	CreateWorkOrderForProductionOrder(ctx context.Context, arg CreateWorkOrderForProductionOrderParams) (WorkOrder, error)
	DeleteChartOfAccounts(ctx context.Context, arg DeleteChartOfAccountsParams) error
	DeleteCompanyCode(ctx context.Context, arg DeleteCompanyCodeParams) error
	DeleteCostCenter(ctx context.Context, arg DeleteCostCenterParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteGLAccount(ctx context.Context, arg DeleteGLAccountParams) error
	DeletePlant(ctx context.Context, arg DeletePlantParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteSalesOrderItem(ctx context.Context, arg DeleteSalesOrderItemParams) error
	DeleteScheduledReport(ctx context.Context, arg DeleteScheduledReportParams) error
	DeleteVendor(ctx context.Context, arg DeleteVendorParams) error
	GetBOMByProduct(ctx context.Context, arg GetBOMByProductParams) (Bom, error)
	GetChartOfAccounts(ctx context.Context, arg GetChartOfAccountsParams) (ChartOfAccount, error)
	GetChartOfAccountsByCode(ctx context.Context, arg GetChartOfAccountsByCodeParams) (ChartOfAccount, error)
	GetCompanyCode(ctx context.Context, arg GetCompanyCodeParams) (CompanyCode, error)
	GetCompanyCodeByCode(ctx context.Context, arg GetCompanyCodeByCodeParams) (CompanyCode, error)
	// Company profile (one row per tenant) — India: state_code, tan
	GetCompanyProfile(ctx context.Context, tenantID pgtype.UUID) (GetCompanyProfileRow, error)
	GetCostCenter(ctx context.Context, arg GetCostCenterParams) (CostCenter, error)
	GetCostCenterByCode(ctx context.Context, arg GetCostCenterByCodeParams) (CostCenter, error)
	GetCustomer(ctx context.Context, arg GetCustomerParams) (GetCustomerRow, error)
	GetDailySales(ctx context.Context, tenantID pgtype.UUID) ([]GetDailySalesRow, error)
	GetDailySalesWithRange(ctx context.Context, arg GetDailySalesWithRangeParams) ([]GetDailySalesWithRangeRow, error)
	GetDocumentNumberSeries(ctx context.Context, arg GetDocumentNumberSeriesParams) (DocumentNumberSeries, error)
	GetGLAccount(ctx context.Context, arg GetGLAccountParams) (GlAccount, error)
	GetGLAccountByNumber(ctx context.Context, arg GetGLAccountByNumberParams) (GlAccount, error)
	GetGoodsReceipt(ctx context.Context, arg GetGoodsReceiptParams) (GoodsReceipt, error)
	GetInventoryValuation(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error)
	GetInvoice(ctx context.Context, arg GetInvoiceParams) (GetInvoiceRow, error)
	GetLastCoilRemainingByProduct(ctx context.Context, arg GetLastCoilRemainingByProductParams) (pgtype.Numeric, error)
	GetNextDocumentNumber(ctx context.Context, arg GetNextDocumentNumberParams) (GetNextDocumentNumberRow, error)
	GetPlant(ctx context.Context, arg GetPlantParams) (Plant, error)
	GetPlantByCode(ctx context.Context, arg GetPlantByCodeParams) (Plant, error)
	GetProcurementSpend30d(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error)
	GetProduct(ctx context.Context, arg GetProductParams) (GetProductRow, error)
	GetProductStock(ctx context.Context, arg GetProductStockParams) (pgtype.Numeric, error)
	GetProductionLine(ctx context.Context, arg GetProductionLineParams) (ProductionLine, error)
	GetProductionOrder(ctx context.Context, arg GetProductionOrderParams) (ProductionOrder, error)
	GetProductionOutput(ctx context.Context, tenantID pgtype.UUID) ([]GetProductionOutputRow, error)
	GetProductionOutputWithRange(ctx context.Context, arg GetProductionOutputWithRangeParams) ([]GetProductionOutputWithRangeRow, error)
	GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error)
	GetPurchaseOrderCount30d(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	GetPurchaseRequisition(ctx context.Context, arg GetPurchaseRequisitionParams) (PurchaseRequisition, error)
	GetRoleByTenantAndName(ctx context.Context, arg GetRoleByTenantAndNameParams) (Role, error)
	GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (SalesOrder, error)
	GetSalesOrderItemByID(ctx context.Context, arg GetSalesOrderItemByIDParams) (SalesOrderItem, error)
	GetScheduledReport(ctx context.Context, arg GetScheduledReportParams) (ScheduledReport, error)
	GetShipment(ctx context.Context, arg GetShipmentParams) (Shipment, error)
	GetStockAgingOver90d(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantSettings(ctx context.Context, tenantID pgtype.UUID) (TenantSetting, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVendor(ctx context.Context, arg GetVendorParams) (GetVendorRow, error)
	GetVendorCount(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	GetVendorInvoice(ctx context.Context, arg GetVendorInvoiceParams) (GetVendorInvoiceRow, error)
	GetWarehouseTransfer(ctx context.Context, arg GetWarehouseTransferParams) (WarehouseTransfer, error)
	GetWarehouseZone(ctx context.Context, arg GetWarehouseZoneParams) (WarehouseZone, error)
	GetWorkOrder(ctx context.Context, arg GetWorkOrderParams) (WorkOrder, error)
	InsertReportAccessLog(ctx context.Context, arg InsertReportAccessLogParams) (pgtype.UUID, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	// BOM items (for MRP and UI)
	ListBOMItemsByBOM(ctx context.Context, arg ListBOMItemsByBOMParams) ([]BomItem, error)
	ListBOMs(ctx context.Context, tenantID pgtype.UUID) ([]Bom, error)
	ListBatchesByProduct(ctx context.Context, arg ListBatchesByProductParams) ([]ProductBatch, error)
	// Chart of accounts
	ListChartOfAccounts(ctx context.Context, arg ListChartOfAccountsParams) ([]ChartOfAccount, error)
	ListCoilConsumptionLogs(ctx context.Context, arg ListCoilConsumptionLogsParams) ([]ListCoilConsumptionLogsRow, error)
	ListCoilConsumptionLogsByProduct(ctx context.Context, arg ListCoilConsumptionLogsByProductParams) ([]ListCoilConsumptionLogsByProductRow, error)
	// Company codes
	ListCompanyCodes(ctx context.Context, arg ListCompanyCodesParams) ([]CompanyCode, error)
	// Cost centers
	ListCostCenters(ctx context.Context, arg ListCostCentersParams) ([]CostCenter, error)
	ListCostCentersByCompanyCode(ctx context.Context, arg ListCostCentersByCompanyCodeParams) ([]CostCenter, error)
	ListCustomFields(ctx context.Context, arg ListCustomFieldsParams) ([]CustomField, error)
	ListCustomers(ctx context.Context, tenantID pgtype.UUID) ([]ListCustomersRow, error)
	// G/L accounts (require chart_of_accounts_id; company_code comes from chart/usage)
	ListGLAccounts(ctx context.Context, arg ListGLAccountsParams) ([]GlAccount, error)
	ListGLAccountsByChart(ctx context.Context, arg ListGLAccountsByChartParams) ([]GlAccount, error)
	ListGoodsReceipts(ctx context.Context, tenantID pgtype.UUID) ([]GoodsReceipt, error)
	ListInventoryTransactions(ctx context.Context, arg ListInventoryTransactionsParams) ([]ListInventoryTransactionsRow, error)
	// Inventory valuation by product (current_stock * unit price per product)
	ListInventoryValuationByProduct(ctx context.Context, tenantID pgtype.UUID) ([]ListInventoryValuationByProductRow, error)
	ListInvoiceLineItems(ctx context.Context, arg ListInvoiceLineItemsParams) ([]ListInvoiceLineItemsRow, error)
	ListInvoices(ctx context.Context, tenantID pgtype.UUID) ([]ListInvoicesRow, error)
	// GSTR-ready: inward supplies (purchase) by vendor invoice date (no line-level HSN on vendor_invoices yet)
	ListInwardSuppliesByDateRange(ctx context.Context, arg ListInwardSuppliesByDateRangeParams) ([]ListInwardSuppliesByDateRangeRow, error)
	ListMachines(ctx context.Context, tenantID pgtype.UUID) ([]Machine, error)
	ListMachinesByProductionLine(ctx context.Context, arg ListMachinesByProductionLineParams) ([]Machine, error)
	ListMaterialConsumptionByWorkOrder(ctx context.Context, arg ListMaterialConsumptionByWorkOrderParams) ([]MaterialConsumption, error)
	// GSTR-ready: outward supplies (sales) by invoice date with line-level HSN and tax (GSTR-1 style)
	ListOutwardSuppliesByDateRange(ctx context.Context, arg ListOutwardSuppliesByDateRangeParams) ([]ListOutwardSuppliesByDateRangeRow, error)
	ListPaymentsByInvoice(ctx context.Context, arg ListPaymentsByInvoiceParams) ([]Payment, error)
	// Plants
	ListPlants(ctx context.Context, arg ListPlantsParams) ([]Plant, error)
	ListProductCategories(ctx context.Context, tenantID pgtype.UUID) ([]ProductCategory, error)
	ListProductStockLevels(ctx context.Context, tenantID pgtype.UUID) ([]ListProductStockLevelsRow, error)
	ListProductionLines(ctx context.Context, tenantID pgtype.UUID) ([]ProductionLine, error)
	ListProductionLogsByWorkOrder(ctx context.Context, arg ListProductionLogsByWorkOrderParams) ([]ProductionLog, error)
	ListProductionOrders(ctx context.Context, tenantID pgtype.UUID) ([]ProductionOrder, error)
	ListProducts(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsRow, error)
	// Production: products below reorder point (low-stock alerts)
	ListProductsBelowReorderPoint(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsBelowReorderPointRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error)
	// Purchase history: PO items with date, vendor, product (for "Reva item purchase history" view)
	ListPurchaseHistory(ctx context.Context, arg ListPurchaseHistoryParams) ([]ListPurchaseHistoryRow, error)
	ListPurchaseOrderItems(ctx context.Context, arg ListPurchaseOrderItemsParams) ([]PurchaseOrderItem, error)
	ListPurchaseOrders(ctx context.Context, tenantID pgtype.UUID) ([]PurchaseOrder, error)
	ListPurchaseRequisitionItems(ctx context.Context, requisitionID pgtype.UUID) ([]PurchaseRequisitionItem, error)
	ListPurchaseRequisitions(ctx context.Context, arg ListPurchaseRequisitionsParams) ([]PurchaseRequisition, error)
	ListQualityInspectionsByWorkOrder(ctx context.Context, arg ListQualityInspectionsByWorkOrderParams) ([]QualityInspection, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]InventoryReservation, error)
	ListSalesOrderItems(ctx context.Context, arg ListSalesOrderItemsParams) ([]SalesOrderItem, error)
	ListSalesOrders(ctx context.Context, tenantID pgtype.UUID) ([]SalesOrder, error)
	// Sales summary by HSN for a date range (GSTR-1 table 12 style)
	ListSalesSummaryByHSN(ctx context.Context, arg ListSalesSummaryByHSNParams) ([]ListSalesSummaryByHSNRow, error)
	ListScheduledReports(ctx context.Context, tenantID pgtype.UUID) ([]ScheduledReport, error)
	ListShipmentLines(ctx context.Context, shipmentID pgtype.UUID) ([]ShipmentLine, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error)
	// Production: stock per product per warehouse
	ListStockByWarehouse(ctx context.Context, tenantID pgtype.UUID) ([]ListStockByWarehouseRow, error)
	// Stock levels with Reva fields (STOCK COIL tab: name, type, # stock, status, tr_notes). Optional category filter.
	ListStockLevelsWithReva(ctx context.Context, arg ListStockLevelsWithRevaParams) ([]ListStockLevelsWithRevaRow, error)
	ListTaxRules(ctx context.Context, tenantID pgtype.UUID) ([]TaxRule, error)
	ListVendorInvoices(ctx context.Context, tenantID pgtype.UUID) ([]ListVendorInvoicesRow, error)
	ListVendors(ctx context.Context, tenantID pgtype.UUID) ([]ListVendorsRow, error)
	ListWarehouseBins(ctx context.Context, shelfID pgtype.UUID) ([]WarehouseBin, error)
	ListWarehouseRacks(ctx context.Context, zoneID pgtype.UUID) ([]WarehouseRack, error)
	ListWarehouseShelves(ctx context.Context, rackID pgtype.UUID) ([]WarehouseShelf, error)
	ListWarehouseTransfers(ctx context.Context, arg ListWarehouseTransfersParams) ([]WarehouseTransfer, error)
	ListWarehouseZones(ctx context.Context, arg ListWarehouseZonesParams) ([]WarehouseZone, error)
	ListWarehouses(ctx context.Context, tenantID pgtype.UUID) ([]Warehouse, error)
	ListWorkOrders(ctx context.Context, tenantID pgtype.UUID) ([]WorkOrder, error)
	ListWorkOrdersByProductionOrder(ctx context.Context, arg ListWorkOrdersByProductionOrderParams) ([]WorkOrder, error)
	NextInvoiceNumber(ctx context.Context, arg NextInvoiceNumberParams) (int32, error)
	RecordMaterialConsumption(ctx context.Context, arg RecordMaterialConsumptionParams) (MaterialConsumption, error)
	RecordProductionLog(ctx context.Context, arg RecordProductionLogParams) (ProductionLog, error)
	SumPaymentsByInvoice(ctx context.Context, arg SumPaymentsByInvoiceParams) (pgtype.Numeric, error)
	UpdateChartOfAccounts(ctx context.Context, arg UpdateChartOfAccountsParams) (ChartOfAccount, error)
	UpdateCompanyCode(ctx context.Context, arg UpdateCompanyCodeParams) (CompanyCode, error)
	UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error)
	UpdateGLAccount(ctx context.Context, arg UpdateGLAccountParams) (GlAccount, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error
	UpdatePlant(ctx context.Context, arg UpdatePlantParams) (Plant, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductionOrderStatus(ctx context.Context, arg UpdateProductionOrderStatusParams) error
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error
	UpdatePurchaseRequisitionStatus(ctx context.Context, arg UpdatePurchaseRequisitionStatusParams) (PurchaseRequisition, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
	UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) error
	UpdateSalesOrderTotal(ctx context.Context, arg UpdateSalesOrderTotalParams) error
	UpdateScheduledReportNextRun(ctx context.Context, arg UpdateScheduledReportNextRunParams) error
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (UpdateVendorRow, error)
	UpdateVendorInvoiceStatus(ctx context.Context, arg UpdateVendorInvoiceStatusParams) error
	UpdateVendorInvoiceTDS(ctx context.Context, arg UpdateVendorInvoiceTDSParams) (UpdateVendorInvoiceTDSRow, error)
	UpdateWorkOrderProducedQty(ctx context.Context, arg UpdateWorkOrderProducedQtyParams) error
	UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) error
	UpsertCompanyProfile(ctx context.Context, arg UpsertCompanyProfileParams) (UpsertCompanyProfileRow, error)
	UpsertDocumentNumberSeries(ctx context.Context, arg UpsertDocumentNumberSeriesParams) (DocumentNumberSeries, error)
	UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error)
}

var _ Querier = (*Queries)(nil)
