// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySales = `-- name: GetDailySales :many
SELECT DATE(created_at) AS sale_date, SUM(total_amount)::DECIMAL AS total_revenue
FROM sales_orders
WHERE tenant_id = $1 AND status != 'CANCELLED'
  AND created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY sale_date DESC
`

type GetDailySalesRow struct {
	SaleDate     pgtype.Date    `json:"sale_date"`
	TotalRevenue pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetDailySales(ctx context.Context, tenantID pgtype.UUID) ([]GetDailySalesRow, error) {
	rows, err := q.db.Query(ctx, getDailySales, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySalesRow
	for rows.Next() {
		var i GetDailySalesRow
		if err := rows.Scan(&i.SaleDate, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySalesWithRange = `-- name: GetDailySalesWithRange :many
SELECT DATE(created_at) AS sale_date, SUM(total_amount)::DECIMAL AS total_revenue
FROM sales_orders
WHERE tenant_id = $1 AND status != 'CANCELLED'
  AND created_at >= $2::date
  AND created_at < ($3::date + INTERVAL '1 day')
GROUP BY DATE(created_at)
ORDER BY sale_date DESC
`

type GetDailySalesWithRangeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

type GetDailySalesWithRangeRow struct {
	SaleDate     pgtype.Date    `json:"sale_date"`
	TotalRevenue pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetDailySalesWithRange(ctx context.Context, arg GetDailySalesWithRangeParams) ([]GetDailySalesWithRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailySalesWithRange, arg.TenantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySalesWithRangeRow
	for rows.Next() {
		var i GetDailySalesWithRangeRow
		if err := rows.Scan(&i.SaleDate, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryValuation = `-- name: GetInventoryValuation :one
WITH stock_data AS (
    SELECT product_id, SUM(
        CASE WHEN transaction_type = 'IN' THEN quantity
             WHEN transaction_type = 'OUT' THEN -quantity
             ELSE 0 END
    ) AS current_stock
    FROM inventory_transactions
    WHERE tenant_id = $1
    GROUP BY product_id
)
SELECT COALESCE(SUM(s.current_stock * p.price), 0)::DECIMAL AS total_valuation
FROM stock_data s
JOIN products p ON p.id = s.product_id
WHERE p.tenant_id = $1
`

func (q *Queries) GetInventoryValuation(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getInventoryValuation, tenantID)
	var total_valuation pgtype.Numeric
	err := row.Scan(&total_valuation)
	return total_valuation, err
}

const getProcurementSpend30d = `-- name: GetProcurementSpend30d :one
SELECT COALESCE(SUM(total_amount), 0)::DECIMAL AS total_spend
FROM vendor_invoices
WHERE tenant_id = $1
  AND invoice_date >= CURRENT_DATE - INTERVAL '30 days'
  AND status != 'CANCELLED'
`

func (q *Queries) GetProcurementSpend30d(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getProcurementSpend30d, tenantID)
	var total_spend pgtype.Numeric
	err := row.Scan(&total_spend)
	return total_spend, err
}

const getProductionOutput = `-- name: GetProductionOutput :many
SELECT DATE(produced_at) AS production_date, SUM(quantity)::DECIMAL AS total_produced
FROM production_logs
WHERE tenant_id = $1
  AND produced_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY DATE(produced_at)
ORDER BY production_date DESC
`

type GetProductionOutputRow struct {
	ProductionDate pgtype.Date    `json:"production_date"`
	TotalProduced  pgtype.Numeric `json:"total_produced"`
}

func (q *Queries) GetProductionOutput(ctx context.Context, tenantID pgtype.UUID) ([]GetProductionOutputRow, error) {
	rows, err := q.db.Query(ctx, getProductionOutput, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductionOutputRow
	for rows.Next() {
		var i GetProductionOutputRow
		if err := rows.Scan(&i.ProductionDate, &i.TotalProduced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionOutputWithRange = `-- name: GetProductionOutputWithRange :many
SELECT DATE(produced_at) AS production_date, SUM(quantity)::DECIMAL AS total_produced
FROM production_logs
WHERE tenant_id = $1
  AND produced_at >= $2::date
  AND produced_at < ($3::date + INTERVAL '1 day')
GROUP BY DATE(produced_at)
ORDER BY production_date DESC
`

type GetProductionOutputWithRangeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

type GetProductionOutputWithRangeRow struct {
	ProductionDate pgtype.Date    `json:"production_date"`
	TotalProduced  pgtype.Numeric `json:"total_produced"`
}

func (q *Queries) GetProductionOutputWithRange(ctx context.Context, arg GetProductionOutputWithRangeParams) ([]GetProductionOutputWithRangeRow, error) {
	rows, err := q.db.Query(ctx, getProductionOutputWithRange, arg.TenantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductionOutputWithRangeRow
	for rows.Next() {
		var i GetProductionOutputWithRangeRow
		if err := rows.Scan(&i.ProductionDate, &i.TotalProduced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrderCount30d = `-- name: GetPurchaseOrderCount30d :one
SELECT COUNT(*)::BIGINT AS po_count
FROM purchase_orders
WHERE tenant_id = $1
  AND created_at >= CURRENT_DATE - INTERVAL '30 days'
  AND status != 'CANCELLED'
`

func (q *Queries) GetPurchaseOrderCount30d(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderCount30d, tenantID)
	var po_count int64
	err := row.Scan(&po_count)
	return po_count, err
}

const getStockAgingOver90d = `-- name: GetStockAgingOver90d :one
SELECT COALESCE(SUM(net_qty * p.price), 0)::DECIMAL AS aging_value
FROM (
    SELECT t.product_id, t.batch_id,
        SUM(CASE WHEN t.transaction_type = 'IN' THEN t.quantity WHEN t.transaction_type = 'OUT' THEN -t.quantity ELSE 0 END) AS net_qty
    FROM inventory_transactions t
    WHERE t.tenant_id = $1
    GROUP BY t.product_id, t.batch_id
    HAVING SUM(CASE WHEN t.transaction_type = 'IN' THEN t.quantity WHEN t.transaction_type = 'OUT' THEN -t.quantity ELSE 0 END) > 0
) it
JOIN products p ON p.id = it.product_id AND p.tenant_id = $1
LEFT JOIN product_batches pb ON pb.id = it.batch_id
WHERE pb.manufacture_date IS NOT NULL AND pb.manufacture_date < CURRENT_DATE - INTERVAL '90 days'
`

func (q *Queries) GetStockAgingOver90d(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getStockAgingOver90d, tenantID)
	var aging_value pgtype.Numeric
	err := row.Scan(&aging_value)
	return aging_value, err
}

const getVendorCount = `-- name: GetVendorCount :one
SELECT COUNT(*)::BIGINT AS vendor_count FROM vendors WHERE tenant_id = $1
`

func (q *Queries) GetVendorCount(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getVendorCount, tenantID)
	var vendor_count int64
	err := row.Scan(&vendor_count)
	return vendor_count, err
}
