// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requisitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseRequisition = `-- name: CreatePurchaseRequisition :one
INSERT INTO purchase_requisitions (tenant_id, req_number, department, requester_id, status, expected_delivery_date, budget)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, req_number, department, requester_id, status, expected_delivery_date, budget, created_at, updated_at
`

type CreatePurchaseRequisitionParams struct {
	TenantID             pgtype.UUID    `json:"tenant_id"`
	ReqNumber            string         `json:"req_number"`
	Department           pgtype.Text    `json:"department"`
	RequesterID          pgtype.UUID    `json:"requester_id"`
	Status               string         `json:"status"`
	ExpectedDeliveryDate pgtype.Date    `json:"expected_delivery_date"`
	Budget               pgtype.Numeric `json:"budget"`
}

func (q *Queries) CreatePurchaseRequisition(ctx context.Context, arg CreatePurchaseRequisitionParams) (PurchaseRequisition, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequisition,
		arg.TenantID,
		arg.ReqNumber,
		arg.Department,
		arg.RequesterID,
		arg.Status,
		arg.ExpectedDeliveryDate,
		arg.Budget,
	)
	var i PurchaseRequisition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReqNumber,
		&i.Department,
		&i.RequesterID,
		&i.Status,
		&i.ExpectedDeliveryDate,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPurchaseRequisitionItem = `-- name: CreatePurchaseRequisitionItem :one
INSERT INTO purchase_requisition_items (requisition_id, product_id, quantity, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, requisition_id, product_id, quantity, notes, created_at
`

type CreatePurchaseRequisitionItemParams struct {
	RequisitionID pgtype.UUID    `json:"requisition_id"`
	ProductID     pgtype.UUID    `json:"product_id"`
	Quantity      pgtype.Numeric `json:"quantity"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) CreatePurchaseRequisitionItem(ctx context.Context, arg CreatePurchaseRequisitionItemParams) (PurchaseRequisitionItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequisitionItem,
		arg.RequisitionID,
		arg.ProductID,
		arg.Quantity,
		arg.Notes,
	)
	var i PurchaseRequisitionItem
	err := row.Scan(
		&i.ID,
		&i.RequisitionID,
		&i.ProductID,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchaseRequisition = `-- name: GetPurchaseRequisition :one
SELECT id, tenant_id, req_number, department, requester_id, status, expected_delivery_date, budget, created_at, updated_at
FROM purchase_requisitions
WHERE id = $1 AND tenant_id = $2
`

type GetPurchaseRequisitionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPurchaseRequisition(ctx context.Context, arg GetPurchaseRequisitionParams) (PurchaseRequisition, error) {
	row := q.db.QueryRow(ctx, getPurchaseRequisition, arg.ID, arg.TenantID)
	var i PurchaseRequisition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReqNumber,
		&i.Department,
		&i.RequesterID,
		&i.Status,
		&i.ExpectedDeliveryDate,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurchaseRequisitionItems = `-- name: ListPurchaseRequisitionItems :many
SELECT id, requisition_id, product_id, quantity, notes, created_at
FROM purchase_requisition_items
WHERE requisition_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPurchaseRequisitionItems(ctx context.Context, requisitionID pgtype.UUID) ([]PurchaseRequisitionItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequisitionItems, requisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequisitionItem
	for rows.Next() {
		var i PurchaseRequisitionItem
		if err := rows.Scan(
			&i.ID,
			&i.RequisitionID,
			&i.ProductID,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseRequisitions = `-- name: ListPurchaseRequisitions :many
SELECT id, tenant_id, req_number, department, requester_id, status, expected_delivery_date, budget, created_at, updated_at
FROM purchase_requisitions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseRequisitionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListPurchaseRequisitions(ctx context.Context, arg ListPurchaseRequisitionsParams) ([]PurchaseRequisition, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequisitions, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequisition
	for rows.Next() {
		var i PurchaseRequisition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReqNumber,
			&i.Department,
			&i.RequesterID,
			&i.Status,
			&i.ExpectedDeliveryDate,
			&i.Budget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchaseRequisitionStatus = `-- name: UpdatePurchaseRequisitionStatus :one
UPDATE purchase_requisitions
SET status = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, req_number, department, requester_id, status, expected_delivery_date, budget, created_at, updated_at
`

type UpdatePurchaseRequisitionStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdatePurchaseRequisitionStatus(ctx context.Context, arg UpdatePurchaseRequisitionStatusParams) (PurchaseRequisition, error) {
	row := q.db.QueryRow(ctx, updatePurchaseRequisitionStatus, arg.ID, arg.TenantID, arg.Status)
	var i PurchaseRequisition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReqNumber,
		&i.Department,
		&i.RequesterID,
		&i.Status,
		&i.ExpectedDeliveryDate,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
