// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInvoiceLineItem = `-- name: AddInvoiceLineItem :one
INSERT INTO invoice_line_items (tenant_id, invoice_id, description, quantity, unit_price, total_line, sort_order, hsn_sac, taxable_value, cgst, sgst, igst)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, invoice_id, description, quantity, unit_price, total_line, sort_order, hsn_sac, taxable_value, cgst, sgst, igst, created_at
`

type AddInvoiceLineItemParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	InvoiceID    pgtype.UUID    `json:"invoice_id"`
	Description  string         `json:"description"`
	Quantity     pgtype.Numeric `json:"quantity"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
	TotalLine    pgtype.Numeric `json:"total_line"`
	SortOrder    int32          `json:"sort_order"`
	HsnSac       pgtype.Text    `json:"hsn_sac"`
	TaxableValue pgtype.Numeric `json:"taxable_value"`
	Cgst         pgtype.Numeric `json:"cgst"`
	Sgst         pgtype.Numeric `json:"sgst"`
	Igst         pgtype.Numeric `json:"igst"`
}

type AddInvoiceLineItemRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	InvoiceID    pgtype.UUID        `json:"invoice_id"`
	Description  string             `json:"description"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	UnitPrice    pgtype.Numeric     `json:"unit_price"`
	TotalLine    pgtype.Numeric     `json:"total_line"`
	SortOrder    int32              `json:"sort_order"`
	HsnSac       pgtype.Text        `json:"hsn_sac"`
	TaxableValue pgtype.Numeric     `json:"taxable_value"`
	Cgst         pgtype.Numeric     `json:"cgst"`
	Sgst         pgtype.Numeric     `json:"sgst"`
	Igst         pgtype.Numeric     `json:"igst"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddInvoiceLineItem(ctx context.Context, arg AddInvoiceLineItemParams) (AddInvoiceLineItemRow, error) {
	row := q.db.QueryRow(ctx, addInvoiceLineItem,
		arg.TenantID,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalLine,
		arg.SortOrder,
		arg.HsnSac,
		arg.TaxableValue,
		arg.Cgst,
		arg.Sgst,
		arg.Igst,
	)
	var i AddInvoiceLineItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalLine,
		&i.SortOrder,
		&i.HsnSac,
		&i.TaxableValue,
		&i.Cgst,
		&i.Sgst,
		&i.Igst,
		&i.CreatedAt,
	)
	return i, err
}

const addSalesOrderItem = `-- name: AddSalesOrderItem :one
INSERT INTO sales_order_items (
    tenant_id, so_id, product_id, quantity, unit_price, total_price
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, so_id, product_id, quantity, unit_price, total_price, created_at
`

type AddSalesOrderItemParams struct {
	TenantID   pgtype.UUID    `json:"tenant_id"`
	SoID       pgtype.UUID    `json:"so_id"`
	ProductID  pgtype.UUID    `json:"product_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
	UnitPrice  pgtype.Numeric `json:"unit_price"`
	TotalPrice pgtype.Numeric `json:"total_price"`
}

func (q *Queries) AddSalesOrderItem(ctx context.Context, arg AddSalesOrderItemParams) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, addSalesOrderItem,
		arg.TenantID,
		arg.SoID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SoID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    tenant_id, name, contact_person, email, phone, billing_address, shipping_address, tax_id, gstin, place_of_supply_state, pan
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, name, contact_person, email, phone, billing_address, shipping_address, tax_id, gstin, place_of_supply_state, pan, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	ContactPerson      pgtype.Text `json:"contact_person"`
	Email              pgtype.Text `json:"email"`
	Phone              pgtype.Text `json:"phone"`
	BillingAddress     pgtype.Text `json:"billing_address"`
	ShippingAddress    pgtype.Text `json:"shipping_address"`
	TaxID              pgtype.Text `json:"tax_id"`
	Gstin              pgtype.Text `json:"gstin"`
	PlaceOfSupplyState pgtype.Text `json:"place_of_supply_state"`
	Pan                pgtype.Text `json:"pan"`
}

type CreateCustomerRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	BillingAddress     pgtype.Text        `json:"billing_address"`
	ShippingAddress    pgtype.Text        `json:"shipping_address"`
	TaxID              pgtype.Text        `json:"tax_id"`
	Gstin              pgtype.Text        `json:"gstin"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	Pan                pgtype.Text        `json:"pan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.Phone,
		arg.BillingAddress,
		arg.ShippingAddress,
		arg.TaxID,
		arg.Gstin,
		arg.PlaceOfSupplyState,
		arg.Pan,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Phone,
		&i.BillingAddress,
		&i.ShippingAddress,
		&i.TaxID,
		&i.Gstin,
		&i.PlaceOfSupplyState,
		&i.Pan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    tenant_id, customer_id, so_id, invoice_number, invoice_date, due_date, total_amount, status,
    place_of_supply_state, invoice_type, subtotal, cgst_total, sgst_total, igst_total
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, tenant_id, customer_id, so_id, invoice_number, invoice_date, due_date, total_amount, status,
  place_of_supply_state, invoice_type, subtotal, cgst_total, sgst_total, igst_total, created_at
`

type CreateInvoiceParams struct {
	TenantID           pgtype.UUID    `json:"tenant_id"`
	CustomerID         pgtype.UUID    `json:"customer_id"`
	SoID               pgtype.UUID    `json:"so_id"`
	InvoiceNumber      string         `json:"invoice_number"`
	InvoiceDate        pgtype.Date    `json:"invoice_date"`
	DueDate            pgtype.Date    `json:"due_date"`
	TotalAmount        pgtype.Numeric `json:"total_amount"`
	Status             string         `json:"status"`
	PlaceOfSupplyState pgtype.Text    `json:"place_of_supply_state"`
	InvoiceType        string         `json:"invoice_type"`
	Subtotal           pgtype.Numeric `json:"subtotal"`
	CgstTotal          pgtype.Numeric `json:"cgst_total"`
	SgstTotal          pgtype.Numeric `json:"sgst_total"`
	IgstTotal          pgtype.Numeric `json:"igst_total"`
}

type CreateInvoiceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	SoID               pgtype.UUID        `json:"so_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	InvoiceDate        pgtype.Date        `json:"invoice_date"`
	DueDate            pgtype.Date        `json:"due_date"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	Status             string             `json:"status"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	InvoiceType        string             `json:"invoice_type"`
	Subtotal           pgtype.Numeric     `json:"subtotal"`
	CgstTotal          pgtype.Numeric     `json:"cgst_total"`
	SgstTotal          pgtype.Numeric     `json:"sgst_total"`
	IgstTotal          pgtype.Numeric     `json:"igst_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.TenantID,
		arg.CustomerID,
		arg.SoID,
		arg.InvoiceNumber,
		arg.InvoiceDate,
		arg.DueDate,
		arg.TotalAmount,
		arg.Status,
		arg.PlaceOfSupplyState,
		arg.InvoiceType,
		arg.Subtotal,
		arg.CgstTotal,
		arg.SgstTotal,
		arg.IgstTotal,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.SoID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.PlaceOfSupplyState,
		&i.InvoiceType,
		&i.Subtotal,
		&i.CgstTotal,
		&i.SgstTotal,
		&i.IgstTotal,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    tenant_id, invoice_id, amount, payment_date, payment_method, reference_number, recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, invoice_id, amount, payment_date, payment_method, reference_number, recorded_by, created_at
`

type CreatePaymentParams struct {
	TenantID        pgtype.UUID    `json:"tenant_id"`
	InvoiceID       pgtype.UUID    `json:"invoice_id"`
	Amount          pgtype.Numeric `json:"amount"`
	PaymentDate     pgtype.Date    `json:"payment_date"`
	PaymentMethod   pgtype.Text    `json:"payment_method"`
	ReferenceNumber pgtype.Text    `json:"reference_number"`
	RecordedBy      pgtype.UUID    `json:"recorded_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenantID,
		arg.InvoiceID,
		arg.Amount,
		arg.PaymentDate,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.RecordedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Amount,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (
    tenant_id, customer_id, so_number, status, expected_shipping_date, total_amount, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, customer_id, so_number, status, expected_shipping_date, total_amount, created_by, created_at, updated_at
`

type CreateSalesOrderParams struct {
	TenantID             pgtype.UUID    `json:"tenant_id"`
	CustomerID           pgtype.UUID    `json:"customer_id"`
	SoNumber             string         `json:"so_number"`
	Status               string         `json:"status"`
	ExpectedShippingDate pgtype.Date    `json:"expected_shipping_date"`
	TotalAmount          pgtype.Numeric `json:"total_amount"`
	CreatedBy            pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.SoNumber,
		arg.Status,
		arg.ExpectedShippingDate,
		arg.TotalAmount,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.SoNumber,
		&i.Status,
		&i.ExpectedShippingDate,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1 AND tenant_id = $2
`

type DeleteCustomerParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.TenantID)
	return err
}

const deleteSalesOrderItem = `-- name: DeleteSalesOrderItem :exec
DELETE FROM sales_order_items
WHERE id = $1 AND tenant_id = $2
`

type DeleteSalesOrderItemParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteSalesOrderItem(ctx context.Context, arg DeleteSalesOrderItemParams) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderItem, arg.ID, arg.TenantID)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, tenant_id, name, contact_person, email, phone, billing_address, shipping_address, tax_id, gstin, place_of_supply_state, pan, created_at, updated_at
FROM customers
WHERE id = $1 AND tenant_id = $2
`

type GetCustomerParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetCustomerRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	BillingAddress     pgtype.Text        `json:"billing_address"`
	ShippingAddress    pgtype.Text        `json:"shipping_address"`
	TaxID              pgtype.Text        `json:"tax_id"`
	Gstin              pgtype.Text        `json:"gstin"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	Pan                pgtype.Text        `json:"pan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ID, arg.TenantID)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Phone,
		&i.BillingAddress,
		&i.ShippingAddress,
		&i.TaxID,
		&i.Gstin,
		&i.PlaceOfSupplyState,
		&i.Pan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, customer_id, so_id, invoice_number, invoice_date, due_date, total_amount, status,
  place_of_supply_state, invoice_type, subtotal, cgst_total, sgst_total, igst_total, created_at
FROM invoices
WHERE tenant_id = $1 AND id = $2
`

type GetInvoiceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetInvoiceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	SoID               pgtype.UUID        `json:"so_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	InvoiceDate        pgtype.Date        `json:"invoice_date"`
	DueDate            pgtype.Date        `json:"due_date"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	Status             string             `json:"status"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	InvoiceType        string             `json:"invoice_type"`
	Subtotal           pgtype.Numeric     `json:"subtotal"`
	CgstTotal          pgtype.Numeric     `json:"cgst_total"`
	SgstTotal          pgtype.Numeric     `json:"sgst_total"`
	IgstTotal          pgtype.Numeric     `json:"igst_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.TenantID, arg.ID)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.SoID,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.PlaceOfSupplyState,
		&i.InvoiceType,
		&i.Subtotal,
		&i.CgstTotal,
		&i.SgstTotal,
		&i.IgstTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, tenant_id, customer_id, so_number, status, expected_shipping_date, total_amount, created_by, created_at, updated_at
FROM sales_orders
WHERE id = $1 AND tenant_id = $2
`

type GetSalesOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, arg.ID, arg.TenantID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.SoNumber,
		&i.Status,
		&i.ExpectedShippingDate,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderItemByID = `-- name: GetSalesOrderItemByID :one
SELECT id, tenant_id, so_id, product_id, quantity, unit_price, total_price, created_at
FROM sales_order_items
WHERE id = $1 AND tenant_id = $2
`

type GetSalesOrderItemByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetSalesOrderItemByID(ctx context.Context, arg GetSalesOrderItemByIDParams) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, getSalesOrderItemByID, arg.ID, arg.TenantID)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SoID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, tenant_id, name, contact_person, email, phone, billing_address, shipping_address, tax_id, gstin, place_of_supply_state, pan, created_at, updated_at
FROM customers
WHERE tenant_id = $1
ORDER BY name ASC
`

type ListCustomersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	BillingAddress     pgtype.Text        `json:"billing_address"`
	ShippingAddress    pgtype.Text        `json:"shipping_address"`
	TaxID              pgtype.Text        `json:"tax_id"`
	Gstin              pgtype.Text        `json:"gstin"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	Pan                pgtype.Text        `json:"pan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomers(ctx context.Context, tenantID pgtype.UUID) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.Phone,
			&i.BillingAddress,
			&i.ShippingAddress,
			&i.TaxID,
			&i.Gstin,
			&i.PlaceOfSupplyState,
			&i.Pan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLineItems = `-- name: ListInvoiceLineItems :many
SELECT id, tenant_id, invoice_id, description, quantity, unit_price, total_line, sort_order,
  hsn_sac, taxable_value, cgst, sgst, igst, created_at
FROM invoice_line_items
WHERE tenant_id = $1 AND invoice_id = $2
ORDER BY sort_order ASC, created_at ASC
`

type ListInvoiceLineItemsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
}

type ListInvoiceLineItemsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	InvoiceID    pgtype.UUID        `json:"invoice_id"`
	Description  string             `json:"description"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	UnitPrice    pgtype.Numeric     `json:"unit_price"`
	TotalLine    pgtype.Numeric     `json:"total_line"`
	SortOrder    int32              `json:"sort_order"`
	HsnSac       pgtype.Text        `json:"hsn_sac"`
	TaxableValue pgtype.Numeric     `json:"taxable_value"`
	Cgst         pgtype.Numeric     `json:"cgst"`
	Sgst         pgtype.Numeric     `json:"sgst"`
	Igst         pgtype.Numeric     `json:"igst"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInvoiceLineItems(ctx context.Context, arg ListInvoiceLineItemsParams) ([]ListInvoiceLineItemsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLineItems, arg.TenantID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoiceLineItemsRow
	for rows.Next() {
		var i ListInvoiceLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalLine,
			&i.SortOrder,
			&i.HsnSac,
			&i.TaxableValue,
			&i.Cgst,
			&i.Sgst,
			&i.Igst,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, tenant_id, customer_id, so_id, invoice_number, invoice_date, due_date, total_amount, status,
  place_of_supply_state, invoice_type, subtotal, cgst_total, sgst_total, igst_total, created_at
FROM invoices
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListInvoicesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	SoID               pgtype.UUID        `json:"so_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	InvoiceDate        pgtype.Date        `json:"invoice_date"`
	DueDate            pgtype.Date        `json:"due_date"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	Status             string             `json:"status"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	InvoiceType        string             `json:"invoice_type"`
	Subtotal           pgtype.Numeric     `json:"subtotal"`
	CgstTotal          pgtype.Numeric     `json:"cgst_total"`
	SgstTotal          pgtype.Numeric     `json:"sgst_total"`
	IgstTotal          pgtype.Numeric     `json:"igst_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInvoices(ctx context.Context, tenantID pgtype.UUID) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.SoID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.Status,
			&i.PlaceOfSupplyState,
			&i.InvoiceType,
			&i.Subtotal,
			&i.CgstTotal,
			&i.SgstTotal,
			&i.IgstTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, tenant_id, invoice_id, amount, payment_date, payment_method, reference_number, recorded_by, created_at
FROM payments
WHERE tenant_id = $1 AND invoice_id = $2
ORDER BY payment_date ASC, created_at ASC
`

type ListPaymentsByInvoiceParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
}

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, arg ListPaymentsByInvoiceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, arg.TenantID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Amount,
			&i.PaymentDate,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderItems = `-- name: ListSalesOrderItems :many
SELECT id, tenant_id, so_id, product_id, quantity, unit_price, total_price, created_at
FROM sales_order_items
WHERE so_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type ListSalesOrderItemsParams struct {
	SoID     pgtype.UUID `json:"so_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListSalesOrderItems(ctx context.Context, arg ListSalesOrderItemsParams) ([]SalesOrderItem, error) {
	rows, err := q.db.Query(ctx, listSalesOrderItems, arg.SoID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderItem
	for rows.Next() {
		var i SalesOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SoID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT id, tenant_id, customer_id, so_number, status, expected_shipping_date, total_amount, created_by, created_at, updated_at
FROM sales_orders
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSalesOrders(ctx context.Context, tenantID pgtype.UUID) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrder
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.SoNumber,
			&i.Status,
			&i.ExpectedShippingDate,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceNumber = `-- name: NextInvoiceNumber :one
INSERT INTO invoice_number_sequences (tenant_id, year, last_number)
VALUES ($1, $2, 1)
ON CONFLICT (tenant_id, year) DO UPDATE SET last_number = invoice_number_sequences.last_number + 1
RETURNING last_number
`

type NextInvoiceNumberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Year     int32       `json:"year"`
}

func (q *Queries) NextInvoiceNumber(ctx context.Context, arg NextInvoiceNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceNumber, arg.TenantID, arg.Year)
	var last_number int32
	err := row.Scan(&last_number)
	return last_number, err
}

const sumPaymentsByInvoice = `-- name: SumPaymentsByInvoice :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL(15,2) AS total_paid
FROM payments
WHERE tenant_id = $1 AND invoice_id = $2
`

type SumPaymentsByInvoiceParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
}

func (q *Queries) SumPaymentsByInvoice(ctx context.Context, arg SumPaymentsByInvoiceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumPaymentsByInvoice, arg.TenantID, arg.InvoiceID)
	var total_paid pgtype.Numeric
	err := row.Scan(&total_paid)
	return total_paid, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $3, contact_person = $4, email = $5, phone = $6, billing_address = $7, shipping_address = $8, tax_id = $9, gstin = $10, place_of_supply_state = $11, pan = $12, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, contact_person, email, phone, billing_address, shipping_address, tax_id, gstin, place_of_supply_state, pan, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID                 pgtype.UUID `json:"id"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	ContactPerson      pgtype.Text `json:"contact_person"`
	Email              pgtype.Text `json:"email"`
	Phone              pgtype.Text `json:"phone"`
	BillingAddress     pgtype.Text `json:"billing_address"`
	ShippingAddress    pgtype.Text `json:"shipping_address"`
	TaxID              pgtype.Text `json:"tax_id"`
	Gstin              pgtype.Text `json:"gstin"`
	PlaceOfSupplyState pgtype.Text `json:"place_of_supply_state"`
	Pan                pgtype.Text `json:"pan"`
}

type UpdateCustomerRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	BillingAddress     pgtype.Text        `json:"billing_address"`
	ShippingAddress    pgtype.Text        `json:"shipping_address"`
	TaxID              pgtype.Text        `json:"tax_id"`
	Gstin              pgtype.Text        `json:"gstin"`
	PlaceOfSupplyState pgtype.Text        `json:"place_of_supply_state"`
	Pan                pgtype.Text        `json:"pan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.Phone,
		arg.BillingAddress,
		arg.ShippingAddress,
		arg.TaxID,
		arg.Gstin,
		arg.PlaceOfSupplyState,
		arg.Pan,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Phone,
		&i.BillingAddress,
		&i.ShippingAddress,
		&i.TaxID,
		&i.Gstin,
		&i.PlaceOfSupplyState,
		&i.Pan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = $3 WHERE tenant_id = $1 AND id = $2
`

type UpdateInvoiceStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.TenantID, arg.ID, arg.Status)
	return err
}

const updateSalesOrderStatus = `-- name: UpdateSalesOrderStatus :exec
UPDATE sales_orders
SET status = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
`

type UpdateSalesOrderStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateSalesOrderStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const updateSalesOrderTotal = `-- name: UpdateSalesOrderTotal :exec
UPDATE sales_orders
SET total_amount = (SELECT COALESCE(SUM(total_price), 0) FROM sales_order_items WHERE sales_order_items.so_id = sales_orders.id), updated_at = CURRENT_TIMESTAMP
WHERE sales_orders.id = $1 AND sales_orders.tenant_id = $2
`

type UpdateSalesOrderTotalParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateSalesOrderTotal(ctx context.Context, arg UpdateSalesOrderTotalParams) error {
	_, err := q.db.Exec(ctx, updateSalesOrderTotal, arg.ID, arg.TenantID)
	return err
}
