// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduledReport = `-- name: CreateScheduledReport :one
INSERT INTO scheduled_reports (tenant_id, created_by, name, report_type, frequency, export_format, recipient_email, parameters, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, created_by, name, report_type, frequency, export_format, recipient_email, parameters, last_run_at, next_run_at, created_at, updated_at
`

type CreateScheduledReportParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	Name           string             `json:"name"`
	ReportType     string             `json:"report_type"`
	Frequency      string             `json:"frequency"`
	ExportFormat   string             `json:"export_format"`
	RecipientEmail string             `json:"recipient_email"`
	Parameters     []byte             `json:"parameters"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateScheduledReport(ctx context.Context, arg CreateScheduledReportParams) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, createScheduledReport,
		arg.TenantID,
		arg.CreatedBy,
		arg.Name,
		arg.ReportType,
		arg.Frequency,
		arg.ExportFormat,
		arg.RecipientEmail,
		arg.Parameters,
		arg.NextRunAt,
	)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.ReportType,
		&i.Frequency,
		&i.ExportFormat,
		&i.RecipientEmail,
		&i.Parameters,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduledReport = `-- name: DeleteScheduledReport :exec
DELETE FROM scheduled_reports WHERE id = $1 AND tenant_id = $2
`

type DeleteScheduledReportParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteScheduledReport(ctx context.Context, arg DeleteScheduledReportParams) error {
	_, err := q.db.Exec(ctx, deleteScheduledReport, arg.ID, arg.TenantID)
	return err
}

const getScheduledReport = `-- name: GetScheduledReport :one
SELECT id, tenant_id, created_by, name, report_type, frequency, export_format, recipient_email, parameters, last_run_at, next_run_at, created_at, updated_at FROM scheduled_reports
WHERE id = $1 AND tenant_id = $2
`

type GetScheduledReportParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetScheduledReport(ctx context.Context, arg GetScheduledReportParams) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, getScheduledReport, arg.ID, arg.TenantID)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.ReportType,
		&i.Frequency,
		&i.ExportFormat,
		&i.RecipientEmail,
		&i.Parameters,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduledReports = `-- name: ListScheduledReports :many
SELECT id, tenant_id, created_by, name, report_type, frequency, export_format, recipient_email, parameters, last_run_at, next_run_at, created_at, updated_at FROM scheduled_reports
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScheduledReports(ctx context.Context, tenantID pgtype.UUID) ([]ScheduledReport, error) {
	rows, err := q.db.Query(ctx, listScheduledReports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledReport
	for rows.Next() {
		var i ScheduledReport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedBy,
			&i.Name,
			&i.ReportType,
			&i.Frequency,
			&i.ExportFormat,
			&i.RecipientEmail,
			&i.Parameters,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledReportNextRun = `-- name: UpdateScheduledReportNextRun :exec
UPDATE scheduled_reports
SET last_run_at = $3, next_run_at = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
`

type UpdateScheduledReportNextRunParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateScheduledReportNextRun(ctx context.Context, arg UpdateScheduledReportNextRunParams) error {
	_, err := q.db.Exec(ctx, updateScheduledReportNextRun,
		arg.ID,
		arg.TenantID,
		arg.LastRunAt,
		arg.NextRunAt,
	)
	return err
}
