// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (tenant_id, shipment_number, sales_order_id, warehouse_id, carrier_name, tracking_number, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, shipment_number, sales_order_id, warehouse_id, carrier_name, tracking_number, status, shipped_at, delivered_at, created_by, created_at
`

type CreateShipmentParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ShipmentNumber string      `json:"shipment_number"`
	SalesOrderID   pgtype.UUID `json:"sales_order_id"`
	WarehouseID    pgtype.UUID `json:"warehouse_id"`
	CarrierName    pgtype.Text `json:"carrier_name"`
	TrackingNumber pgtype.Text `json:"tracking_number"`
	Status         string      `json:"status"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.TenantID,
		arg.ShipmentNumber,
		arg.SalesOrderID,
		arg.WarehouseID,
		arg.CarrierName,
		arg.TrackingNumber,
		arg.Status,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.WarehouseID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createShipmentLine = `-- name: CreateShipmentLine :one
INSERT INTO shipment_lines (shipment_id, product_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, shipment_id, product_id, quantity, created_at
`

type CreateShipmentLineParams struct {
	ShipmentID pgtype.UUID    `json:"shipment_id"`
	ProductID  pgtype.UUID    `json:"product_id"`
	Quantity   pgtype.Numeric `json:"quantity"`
}

func (q *Queries) CreateShipmentLine(ctx context.Context, arg CreateShipmentLineParams) (ShipmentLine, error) {
	row := q.db.QueryRow(ctx, createShipmentLine, arg.ShipmentID, arg.ProductID, arg.Quantity)
	var i ShipmentLine
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, tenant_id, shipment_number, sales_order_id, warehouse_id, carrier_name, tracking_number, status, shipped_at, delivered_at, created_by, created_at
FROM shipments
WHERE id = $1 AND tenant_id = $2
`

type GetShipmentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetShipment(ctx context.Context, arg GetShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipment, arg.ID, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.WarehouseID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listShipmentLines = `-- name: ListShipmentLines :many
SELECT id, shipment_id, product_id, quantity, created_at
FROM shipment_lines
WHERE shipment_id = $1
ORDER BY id ASC
`

func (q *Queries) ListShipmentLines(ctx context.Context, shipmentID pgtype.UUID) ([]ShipmentLine, error) {
	rows, err := q.db.Query(ctx, listShipmentLines, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentLine
	for rows.Next() {
		var i ShipmentLine
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT id, tenant_id, shipment_number, sales_order_id, warehouse_id, carrier_name, tracking_number, status, shipped_at, delivered_at, created_by, created_at
FROM shipments
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListShipmentsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipments, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentNumber,
			&i.SalesOrderID,
			&i.WarehouseID,
			&i.CarrierName,
			&i.TrackingNumber,
			&i.Status,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :one
UPDATE shipments
SET status = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, shipment_number, sales_order_id, warehouse_id, carrier_name, tracking_number, status, shipped_at, delivered_at, created_by, created_at
`

type UpdateShipmentStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipmentStatus, arg.ID, arg.TenantID, arg.Status)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.WarehouseID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
