// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomField = `-- name: CreateCustomField :one
INSERT INTO custom_fields (tenant_id, entity_type, field_name, field_type, sort_order, required, default_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, entity_type, field_name, field_type, sort_order, required, default_value, created_at
`

type CreateCustomFieldParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	EntityType   string      `json:"entity_type"`
	FieldName    string      `json:"field_name"`
	FieldType    string      `json:"field_type"`
	SortOrder    int32       `json:"sort_order"`
	Required     bool        `json:"required"`
	DefaultValue pgtype.Text `json:"default_value"`
}

func (q *Queries) CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRow(ctx, createCustomField,
		arg.TenantID,
		arg.EntityType,
		arg.FieldName,
		arg.FieldType,
		arg.SortOrder,
		arg.Required,
		arg.DefaultValue,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.FieldName,
		&i.FieldType,
		&i.SortOrder,
		&i.Required,
		&i.DefaultValue,
		&i.CreatedAt,
	)
	return i, err
}

const createTaxRule = `-- name: CreateTaxRule :one
INSERT INTO tax_rules (tenant_id, name, rate, type, applicable_to, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, rate, type, applicable_to, is_default, created_at
`

type CreateTaxRuleParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	Name         string         `json:"name"`
	Rate         pgtype.Numeric `json:"rate"`
	Type         string         `json:"type"`
	ApplicableTo string         `json:"applicable_to"`
	IsDefault    bool           `json:"is_default"`
}

func (q *Queries) CreateTaxRule(ctx context.Context, arg CreateTaxRuleParams) (TaxRule, error) {
	row := q.db.QueryRow(ctx, createTaxRule,
		arg.TenantID,
		arg.Name,
		arg.Rate,
		arg.Type,
		arg.ApplicableTo,
		arg.IsDefault,
	)
	var i TaxRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Rate,
		&i.Type,
		&i.ApplicableTo,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentNumberSeries = `-- name: GetDocumentNumberSeries :one
SELECT tenant_id, document_type, year, last_number, prefix
FROM document_number_series
WHERE tenant_id = $1 AND document_type = $2 AND year = $3 LIMIT 1
`

type GetDocumentNumberSeriesParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	DocumentType string      `json:"document_type"`
	Year         int32       `json:"year"`
}

func (q *Queries) GetDocumentNumberSeries(ctx context.Context, arg GetDocumentNumberSeriesParams) (DocumentNumberSeries, error) {
	row := q.db.QueryRow(ctx, getDocumentNumberSeries, arg.TenantID, arg.DocumentType, arg.Year)
	var i DocumentNumberSeries
	err := row.Scan(
		&i.TenantID,
		&i.DocumentType,
		&i.Year,
		&i.LastNumber,
		&i.Prefix,
	)
	return i, err
}

const getNextDocumentNumber = `-- name: GetNextDocumentNumber :one
INSERT INTO document_number_series (tenant_id, document_type, year, last_number, prefix)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (tenant_id, document_type, year) DO UPDATE SET last_number = document_number_series.last_number + 1
RETURNING last_number, prefix
`

type GetNextDocumentNumberParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	DocumentType string      `json:"document_type"`
	Year         int32       `json:"year"`
	Prefix       string      `json:"prefix"`
}

type GetNextDocumentNumberRow struct {
	LastNumber int32  `json:"last_number"`
	Prefix     string `json:"prefix"`
}

func (q *Queries) GetNextDocumentNumber(ctx context.Context, arg GetNextDocumentNumberParams) (GetNextDocumentNumberRow, error) {
	row := q.db.QueryRow(ctx, getNextDocumentNumber,
		arg.TenantID,
		arg.DocumentType,
		arg.Year,
		arg.Prefix,
	)
	var i GetNextDocumentNumberRow
	err := row.Scan(&i.LastNumber, &i.Prefix)
	return i, err
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, display_name, fiscal_year_start_month, base_currency, locale, timezone, feature_flags, created_at, updated_at
FROM tenant_settings
WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID pgtype.UUID) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.DisplayName,
		&i.FiscalYearStartMonth,
		&i.BaseCurrency,
		&i.Locale,
		&i.Timezone,
		&i.FeatureFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomFields = `-- name: ListCustomFields :many
SELECT id, tenant_id, entity_type, field_name, field_type, sort_order, required, default_value, created_at
FROM custom_fields
WHERE tenant_id = $1 AND entity_type = $2
ORDER BY sort_order ASC, field_name ASC
`

type ListCustomFieldsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) ListCustomFields(ctx context.Context, arg ListCustomFieldsParams) ([]CustomField, error) {
	rows, err := q.db.Query(ctx, listCustomFields, arg.TenantID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.FieldName,
			&i.FieldType,
			&i.SortOrder,
			&i.Required,
			&i.DefaultValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxRules = `-- name: ListTaxRules :many
SELECT id, tenant_id, name, rate, type, applicable_to, is_default, created_at
FROM tax_rules
WHERE tenant_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTaxRules(ctx context.Context, tenantID pgtype.UUID) ([]TaxRule, error) {
	rows, err := q.db.Query(ctx, listTaxRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRule
	for rows.Next() {
		var i TaxRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Rate,
			&i.Type,
			&i.ApplicableTo,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocumentNumberSeries = `-- name: UpsertDocumentNumberSeries :one
INSERT INTO document_number_series (tenant_id, document_type, year, last_number, prefix)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, document_type, year) DO UPDATE SET
  last_number = GREATEST(document_number_series.last_number, EXCLUDED.last_number),
  prefix = EXCLUDED.prefix
RETURNING tenant_id, document_type, year, last_number, prefix
`

type UpsertDocumentNumberSeriesParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	DocumentType string      `json:"document_type"`
	Year         int32       `json:"year"`
	LastNumber   int32       `json:"last_number"`
	Prefix       string      `json:"prefix"`
}

func (q *Queries) UpsertDocumentNumberSeries(ctx context.Context, arg UpsertDocumentNumberSeriesParams) (DocumentNumberSeries, error) {
	row := q.db.QueryRow(ctx, upsertDocumentNumberSeries,
		arg.TenantID,
		arg.DocumentType,
		arg.Year,
		arg.LastNumber,
		arg.Prefix,
	)
	var i DocumentNumberSeries
	err := row.Scan(
		&i.TenantID,
		&i.DocumentType,
		&i.Year,
		&i.LastNumber,
		&i.Prefix,
	)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (tenant_id, display_name, fiscal_year_start_month, base_currency, locale, timezone, feature_flags, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP)
ON CONFLICT (tenant_id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  fiscal_year_start_month = EXCLUDED.fiscal_year_start_month,
  base_currency = EXCLUDED.base_currency,
  locale = EXCLUDED.locale,
  timezone = EXCLUDED.timezone,
  feature_flags = EXCLUDED.feature_flags,
  updated_at = CURRENT_TIMESTAMP
RETURNING tenant_id, display_name, fiscal_year_start_month, base_currency, locale, timezone, feature_flags, created_at, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	DisplayName          string      `json:"display_name"`
	FiscalYearStartMonth int32       `json:"fiscal_year_start_month"`
	BaseCurrency         string      `json:"base_currency"`
	Locale               string      `json:"locale"`
	Timezone             string      `json:"timezone"`
	FeatureFlags         []byte      `json:"feature_flags"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings,
		arg.TenantID,
		arg.DisplayName,
		arg.FiscalYearStartMonth,
		arg.BaseCurrency,
		arg.Locale,
		arg.Timezone,
		arg.FeatureFlags,
	)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.DisplayName,
		&i.FiscalYearStartMonth,
		&i.BaseCurrency,
		&i.Locale,
		&i.Timezone,
		&i.FeatureFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
