// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouse_hierarchy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWarehouseBin = `-- name: CreateWarehouseBin :one
INSERT INTO warehouse_bins (shelf_id, code)
VALUES ($1, $2)
RETURNING id, shelf_id, code, created_at
`

type CreateWarehouseBinParams struct {
	ShelfID pgtype.UUID `json:"shelf_id"`
	Code    string      `json:"code"`
}

func (q *Queries) CreateWarehouseBin(ctx context.Context, arg CreateWarehouseBinParams) (WarehouseBin, error) {
	row := q.db.QueryRow(ctx, createWarehouseBin, arg.ShelfID, arg.Code)
	var i WarehouseBin
	err := row.Scan(
		&i.ID,
		&i.ShelfID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const createWarehouseRack = `-- name: CreateWarehouseRack :one
INSERT INTO warehouse_racks (zone_id, code)
VALUES ($1, $2)
RETURNING id, zone_id, code, created_at
`

type CreateWarehouseRackParams struct {
	ZoneID pgtype.UUID `json:"zone_id"`
	Code   string      `json:"code"`
}

func (q *Queries) CreateWarehouseRack(ctx context.Context, arg CreateWarehouseRackParams) (WarehouseRack, error) {
	row := q.db.QueryRow(ctx, createWarehouseRack, arg.ZoneID, arg.Code)
	var i WarehouseRack
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const createWarehouseShelf = `-- name: CreateWarehouseShelf :one
INSERT INTO warehouse_shelves (rack_id, code)
VALUES ($1, $2)
RETURNING id, rack_id, code, created_at
`

type CreateWarehouseShelfParams struct {
	RackID pgtype.UUID `json:"rack_id"`
	Code   string      `json:"code"`
}

func (q *Queries) CreateWarehouseShelf(ctx context.Context, arg CreateWarehouseShelfParams) (WarehouseShelf, error) {
	row := q.db.QueryRow(ctx, createWarehouseShelf, arg.RackID, arg.Code)
	var i WarehouseShelf
	err := row.Scan(
		&i.ID,
		&i.RackID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const createWarehouseZone = `-- name: CreateWarehouseZone :one
INSERT INTO warehouse_zones (tenant_id, warehouse_id, code, name)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, warehouse_id, code, name, created_at
`

type CreateWarehouseZoneParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
	Code        string      `json:"code"`
	Name        pgtype.Text `json:"name"`
}

func (q *Queries) CreateWarehouseZone(ctx context.Context, arg CreateWarehouseZoneParams) (WarehouseZone, error) {
	row := q.db.QueryRow(ctx, createWarehouseZone,
		arg.TenantID,
		arg.WarehouseID,
		arg.Code,
		arg.Name,
	)
	var i WarehouseZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getWarehouseZone = `-- name: GetWarehouseZone :one
SELECT id, tenant_id, warehouse_id, code, name, created_at
FROM warehouse_zones
WHERE id = $1 AND tenant_id = $2
`

type GetWarehouseZoneParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetWarehouseZone(ctx context.Context, arg GetWarehouseZoneParams) (WarehouseZone, error) {
	row := q.db.QueryRow(ctx, getWarehouseZone, arg.ID, arg.TenantID)
	var i WarehouseZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listWarehouseBins = `-- name: ListWarehouseBins :many
SELECT id, shelf_id, code, created_at
FROM warehouse_bins
WHERE shelf_id = $1
ORDER BY code ASC
`

func (q *Queries) ListWarehouseBins(ctx context.Context, shelfID pgtype.UUID) ([]WarehouseBin, error) {
	rows, err := q.db.Query(ctx, listWarehouseBins, shelfID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseBin
	for rows.Next() {
		var i WarehouseBin
		if err := rows.Scan(
			&i.ID,
			&i.ShelfID,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseRacks = `-- name: ListWarehouseRacks :many
SELECT id, zone_id, code, created_at
FROM warehouse_racks
WHERE zone_id = $1
ORDER BY code ASC
`

func (q *Queries) ListWarehouseRacks(ctx context.Context, zoneID pgtype.UUID) ([]WarehouseRack, error) {
	rows, err := q.db.Query(ctx, listWarehouseRacks, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseRack
	for rows.Next() {
		var i WarehouseRack
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseShelves = `-- name: ListWarehouseShelves :many
SELECT id, rack_id, code, created_at
FROM warehouse_shelves
WHERE rack_id = $1
ORDER BY code ASC
`

func (q *Queries) ListWarehouseShelves(ctx context.Context, rackID pgtype.UUID) ([]WarehouseShelf, error) {
	rows, err := q.db.Query(ctx, listWarehouseShelves, rackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseShelf
	for rows.Next() {
		var i WarehouseShelf
		if err := rows.Scan(
			&i.ID,
			&i.RackID,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseZones = `-- name: ListWarehouseZones :many
SELECT id, tenant_id, warehouse_id, code, name, created_at
FROM warehouse_zones
WHERE tenant_id = $1 AND warehouse_id = $2
ORDER BY code ASC
`

type ListWarehouseZonesParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
}

func (q *Queries) ListWarehouseZones(ctx context.Context, arg ListWarehouseZonesParams) ([]WarehouseZone, error) {
	rows, err := q.db.Query(ctx, listWarehouseZones, arg.TenantID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseZone
	for rows.Next() {
		var i WarehouseZone
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WarehouseID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
