// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name FROM roles WHERE code = $1 LIMIT 1
`

type GetRoleByCodeRow struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
	Name string      `json:"name"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i GetRoleByCodeRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getUserWithRoleByEmail = `-- name: GetUserWithRoleByEmail :one
SELECT 
    u.id, 
    u.email, 
    u.password_hash, 
    u.name, 
    u.is_active,
    r.code as role_code
FROM users u 
JOIN roles r ON u.role_id = r.id 
WHERE u.email = $1 LIMIT 1
`

type GetUserWithRoleByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	IsActive     bool        `json:"is_active"`
	RoleCode     string      `json:"role_code"`
}

func (q *Queries) GetUserWithRoleByEmail(ctx context.Context, email string) (GetUserWithRoleByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRoleByEmail, email)
	var i GetUserWithRoleByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.RoleCode,
	)
	return i, err
}

const getUserWithRoleByID = `-- name: GetUserWithRoleByID :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.name,
    u.is_active,
    r.code as role_code
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
LIMIT 1
`

type GetUserWithRoleByIDRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	IsActive     bool        `json:"is_active"`
	RoleCode     string      `json:"role_code"`
}

func (q *Queries) GetUserWithRoleByID(ctx context.Context, id pgtype.UUID) (GetUserWithRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRoleByID, id)
	var i GetUserWithRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.RoleCode,
	)
	return i, err
}
