// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, display_name, normalized_name, phone_number, normalized_phone, whatsapp_number, normalized_whatsapp, email, gst_number, normalized_gst, company_name, notes, is_active, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.NormalizedName,
		&i.PhoneNumber,
		&i.NormalizedPhone,
		&i.WhatsappNumber,
		&i.NormalizedWhatsapp,
		&i.Email,
		&i.GstNumber,
		&i.NormalizedGst,
		&i.CompanyName,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByNormalizedGST = `-- name: GetCustomerByNormalizedGST :one
SELECT id, display_name, normalized_name, phone_number, normalized_phone, whatsapp_number, normalized_whatsapp, email, gst_number, normalized_gst, company_name, notes, is_active, created_at, updated_at
FROM customers
WHERE normalized_gst = $1
LIMIT 1
`

func (q *Queries) GetCustomerByNormalizedGST(ctx context.Context, normalizedGst pgtype.Text) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByNormalizedGST, normalizedGst)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.NormalizedName,
		&i.PhoneNumber,
		&i.NormalizedPhone,
		&i.WhatsappNumber,
		&i.NormalizedWhatsapp,
		&i.Email,
		&i.GstNumber,
		&i.NormalizedGst,
		&i.CompanyName,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByNormalizedPhone = `-- name: GetCustomerByNormalizedPhone :one
SELECT id, display_name, normalized_name, phone_number, normalized_phone, whatsapp_number, normalized_whatsapp, email, gst_number, normalized_gst, company_name, notes, is_active, created_at, updated_at
FROM customers
WHERE normalized_phone = $1
LIMIT 1
`

func (q *Queries) GetCustomerByNormalizedPhone(ctx context.Context, normalizedPhone pgtype.Text) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByNormalizedPhone, normalizedPhone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.NormalizedName,
		&i.PhoneNumber,
		&i.NormalizedPhone,
		&i.WhatsappNumber,
		&i.NormalizedWhatsapp,
		&i.Email,
		&i.GstNumber,
		&i.NormalizedGst,
		&i.CompanyName,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByNormalizedWhatsApp = `-- name: GetCustomerByNormalizedWhatsApp :one
SELECT id, display_name, normalized_name, phone_number, normalized_phone, whatsapp_number, normalized_whatsapp, email, gst_number, normalized_gst, company_name, notes, is_active, created_at, updated_at
FROM customers
WHERE normalized_whatsapp = $1
LIMIT 1
`

func (q *Queries) GetCustomerByNormalizedWhatsApp(ctx context.Context, normalizedWhatsapp pgtype.Text) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByNormalizedWhatsApp, normalizedWhatsapp)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.NormalizedName,
		&i.PhoneNumber,
		&i.NormalizedPhone,
		&i.WhatsappNumber,
		&i.NormalizedWhatsapp,
		&i.Email,
		&i.GstNumber,
		&i.NormalizedGst,
		&i.CompanyName,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customers (
    display_name,
    normalized_name,
    phone_number,
    normalized_phone,
    whatsapp_number,
    normalized_whatsapp,
    email,
    gst_number,
    normalized_gst,
    company_name,
    notes,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, TRUE
)
RETURNING id, display_name, normalized_name, phone_number, normalized_phone, whatsapp_number, normalized_whatsapp, email, gst_number, normalized_gst, company_name, notes, is_active, created_at, updated_at
`

type InsertCustomerParams struct {
	DisplayName        string      `json:"display_name"`
	NormalizedName     string      `json:"normalized_name"`
	PhoneNumber        pgtype.Text `json:"phone_number"`
	NormalizedPhone    pgtype.Text `json:"normalized_phone"`
	WhatsappNumber     pgtype.Text `json:"whatsapp_number"`
	NormalizedWhatsapp pgtype.Text `json:"normalized_whatsapp"`
	Email              pgtype.Text `json:"email"`
	GstNumber          pgtype.Text `json:"gst_number"`
	NormalizedGst      pgtype.Text `json:"normalized_gst"`
	CompanyName        pgtype.Text `json:"company_name"`
	Notes              pgtype.Text `json:"notes"`
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.DisplayName,
		arg.NormalizedName,
		arg.PhoneNumber,
		arg.NormalizedPhone,
		arg.WhatsappNumber,
		arg.NormalizedWhatsapp,
		arg.Email,
		arg.GstNumber,
		arg.NormalizedGst,
		arg.CompanyName,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.NormalizedName,
		&i.PhoneNumber,
		&i.NormalizedPhone,
		&i.WhatsappNumber,
		&i.NormalizedWhatsapp,
		&i.Email,
		&i.GstNumber,
		&i.NormalizedGst,
		&i.CompanyName,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerAlias = `-- name: InsertCustomerAlias :exec
INSERT INTO customer_aliases (
    customer_id,
    alias,
    normalized_alias
) VALUES (
    $1, $2, $3
)
ON CONFLICT (customer_id, normalized_alias) DO NOTHING
`

type InsertCustomerAliasParams struct {
	CustomerID      pgtype.UUID `json:"customer_id"`
	Alias           string      `json:"alias"`
	NormalizedAlias string      `json:"normalized_alias"`
}

func (q *Queries) InsertCustomerAlias(ctx context.Context, arg InsertCustomerAliasParams) error {
	_, err := q.db.Exec(ctx, insertCustomerAlias, arg.CustomerID, arg.Alias, arg.NormalizedAlias)
	return err
}

const listCustomerFuzzyCandidates = `-- name: ListCustomerFuzzyCandidates :many
SELECT
    c.id, c.display_name, c.normalized_name, c.phone_number, c.normalized_phone, c.whatsapp_number, c.normalized_whatsapp, c.email, c.gst_number, c.normalized_gst, c.company_name, c.notes, c.is_active, c.created_at, c.updated_at,
    COALESCE(alias_match.alias, '') AS matched_alias,
    COALESCE(alias_match.normalized_alias, '') AS matched_normalized_alias
FROM customers c
LEFT JOIN LATERAL (
    SELECT
        a.customer_id,
        a.alias,
        a.normalized_alias
    FROM customer_aliases a
    WHERE a.customer_id = c.id
      AND $1::text <> ''
      AND a.normalized_alias LIKE '%' || $1::text || '%'
    ORDER BY a.created_at ASC, a.id ASC
    LIMIT 1
) alias_match ON TRUE
WHERE c.is_active = TRUE
  AND $1::text <> ''
  AND (
      c.normalized_name LIKE '%' || $1::text || '%'
      OR (c.company_name IS NOT NULL AND LOWER(c.company_name) LIKE '%' || $2::text || '%')
      OR alias_match.customer_id IS NOT NULL
  )
ORDER BY c.created_at ASC, c.id ASC
LIMIT $3
`

type ListCustomerFuzzyCandidatesParams struct {
	NormalizedQuery string `json:"normalized_query"`
	LowerQuery      string `json:"lower_query"`
	PageLimit       int32  `json:"page_limit"`
}

type ListCustomerFuzzyCandidatesRow struct {
	Customer               Customer `json:"customer"`
	MatchedAlias           string   `json:"matched_alias"`
	MatchedNormalizedAlias string   `json:"matched_normalized_alias"`
}

func (q *Queries) ListCustomerFuzzyCandidates(ctx context.Context, arg ListCustomerFuzzyCandidatesParams) ([]ListCustomerFuzzyCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerFuzzyCandidates, arg.NormalizedQuery, arg.LowerQuery, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerFuzzyCandidatesRow
	for rows.Next() {
		var i ListCustomerFuzzyCandidatesRow
		if err := rows.Scan(
			&i.Customer.ID,
			&i.Customer.DisplayName,
			&i.Customer.NormalizedName,
			&i.Customer.PhoneNumber,
			&i.Customer.NormalizedPhone,
			&i.Customer.WhatsappNumber,
			&i.Customer.NormalizedWhatsapp,
			&i.Customer.Email,
			&i.Customer.GstNumber,
			&i.Customer.NormalizedGst,
			&i.Customer.CompanyName,
			&i.Customer.Notes,
			&i.Customer.IsActive,
			&i.Customer.CreatedAt,
			&i.Customer.UpdatedAt,
			&i.MatchedAlias,
			&i.MatchedNormalizedAlias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSearchCandidates = `-- name: ListCustomerSearchCandidates :many
SELECT
    c.id, c.display_name, c.normalized_name, c.phone_number, c.normalized_phone, c.whatsapp_number, c.normalized_whatsapp, c.email, c.gst_number, c.normalized_gst, c.company_name, c.notes, c.is_active, c.created_at, c.updated_at,
    COALESCE(alias_match.alias, '') AS matched_alias,
    COALESCE(alias_match.normalized_alias, '') AS matched_normalized_alias,
    CASE
        WHEN c.normalized_name = $1::text THEN 1
        WHEN alias_match.normalized_alias = $1::text THEN 2
        WHEN LOWER(COALESCE(c.company_name, '')) = $2::text THEN 3
        WHEN c.normalized_name LIKE $1::text || '%' THEN 4
        WHEN alias_match.customer_id IS NOT NULL THEN 5
        WHEN LOWER(COALESCE(c.company_name, '')) LIKE $2::text || '%' THEN 6
        ELSE 7
    END AS match_rank
FROM customers c
LEFT JOIN LATERAL (
    SELECT
        a.customer_id,
        a.alias,
        a.normalized_alias
    FROM customer_aliases a
    WHERE a.customer_id = c.id
      AND $1::text <> ''
      AND (
          a.normalized_alias = $1::text
          OR a.normalized_alias LIKE $1::text || '%'
      )
    ORDER BY
        CASE
            WHEN a.normalized_alias = $1::text THEN 0
            ELSE 1
        END,
        a.created_at ASC,
        a.id ASC
    LIMIT 1
) alias_match ON TRUE
WHERE c.is_active = TRUE
  AND $1::text <> ''
  AND (
      c.normalized_name = $1::text
      OR c.normalized_name LIKE $1::text || '%'
      OR (c.company_name IS NOT NULL AND LOWER(c.company_name) = $2::text)
      OR (c.company_name IS NOT NULL AND LOWER(c.company_name) LIKE $2::text || '%')
      OR alias_match.customer_id IS NOT NULL
  )
ORDER BY match_rank ASC, c.normalized_name ASC, c.id ASC
LIMIT $3
`

type ListCustomerSearchCandidatesParams struct {
	NormalizedQuery string `json:"normalized_query"`
	LowerQuery      string `json:"lower_query"`
	PageLimit       int32  `json:"page_limit"`
}

type ListCustomerSearchCandidatesRow struct {
	Customer               Customer `json:"customer"`
	MatchedAlias           string   `json:"matched_alias"`
	MatchedNormalizedAlias string   `json:"matched_normalized_alias"`
	MatchRank              int32    `json:"match_rank"`
}

func (q *Queries) ListCustomerSearchCandidates(ctx context.Context, arg ListCustomerSearchCandidatesParams) ([]ListCustomerSearchCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSearchCandidates, arg.NormalizedQuery, arg.LowerQuery, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSearchCandidatesRow
	for rows.Next() {
		var i ListCustomerSearchCandidatesRow
		if err := rows.Scan(
			&i.Customer.ID,
			&i.Customer.DisplayName,
			&i.Customer.NormalizedName,
			&i.Customer.PhoneNumber,
			&i.Customer.NormalizedPhone,
			&i.Customer.WhatsappNumber,
			&i.Customer.NormalizedWhatsapp,
			&i.Customer.Email,
			&i.Customer.GstNumber,
			&i.Customer.NormalizedGst,
			&i.Customer.CompanyName,
			&i.Customer.Notes,
			&i.Customer.IsActive,
			&i.Customer.CreatedAt,
			&i.Customer.UpdatedAt,
			&i.MatchedAlias,
			&i.MatchedNormalizedAlias,
			&i.MatchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByNormalizedAlias = `-- name: ListCustomersByNormalizedAlias :many
SELECT c.id, c.display_name, c.normalized_name, c.phone_number, c.normalized_phone, c.whatsapp_number, c.normalized_whatsapp, c.email, c.gst_number, c.normalized_gst, c.company_name, c.notes, c.is_active, c.created_at, c.updated_at
FROM customer_aliases a
JOIN customers c ON c.id = a.customer_id
WHERE a.normalized_alias = $1
ORDER BY c.created_at ASC, c.id ASC
`

func (q *Queries) ListCustomersByNormalizedAlias(ctx context.Context, normalizedAlias string) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByNormalizedAlias, normalizedAlias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.NormalizedName,
			&i.PhoneNumber,
			&i.NormalizedPhone,
			&i.WhatsappNumber,
			&i.NormalizedWhatsapp,
			&i.Email,
			&i.GstNumber,
			&i.NormalizedGst,
			&i.CompanyName,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
