// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementBatchReservedQty = `-- name: DecrementBatchReservedQty :one
UPDATE inventory_batches
SET
    reserved_qty = reserved_qty - $1,
    updated_at = NOW()
WHERE id = $2
  AND type = 'FINISHED'::batch_type
  AND $1 > 0
  AND reserved_qty >= $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type DecrementBatchReservedQtyParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) DecrementBatchReservedQty(ctx context.Context, arg DecrementBatchReservedQtyParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, decrementBatchReservedQty, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const deductBatchRemainingQty = `-- name: DeductBatchRemainingQty :one
UPDATE inventory_batches
SET
    remaining_qty = remaining_qty - $1,
    status = CASE
        WHEN remaining_qty - $1 <= 0 THEN 'EXHAUSTED'::batch_status
        ELSE status
    END,
    updated_at = NOW()
WHERE id = $2
  AND type = 'FINISHED'::batch_type
  AND status = 'ACTIVE'::batch_status
  AND $1 > 0
  AND remaining_qty >= $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type DeductBatchRemainingQtyParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) DeductBatchRemainingQty(ctx context.Context, arg DeductBatchRemainingQtyParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, deductBatchRemainingQty, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const getReservableFinishedBatchesForUpdate = `-- name: GetReservableFinishedBatchesForUpdate :many
SELECT
    b.id,
    b.item_id,
    b.batch_code,
    b.initial_qty,
    b.remaining_qty,
    b.reserved_qty,
    b.status,
    b.created_at,
    b.updated_at
FROM inventory_batches b
WHERE b.item_id = $1
  AND b.type = 'FINISHED'::batch_type
  AND b.status = 'ACTIVE'::batch_status
  AND b.remaining_qty > b.reserved_qty
ORDER BY b.created_at ASC, b.id ASC
FOR UPDATE
`

type GetReservableFinishedBatchesForUpdateRow struct {
	ID           pgtype.UUID        `json:"id"`
	ItemID       pgtype.UUID        `json:"item_id"`
	BatchCode    string             `json:"batch_code"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	ReservedQty  pgtype.Numeric     `json:"reserved_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetReservableFinishedBatchesForUpdate(ctx context.Context, itemID pgtype.UUID) ([]GetReservableFinishedBatchesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getReservableFinishedBatchesForUpdate, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservableFinishedBatchesForUpdateRow
	for rows.Next() {
		var i GetReservableFinishedBatchesForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.BatchCode,
			&i.InitialQty,
			&i.RemainingQty,
			&i.ReservedQty,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBatchReservedQty = `-- name: IncrementBatchReservedQty :one
UPDATE inventory_batches
SET
    reserved_qty = reserved_qty + $1,
    updated_at = NOW()
WHERE id = $2
  AND type = 'FINISHED'::batch_type
  AND status = 'ACTIVE'::batch_status
  AND $1 > 0
  AND reserved_qty + $1 <= remaining_qty
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type IncrementBatchReservedQtyParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) IncrementBatchReservedQty(ctx context.Context, arg IncrementBatchReservedQtyParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, incrementBatchReservedQty, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}
