// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO inventory_batches (
    item_id, batch_code, daily_sequence, initial_qty, remaining_qty, status
) VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE'
)
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type CreateBatchParams struct {
	ItemID        pgtype.UUID    `json:"item_id"`
	BatchCode     string         `json:"batch_code"`
	DailySequence int32          `json:"daily_sequence"`
	InitialQty    pgtype.Numeric `json:"initial_qty"`
	RemainingQty  pgtype.Numeric `json:"remaining_qty"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ItemID,
		arg.BatchCode,
		arg.DailySequence,
		arg.InitialQty,
		arg.RemainingQty,
	)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const createDerivedBatch = `-- name: CreateDerivedBatch :one
INSERT INTO inventory_batches (
    item_id,
    batch_code,
    daily_sequence,
    initial_qty,
    remaining_qty,
    reserved_qty,
    status,
    type,
    diameter,
    parent_batch_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type CreateDerivedBatchParams struct {
	ItemID        pgtype.UUID    `json:"item_id"`
	BatchCode     string         `json:"batch_code"`
	DailySequence int32          `json:"daily_sequence"`
	InitialQty    pgtype.Numeric `json:"initial_qty"`
	RemainingQty  pgtype.Numeric `json:"remaining_qty"`
	ReservedQty   pgtype.Numeric `json:"reserved_qty"`
	Status        BatchStatus    `json:"status"`
	Type          BatchType      `json:"type"`
	Diameter      pgtype.Numeric `json:"diameter"`
	ParentBatchID pgtype.UUID    `json:"parent_batch_id"`
}

func (q *Queries) CreateDerivedBatch(ctx context.Context, arg CreateDerivedBatchParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, createDerivedBatch,
		arg.ItemID,
		arg.BatchCode,
		arg.DailySequence,
		arg.InitialQty,
		arg.RemainingQty,
		arg.ReservedQty,
		arg.Status,
		arg.Type,
		arg.Diameter,
		arg.ParentBatchID,
	)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const exhaustBatchByID = `-- name: ExhaustBatchByID :one
UPDATE inventory_batches
SET remaining_qty = 0,
        status = 'EXHAUSTED',
        updated_at = NOW()
WHERE id = $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

func (q *Queries) ExhaustBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, exhaustBatchByID, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const finalizeBatchReservation = `-- name: FinalizeBatchReservation :one
UPDATE inventory_batches
SET remaining_qty = remaining_qty - $1,
    reserved_qty = reserved_qty - $1,
    updated_at = NOW(),
    status = CASE
                WHEN remaining_qty - $1 <= 0 THEN 'EXHAUSTED'::batch_status
        ELSE status
    END
WHERE id = $2
    AND $1 > 0
    AND remaining_qty >= $1
    AND reserved_qty >= $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type FinalizeBatchReservationParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) FinalizeBatchReservation(ctx context.Context, arg FinalizeBatchReservationParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, finalizeBatchReservation, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const getActiveBatchesByItem = `-- name: GetActiveBatchesByItem :many
SELECT
    b.id,
    b.batch_code,
    COALESCE(i.sku, '') AS sku,
    b.initial_qty,
    GREATEST(b.remaining_qty - b.reserved_qty, 0)::numeric AS remaining_qty,
    b.status,
    b.created_at
FROM inventory_batches b
JOIN items i ON i.id = b.item_id
WHERE b.item_id = $1
    AND b.remaining_qty > b.reserved_qty
    AND b.status = 'ACTIVE'::batch_status
ORDER BY b.created_at ASC
`

type GetActiveBatchesByItemRow struct {
	ID           pgtype.UUID        `json:"id"`
	BatchCode    string             `json:"batch_code"`
	Sku          string             `json:"sku"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveBatchesByItem(ctx context.Context, itemID pgtype.UUID) ([]GetActiveBatchesByItemRow, error) {
	rows, err := q.db.Query(ctx, getActiveBatchesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBatchesByItemRow
	for rows.Next() {
		var i GetActiveBatchesByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.Sku,
			&i.InitialQty,
			&i.RemainingQty,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBatchesByItemAndType = `-- name: GetActiveBatchesByItemAndType :many
SELECT
    b.id,
    b.batch_code,
    COALESCE(i.sku, '') AS sku,
    b.initial_qty,
    GREATEST(b.remaining_qty - b.reserved_qty, 0)::numeric AS remaining_qty,
    b.status,
    b.created_at
FROM inventory_batches b
JOIN items i ON i.id = b.item_id
WHERE b.item_id = $1
    AND b.type = $2
    AND b.remaining_qty > b.reserved_qty
    AND b.status = 'ACTIVE'::batch_status
ORDER BY b.created_at ASC
`

type GetActiveBatchesByItemAndTypeParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	Type   BatchType   `json:"type"`
}

type GetActiveBatchesByItemAndTypeRow struct {
	ID           pgtype.UUID        `json:"id"`
	BatchCode    string             `json:"batch_code"`
	Sku          string             `json:"sku"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveBatchesByItemAndType(ctx context.Context, arg GetActiveBatchesByItemAndTypeParams) ([]GetActiveBatchesByItemAndTypeRow, error) {
	rows, err := q.db.Query(ctx, getActiveBatchesByItemAndType, arg.ItemID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBatchesByItemAndTypeRow
	for rows.Next() {
		var i GetActiveBatchesByItemAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.Sku,
			&i.InitialQty,
			&i.RemainingQty,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBatchesByType = `-- name: GetActiveBatchesByType :many
SELECT
    b.id,
    b.batch_code,
    COALESCE(i.sku, '') AS sku,
    b.initial_qty,
    GREATEST(b.remaining_qty - b.reserved_qty, 0)::numeric AS remaining_qty,
    b.status,
    b.created_at
FROM inventory_batches b
JOIN items i ON i.id = b.item_id
WHERE b.type = $1
    AND b.remaining_qty > b.reserved_qty
    AND b.status = 'ACTIVE'::batch_status
ORDER BY b.created_at ASC
`

type GetActiveBatchesByTypeRow struct {
	ID           pgtype.UUID        `json:"id"`
	BatchCode    string             `json:"batch_code"`
	Sku          string             `json:"sku"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveBatchesByType(ctx context.Context, type_ BatchType) ([]GetActiveBatchesByTypeRow, error) {
	rows, err := q.db.Query(ctx, getActiveBatchesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBatchesByTypeRow
	for rows.Next() {
		var i GetActiveBatchesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.Sku,
			&i.InitialQty,
			&i.RemainingQty,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatch = `-- name: GetBatch :one
SELECT id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost FROM inventory_batches
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBatch(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const getBatchForUpdate = `-- name: GetBatchForUpdate :one
SELECT id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost FROM inventory_batches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatchForUpdate, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const getFinishedGoodBatches = `-- name: GetFinishedGoodBatches :many
SELECT
    b.id,
    b.batch_code,
    b.initial_qty,
    b.remaining_qty,
    b.reserved_qty,
    GREATEST(b.remaining_qty - b.reserved_qty, 0)::numeric AS available_qty,
    b.status,
    b.created_at,
    b.parent_batch_id,
    COALESCE(parent.batch_code, '') AS source_molded_batch_code
FROM inventory_batches b
LEFT JOIN inventory_batches parent ON parent.id = b.parent_batch_id
WHERE b.item_id = $1
  AND b.type = 'FINISHED'
ORDER BY b.created_at DESC, b.batch_code DESC
`

type GetFinishedGoodBatchesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BatchCode             string             `json:"batch_code"`
	InitialQty            pgtype.Numeric     `json:"initial_qty"`
	RemainingQty          pgtype.Numeric     `json:"remaining_qty"`
	ReservedQty           pgtype.Numeric     `json:"reserved_qty"`
	AvailableQty          pgtype.Numeric     `json:"available_qty"`
	Status                BatchStatus        `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ParentBatchID         pgtype.UUID        `json:"parent_batch_id"`
	SourceMoldedBatchCode string             `json:"source_molded_batch_code"`
}

func (q *Queries) GetFinishedGoodBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodBatchesRow, error) {
	rows, err := q.db.Query(ctx, getFinishedGoodBatches, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedGoodBatchesRow
	for rows.Next() {
		var i GetFinishedGoodBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.InitialQty,
			&i.RemainingQty,
			&i.ReservedQty,
			&i.AvailableQty,
			&i.Status,
			&i.CreatedAt,
			&i.ParentBatchID,
			&i.SourceMoldedBatchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedGoodRecentPolishingOutput = `-- name: GetFinishedGoodRecentPolishingOutput :many
SELECT
    j.id AS journal_id,
    j.created_at,
    fb.id AS finished_batch_id,
    fb.batch_code AS finished_batch_code,
    mb.id AS source_molded_batch_id,
    COALESCE(mb.batch_code, '') AS source_molded_batch_code,
    j.finished_qty,
    j.scrap_qty,
    j.shortlength_qty,
    j.process_loss_qty,
    COALESCE(u.name, '') AS operator_name
FROM inventory_batches fb
JOIN inventory_transactions ft
    ON ft.batch_id = fb.id
   AND ft.direction = 'IN'
   AND ft.reference_type = 'PRODUCTION_JOURNAL'
JOIN production_journals j ON j.id = ft.reference_id
LEFT JOIN inventory_batches mb ON mb.id = fb.parent_batch_id
LEFT JOIN users u ON u.id = j.created_by
WHERE fb.item_id = $1
  AND fb.type = 'FINISHED'
ORDER BY j.created_at DESC
LIMIT $2
`

type GetFinishedGoodRecentPolishingOutputParams struct {
	ItemID    pgtype.UUID `json:"item_id"`
	PageLimit int32       `json:"page_limit"`
}

type GetFinishedGoodRecentPolishingOutputRow struct {
	JournalID             pgtype.UUID        `json:"journal_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	FinishedBatchID       pgtype.UUID        `json:"finished_batch_id"`
	FinishedBatchCode     string             `json:"finished_batch_code"`
	SourceMoldedBatchID   pgtype.UUID        `json:"source_molded_batch_id"`
	SourceMoldedBatchCode string             `json:"source_molded_batch_code"`
	FinishedQty           pgtype.Numeric     `json:"finished_qty"`
	ScrapQty              pgtype.Numeric     `json:"scrap_qty"`
	ShortlengthQty        pgtype.Numeric     `json:"shortlength_qty"`
	ProcessLossQty        pgtype.Numeric     `json:"process_loss_qty"`
	OperatorName          string             `json:"operator_name"`
}

func (q *Queries) GetFinishedGoodRecentPolishingOutput(ctx context.Context, arg GetFinishedGoodRecentPolishingOutputParams) ([]GetFinishedGoodRecentPolishingOutputRow, error) {
	rows, err := q.db.Query(ctx, getFinishedGoodRecentPolishingOutput, arg.ItemID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedGoodRecentPolishingOutputRow
	for rows.Next() {
		var i GetFinishedGoodRecentPolishingOutputRow
		if err := rows.Scan(
			&i.JournalID,
			&i.CreatedAt,
			&i.FinishedBatchID,
			&i.FinishedBatchCode,
			&i.SourceMoldedBatchID,
			&i.SourceMoldedBatchCode,
			&i.FinishedQty,
			&i.ScrapQty,
			&i.ShortlengthQty,
			&i.ProcessLossQty,
			&i.OperatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedGoodSourceMoldedBatches = `-- name: GetFinishedGoodSourceMoldedBatches :many
SELECT
    mb.id,
    mb.batch_code,
    mb.created_at,
    mb.status,
    GREATEST(mb.remaining_qty - mb.reserved_qty, 0)::numeric AS available_qty,
    COALESCE(SUM(j.finished_qty), 0)::numeric AS produced_qty,
    MAX(j.created_at) AS latest_polished_at
FROM inventory_batches fb
JOIN inventory_transactions ft
    ON ft.batch_id = fb.id
   AND ft.direction = 'IN'
   AND ft.reference_type = 'PRODUCTION_JOURNAL'
JOIN production_journals j ON j.id = ft.reference_id
JOIN inventory_batches mb ON mb.id = fb.parent_batch_id
WHERE fb.item_id = $1
  AND fb.type = 'FINISHED'
GROUP BY mb.id, mb.batch_code, mb.created_at, mb.status, mb.remaining_qty, mb.reserved_qty
ORDER BY latest_polished_at DESC, mb.batch_code DESC
`

type GetFinishedGoodSourceMoldedBatchesRow struct {
	ID               pgtype.UUID        `json:"id"`
	BatchCode        string             `json:"batch_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Status           BatchStatus        `json:"status"`
	AvailableQty     pgtype.Numeric     `json:"available_qty"`
	ProducedQty      pgtype.Numeric     `json:"produced_qty"`
	LatestPolishedAt interface{}        `json:"latest_polished_at"`
}

func (q *Queries) GetFinishedGoodSourceMoldedBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodSourceMoldedBatchesRow, error) {
	rows, err := q.db.Query(ctx, getFinishedGoodSourceMoldedBatches, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedGoodSourceMoldedBatchesRow
	for rows.Next() {
		var i GetFinishedGoodSourceMoldedBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.CreatedAt,
			&i.Status,
			&i.AvailableQty,
			&i.ProducedQty,
			&i.LatestPolishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedGoodSourceRawBatches = `-- name: GetFinishedGoodSourceRawBatches :many
WITH source_molded AS (
    SELECT DISTINCT fb.parent_batch_id AS molded_batch_id
    FROM inventory_batches fb
    WHERE fb.item_id = $1
      AND fb.type = 'FINISHED'
      AND fb.parent_batch_id IS NOT NULL
)
SELECT
    rb.id,
    rb.batch_code,
    rb.created_at,
    rb.status,
    GREATEST(rb.remaining_qty - rb.reserved_qty, 0)::numeric AS available_qty,
    COALESCE(v.name, '') AS vendor_name,
    COALESCE(po.po_number, '') AS po_number,
    MAX(mj.created_at) AS latest_used_at
FROM source_molded sm
JOIN inventory_transactions mt
    ON mt.batch_id = sm.molded_batch_id
   AND mt.direction = 'IN'
   AND mt.reference_type = 'PRODUCTION_JOURNAL'
JOIN production_journals mj ON mj.id = mt.reference_id
JOIN inventory_batches rb ON rb.id = mj.source_batch_id
LEFT JOIN purchase_orders po ON po.id = rb.parent_po_id
LEFT JOIN vendors v ON v.id = po.vendor_id
GROUP BY rb.id, rb.batch_code, rb.created_at, rb.status, rb.remaining_qty, rb.reserved_qty, v.name, po.po_number
ORDER BY latest_used_at DESC, rb.batch_code DESC
`

type GetFinishedGoodSourceRawBatchesRow struct {
	ID           pgtype.UUID        `json:"id"`
	BatchCode    string             `json:"batch_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Status       BatchStatus        `json:"status"`
	AvailableQty pgtype.Numeric     `json:"available_qty"`
	VendorName   string             `json:"vendor_name"`
	PoNumber     string             `json:"po_number"`
	LatestUsedAt interface{}        `json:"latest_used_at"`
}

func (q *Queries) GetFinishedGoodSourceRawBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodSourceRawBatchesRow, error) {
	rows, err := q.db.Query(ctx, getFinishedGoodSourceRawBatches, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedGoodSourceRawBatchesRow
	for rows.Next() {
		var i GetFinishedGoodSourceRawBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.CreatedAt,
			&i.Status,
			&i.AvailableQty,
			&i.VendorName,
			&i.PoNumber,
			&i.LatestUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedGoodSummary = `-- name: GetFinishedGoodSummary :one
SELECT
    i.id AS item_id,
    COALESCE(i.sku, '') AS sku,
    i.name,
    i.diameter,
    i.low_stock_threshold,
    i.linked_raw_material_id,
    COALESCE(raw.sku, '') AS linked_raw_material_sku,
    COALESCE(raw.name, '') AS linked_raw_material_name,
    raw.specs AS linked_raw_material_specs,
    COALESCE(SUM(b.remaining_qty), 0)::numeric AS total_qty,
    COALESCE(SUM(GREATEST(b.remaining_qty - b.reserved_qty, 0)) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS available_qty,
    COALESCE(SUM(b.reserved_qty) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS reserved_qty,
    COALESCE(SUM(b.remaining_qty) FILTER (WHERE b.status = 'HOLD'), 0)::numeric AS hold_qty,
    COUNT(b.id)::int AS batch_count
FROM items i
LEFT JOIN items raw ON raw.id = i.linked_raw_material_id
LEFT JOIN inventory_batches b
    ON b.item_id = i.id
   AND b.type = 'FINISHED'
WHERE i.id = $1
  AND i.category = 'FINISHED'::item_category
  AND i.is_active = true
GROUP BY
    i.id,
    i.sku,
    i.name,
    i.diameter,
    i.low_stock_threshold,
    i.linked_raw_material_id,
    raw.sku,
    raw.name,
    raw.specs
`

type GetFinishedGoodSummaryRow struct {
	ItemID                 pgtype.UUID    `json:"item_id"`
	Sku                    string         `json:"sku"`
	Name                   string         `json:"name"`
	Diameter               pgtype.Numeric `json:"diameter"`
	LowStockThreshold      pgtype.Numeric `json:"low_stock_threshold"`
	LinkedRawMaterialID    pgtype.UUID    `json:"linked_raw_material_id"`
	LinkedRawMaterialSku   string         `json:"linked_raw_material_sku"`
	LinkedRawMaterialName  string         `json:"linked_raw_material_name"`
	LinkedRawMaterialSpecs []byte         `json:"linked_raw_material_specs"`
	TotalQty               pgtype.Numeric `json:"total_qty"`
	AvailableQty           pgtype.Numeric `json:"available_qty"`
	ReservedQty            pgtype.Numeric `json:"reserved_qty"`
	HoldQty                pgtype.Numeric `json:"hold_qty"`
	BatchCount             int32          `json:"batch_count"`
}

func (q *Queries) GetFinishedGoodSummary(ctx context.Context, id pgtype.UUID) (GetFinishedGoodSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFinishedGoodSummary, id)
	var i GetFinishedGoodSummaryRow
	err := row.Scan(
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.Diameter,
		&i.LowStockThreshold,
		&i.LinkedRawMaterialID,
		&i.LinkedRawMaterialSku,
		&i.LinkedRawMaterialName,
		&i.LinkedRawMaterialSpecs,
		&i.TotalQty,
		&i.AvailableQty,
		&i.ReservedQty,
		&i.HoldQty,
		&i.BatchCount,
	)
	return i, err
}

const getFinishedGoodsMaster = `-- name: GetFinishedGoodsMaster :many
SELECT
    i.id AS item_id,
    COALESCE(i.sku, '') AS sku,
    i.name,
    i.diameter,
    i.low_stock_threshold,
    COALESCE(SUM(GREATEST(b.remaining_qty - b.reserved_qty, 0)) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS available_qty,
    COALESCE(SUM(b.reserved_qty) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS reserved_qty
FROM items i
LEFT JOIN inventory_batches b
    ON b.item_id = i.id
   AND b.type = 'FINISHED'
WHERE i.category = 'FINISHED'::item_category
  AND i.is_active = true
GROUP BY i.id, i.sku, i.name, i.diameter, i.low_stock_threshold
ORDER BY i.name
`

type GetFinishedGoodsMasterRow struct {
	ItemID            pgtype.UUID    `json:"item_id"`
	Sku               string         `json:"sku"`
	Name              string         `json:"name"`
	Diameter          pgtype.Numeric `json:"diameter"`
	LowStockThreshold pgtype.Numeric `json:"low_stock_threshold"`
	AvailableQty      pgtype.Numeric `json:"available_qty"`
	ReservedQty       pgtype.Numeric `json:"reserved_qty"`
}

func (q *Queries) GetFinishedGoodsMaster(ctx context.Context) ([]GetFinishedGoodsMasterRow, error) {
	rows, err := q.db.Query(ctx, getFinishedGoodsMaster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedGoodsMasterRow
	for rows.Next() {
		var i GetFinishedGoodsMasterRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Sku,
			&i.Name,
			&i.Diameter,
			&i.LowStockThreshold,
			&i.AvailableQty,
			&i.ReservedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryAggregated = `-- name: GetInventoryAggregated :many
SELECT i.category,
       i.id as item_id,
    i.sku,
       i.name,
       i.specs,
    SUM(b.remaining_qty) as total_qty,
    COALESCE(SUM(GREATEST(b.remaining_qty - b.reserved_qty, 0)) FILTER (WHERE b.status = 'ACTIVE'), 0) as available_qty,
    COALESCE(SUM(b.reserved_qty) FILTER (WHERE b.status = 'ACTIVE'), 0) as reserved_qty
FROM inventory_batches b
JOIN items i ON b.item_id = i.id
WHERE (b.remaining_qty > 0 OR b.reserved_qty > 0)
    AND (
        (i.category = 'RAW'::item_category AND b.type = 'RAW'::batch_type)
        OR (i.category = 'SEMI_FINISHED'::item_category AND b.type = 'MOLDED'::batch_type)
        OR (i.category = 'FINISHED'::item_category AND b.type = 'FINISHED'::batch_type)
        OR i.category = 'SCRAP'::item_category
    )
GROUP BY i.category, i.id, i.sku, i.name, i.specs
ORDER BY i.category, i.name
`

type GetInventoryAggregatedRow struct {
	Category     ItemCategory `json:"category"`
	ItemID       pgtype.UUID  `json:"item_id"`
	Sku          pgtype.Text  `json:"sku"`
	Name         string       `json:"name"`
	Specs        []byte       `json:"specs"`
	TotalQty     int64        `json:"total_qty"`
	AvailableQty interface{}  `json:"available_qty"`
	ReservedQty  interface{}  `json:"reserved_qty"`
}

func (q *Queries) GetInventoryAggregated(ctx context.Context) ([]GetInventoryAggregatedRow, error) {
	rows, err := q.db.Query(ctx, getInventoryAggregated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryAggregatedRow
	for rows.Next() {
		var i GetInventoryAggregatedRow
		if err := rows.Scan(
			&i.Category,
			&i.ItemID,
			&i.Sku,
			&i.Name,
			&i.Specs,
			&i.TotalQty,
			&i.AvailableQty,
			&i.ReservedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextActiveBatch = `-- name: GetNextActiveBatch :one
SELECT
    b.id,
    b.item_id,
    b.batch_code,
    b.initial_qty,
    b.remaining_qty,
    b.reserved_qty,
    b.status,
    b.created_at
FROM inventory_batches b
WHERE b.item_id = $1
    AND b.status = 'ACTIVE'::batch_status
    AND b.remaining_qty > b.reserved_qty
ORDER BY b.created_at ASC, b.id ASC
LIMIT 1
`

type GetNextActiveBatchRow struct {
	ID           pgtype.UUID        `json:"id"`
	ItemID       pgtype.UUID        `json:"item_id"`
	BatchCode    string             `json:"batch_code"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	ReservedQty  pgtype.Numeric     `json:"reserved_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNextActiveBatch(ctx context.Context, itemID pgtype.UUID) (GetNextActiveBatchRow, error) {
	row := q.db.QueryRow(ctx, getNextActiveBatch, itemID)
	var i GetNextActiveBatchRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.ReservedQty,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProcurementReceiptTransactionForUpdate = `-- name: GetProcurementReceiptTransactionForUpdate :one
SELECT id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at FROM inventory_transactions
WHERE id = $1
    AND reference_type = 'PURCHASE_ORDER'
    AND direction = 'IN'
FOR UPDATE
`

func (q *Queries) GetProcurementReceiptTransactionForUpdate(ctx context.Context, id pgtype.UUID) (InventoryTransaction, error) {
	row := q.db.QueryRow(ctx, getProcurementReceiptTransactionForUpdate, id)
	var i InventoryTransaction
	err := row.Scan(
		&i.ID,
		&i.MovementGroupID,
		&i.ItemID,
		&i.BatchID,
		&i.Direction,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getRawMaterialBatches = `-- name: GetRawMaterialBatches :many
SELECT
    b.id,
    b.batch_code,
    b.initial_qty,
    b.remaining_qty,
    b.reserved_qty,
    GREATEST(b.remaining_qty - b.reserved_qty, 0)::numeric AS available_qty,
    b.status,
    b.created_at,
    b.parent_po_id,
    COALESCE(v.name, '') AS vendor_name,
    COALESCE(po.po_number, '') AS po_number
FROM inventory_batches b
LEFT JOIN purchase_orders po ON po.id = b.parent_po_id
LEFT JOIN vendors v ON v.id = po.vendor_id
WHERE b.item_id = $1
    AND b.type = 'RAW'
ORDER BY b.created_at ASC
`

type GetRawMaterialBatchesRow struct {
	ID           pgtype.UUID        `json:"id"`
	BatchCode    string             `json:"batch_code"`
	InitialQty   pgtype.Numeric     `json:"initial_qty"`
	RemainingQty pgtype.Numeric     `json:"remaining_qty"`
	ReservedQty  pgtype.Numeric     `json:"reserved_qty"`
	AvailableQty pgtype.Numeric     `json:"available_qty"`
	Status       BatchStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ParentPoID   pgtype.UUID        `json:"parent_po_id"`
	VendorName   string             `json:"vendor_name"`
	PoNumber     string             `json:"po_number"`
}

func (q *Queries) GetRawMaterialBatches(ctx context.Context, itemID pgtype.UUID) ([]GetRawMaterialBatchesRow, error) {
	rows, err := q.db.Query(ctx, getRawMaterialBatches, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRawMaterialBatchesRow
	for rows.Next() {
		var i GetRawMaterialBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchCode,
			&i.InitialQty,
			&i.RemainingQty,
			&i.ReservedQty,
			&i.AvailableQty,
			&i.Status,
			&i.CreatedAt,
			&i.ParentPoID,
			&i.VendorName,
			&i.PoNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawMaterialMaster = `-- name: GetRawMaterialMaster :many
SELECT
    i.id AS item_id,
    COALESCE(i.sku, '') AS sku,
    i.name,
    i.specs,
    i.low_stock_threshold,
    COALESCE(SUM(GREATEST(b.remaining_qty - b.reserved_qty, 0)) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS available_qty,
    COALESCE(SUM(b.reserved_qty) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS reserved_qty,
    COALESCE((
        SELECT SUM(GREATEST(po.ordered_qty - po.received_qty, 0))
        FROM purchase_orders po
        WHERE po.item_id = i.id
          AND po.status IN ('PENDING', 'PARTIAL')
    ), 0)::numeric AS pending_deliveries
FROM items i
LEFT JOIN inventory_batches b ON b.item_id = i.id AND b.type = 'RAW'
WHERE i.category = 'RAW'::item_category AND i.is_active = true
GROUP BY i.id, i.sku, i.name, i.specs, i.low_stock_threshold
ORDER BY i.name
`

type GetRawMaterialMasterRow struct {
	ItemID            pgtype.UUID    `json:"item_id"`
	Sku               string         `json:"sku"`
	Name              string         `json:"name"`
	Specs             []byte         `json:"specs"`
	LowStockThreshold pgtype.Numeric `json:"low_stock_threshold"`
	AvailableQty      pgtype.Numeric `json:"available_qty"`
	ReservedQty       pgtype.Numeric `json:"reserved_qty"`
	PendingDeliveries pgtype.Numeric `json:"pending_deliveries"`
}

func (q *Queries) GetRawMaterialMaster(ctx context.Context) ([]GetRawMaterialMasterRow, error) {
	rows, err := q.db.Query(ctx, getRawMaterialMaster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRawMaterialMasterRow
	for rows.Next() {
		var i GetRawMaterialMasterRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Sku,
			&i.Name,
			&i.Specs,
			&i.LowStockThreshold,
			&i.AvailableQty,
			&i.ReservedQty,
			&i.PendingDeliveries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawMaterialSummary = `-- name: GetRawMaterialSummary :one
SELECT
    i.id AS item_id,
    COALESCE(i.sku, '') AS sku,
    i.name,
    i.specs,
    i.low_stock_threshold,
    COALESCE(SUM(GREATEST(b.remaining_qty - b.reserved_qty, 0)) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS available_qty,
    COALESCE(SUM(b.reserved_qty) FILTER (WHERE b.status = 'ACTIVE'), 0)::numeric AS reserved_qty,
    COALESCE(SUM(b.remaining_qty) FILTER (WHERE b.status = 'HOLD'), 0)::numeric AS hold_qty,
    COALESCE((
        SELECT SUM(GREATEST(po.ordered_qty - po.received_qty, 0))
        FROM purchase_orders po
        WHERE po.item_id = i.id
          AND po.status IN ('PENDING', 'PARTIAL')
    ), 0)::numeric AS pending_deliveries
FROM items i
LEFT JOIN inventory_batches b ON b.item_id = i.id AND b.type = 'RAW'
WHERE i.id = $1
    AND i.category = 'RAW'::item_category
    AND i.is_active = true
GROUP BY i.id, i.sku, i.name, i.specs, i.low_stock_threshold
`

type GetRawMaterialSummaryRow struct {
	ItemID            pgtype.UUID    `json:"item_id"`
	Sku               string         `json:"sku"`
	Name              string         `json:"name"`
	Specs             []byte         `json:"specs"`
	LowStockThreshold pgtype.Numeric `json:"low_stock_threshold"`
	AvailableQty      pgtype.Numeric `json:"available_qty"`
	ReservedQty       pgtype.Numeric `json:"reserved_qty"`
	HoldQty           pgtype.Numeric `json:"hold_qty"`
	PendingDeliveries pgtype.Numeric `json:"pending_deliveries"`
}

func (q *Queries) GetRawMaterialSummary(ctx context.Context, id pgtype.UUID) (GetRawMaterialSummaryRow, error) {
	row := q.db.QueryRow(ctx, getRawMaterialSummary, id)
	var i GetRawMaterialSummaryRow
	err := row.Scan(
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.Specs,
		&i.LowStockThreshold,
		&i.AvailableQty,
		&i.ReservedQty,
		&i.HoldQty,
		&i.PendingDeliveries,
	)
	return i, err
}

const getTransactionByMovementGroup = `-- name: GetTransactionByMovementGroup :one
SELECT id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at FROM inventory_transactions
WHERE movement_group_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetTransactionByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (InventoryTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByMovementGroup, movementGroupID)
	var i InventoryTransaction
	err := row.Scan(
		&i.ID,
		&i.MovementGroupID,
		&i.ItemID,
		&i.BatchID,
		&i.Direction,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByBatch = `-- name: ListTransactionsByBatch :many
SELECT id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at FROM inventory_transactions
WHERE batch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByBatchParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByBatch(ctx context.Context, arg ListTransactionsByBatchParams) ([]InventoryTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByBatch, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryTransaction
	for rows.Next() {
		var i InventoryTransaction
		if err := rows.Scan(
			&i.ID,
			&i.MovementGroupID,
			&i.ItemID,
			&i.BatchID,
			&i.Direction,
			&i.Quantity,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransaction = `-- name: RecordTransaction :one
INSERT INTO inventory_transactions (
    movement_group_id, item_id, batch_id, direction, 
    quantity, reference_type, reference_id, performed_by, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at
`

type RecordTransactionParams struct {
	MovementGroupID pgtype.UUID    `json:"movement_group_id"`
	ItemID          pgtype.UUID    `json:"item_id"`
	BatchID         pgtype.UUID    `json:"batch_id"`
	Direction       TxDirection    `json:"direction"`
	Quantity        pgtype.Numeric `json:"quantity"`
	ReferenceType   string         `json:"reference_type"`
	ReferenceID     pgtype.UUID    `json:"reference_id"`
	PerformedBy     pgtype.UUID    `json:"performed_by"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) RecordTransaction(ctx context.Context, arg RecordTransactionParams) (InventoryTransaction, error) {
	row := q.db.QueryRow(ctx, recordTransaction,
		arg.MovementGroupID,
		arg.ItemID,
		arg.BatchID,
		arg.Direction,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.PerformedBy,
		arg.Notes,
	)
	var i InventoryTransaction
	err := row.Scan(
		&i.ID,
		&i.MovementGroupID,
		&i.ItemID,
		&i.BatchID,
		&i.Direction,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const releaseBatchReservation = `-- name: ReleaseBatchReservation :one
UPDATE inventory_batches
SET reserved_qty = reserved_qty - $1,
    updated_at = NOW()
WHERE id = $2
    AND $1 > 0
    AND reserved_qty >= $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type ReleaseBatchReservationParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) ReleaseBatchReservation(ctx context.Context, arg ReleaseBatchReservationParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, releaseBatchReservation, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const reserveBatchStock = `-- name: ReserveBatchStock :one
UPDATE inventory_batches
SET reserved_qty = reserved_qty + $1,
    updated_at = NOW()
WHERE id = $2
    AND $1 > 0
    AND status = 'ACTIVE'::batch_status
    AND reserved_qty + $1 <= remaining_qty
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type ReserveBatchStockParams struct {
	Qty pgtype.Numeric `json:"qty"`
	ID  pgtype.UUID    `json:"id"`
}

func (q *Queries) ReserveBatchStock(ctx context.Context, arg ReserveBatchStockParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, reserveBatchStock, arg.Qty, arg.ID)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const setBatchStatus = `-- name: SetBatchStatus :one
UPDATE inventory_batches
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type SetBatchStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status BatchStatus `json:"status"`
}

func (q *Queries) SetBatchStatus(ctx context.Context, arg SetBatchStatusParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, setBatchStatus, arg.ID, arg.Status)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}

const updateBatchQuantity = `-- name: UpdateBatchQuantity :one
UPDATE inventory_batches
SET remaining_qty = remaining_qty + $2, 
    updated_at = NOW(),
    status = CASE 
        WHEN remaining_qty + $2 <= 0 THEN 'EXHAUSTED'::batch_status 
        WHEN remaining_qty + $2 < initial_qty THEN 'ACTIVE'::batch_status
        ELSE status
    END
WHERE id = $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, status, created_at, updated_at, daily_sequence, type, diameter, reserved_qty, parent_batch_id, expiry_date, parent_po_id, unit_cost
`

type UpdateBatchQuantityParams struct {
	ID           pgtype.UUID    `json:"id"`
	RemainingQty pgtype.Numeric `json:"remaining_qty"`
}

func (q *Queries) UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, updateBatchQuantity, arg.ID, arg.RemainingQty)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailySequence,
		&i.Type,
		&i.Diameter,
		&i.ReservedQty,
		&i.ParentBatchID,
		&i.ExpiryDate,
		&i.ParentPoID,
		&i.UnitCost,
	)
	return i, err
}
