// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO inventory_batches (
    item_id, batch_code, initial_qty, remaining_qty, unit_cost, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, unit_cost, status, created_at, updated_at
`

type CreateBatchParams struct {
	ItemID       pgtype.UUID    `json:"item_id"`
	BatchCode    string         `json:"batch_code"`
	InitialQty   pgtype.Numeric `json:"initial_qty"`
	RemainingQty pgtype.Numeric `json:"remaining_qty"`
	UnitCost     pgtype.Numeric `json:"unit_cost"`
	Status       BatchStatus    `json:"status"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ItemID,
		arg.BatchCode,
		arg.InitialQty,
		arg.RemainingQty,
		arg.UnitCost,
		arg.Status,
	)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.UnitCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveBatchesByItem = `-- name: GetActiveBatchesByItem :many
SELECT id, batch_code, remaining_qty
FROM inventory_batches
WHERE item_id = $1 AND remaining_qty > 0
ORDER BY created_at ASC
`

type GetActiveBatchesByItemRow struct {
	ID           pgtype.UUID    `json:"id"`
	BatchCode    string         `json:"batch_code"`
	RemainingQty pgtype.Numeric `json:"remaining_qty"`
}

func (q *Queries) GetActiveBatchesByItem(ctx context.Context, itemID pgtype.UUID) ([]GetActiveBatchesByItemRow, error) {
	rows, err := q.db.Query(ctx, getActiveBatchesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBatchesByItemRow
	for rows.Next() {
		var i GetActiveBatchesByItemRow
		if err := rows.Scan(&i.ID, &i.BatchCode, &i.RemainingQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatch = `-- name: GetBatch :one
SELECT id, item_id, batch_code, initial_qty, remaining_qty, unit_cost, status, created_at, updated_at FROM inventory_batches
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBatch(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.UnitCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchForUpdate = `-- name: GetBatchForUpdate :one
SELECT id, item_id, batch_code, initial_qty, remaining_qty, unit_cost, status, created_at, updated_at FROM inventory_batches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatchForUpdate, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.UnitCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryAggregated = `-- name: GetInventoryAggregated :many
SELECT i.category,
       i.id as item_id,
       i.name,
       i.specs,
       SUM(b.remaining_qty) as total_qty
FROM inventory_batches b
JOIN items i ON b.item_id = i.id
WHERE b.remaining_qty > 0
GROUP BY i.category, i.id, i.name, i.specs
ORDER BY i.category, i.name
`

type GetInventoryAggregatedRow struct {
	Category ItemCategory `json:"category"`
	ItemID   pgtype.UUID  `json:"item_id"`
	Name     string       `json:"name"`
	Specs    []byte       `json:"specs"`
	TotalQty int64        `json:"total_qty"`
}

func (q *Queries) GetInventoryAggregated(ctx context.Context) ([]GetInventoryAggregatedRow, error) {
	rows, err := q.db.Query(ctx, getInventoryAggregated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryAggregatedRow
	for rows.Next() {
		var i GetInventoryAggregatedRow
		if err := rows.Scan(
			&i.Category,
			&i.ItemID,
			&i.Name,
			&i.Specs,
			&i.TotalQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByMovementGroup = `-- name: GetTransactionByMovementGroup :one
SELECT id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at FROM inventory_transactions
WHERE movement_group_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetTransactionByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (InventoryTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByMovementGroup, movementGroupID)
	var i InventoryTransaction
	err := row.Scan(
		&i.ID,
		&i.MovementGroupID,
		&i.ItemID,
		&i.BatchID,
		&i.Direction,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByBatch = `-- name: ListTransactionsByBatch :many
SELECT id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at FROM inventory_transactions
WHERE batch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByBatchParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByBatch(ctx context.Context, arg ListTransactionsByBatchParams) ([]InventoryTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByBatch, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryTransaction
	for rows.Next() {
		var i InventoryTransaction
		if err := rows.Scan(
			&i.ID,
			&i.MovementGroupID,
			&i.ItemID,
			&i.BatchID,
			&i.Direction,
			&i.Quantity,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransaction = `-- name: RecordTransaction :one
INSERT INTO inventory_transactions (
    movement_group_id, item_id, batch_id, direction, 
    quantity, reference_type, reference_id, performed_by, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, movement_group_id, item_id, batch_id, direction, quantity, reference_type, reference_id, performed_by, notes, created_at
`

type RecordTransactionParams struct {
	MovementGroupID pgtype.UUID     `json:"movement_group_id"`
	ItemID          pgtype.UUID     `json:"item_id"`
	BatchID         pgtype.UUID     `json:"batch_id"`
	Direction       TxDirection     `json:"direction"`
	Quantity        pgtype.Numeric  `json:"quantity"`
	ReferenceType   TxReferenceType `json:"reference_type"`
	ReferenceID     pgtype.UUID     `json:"reference_id"`
	PerformedBy     pgtype.UUID     `json:"performed_by"`
	Notes           pgtype.Text     `json:"notes"`
}

func (q *Queries) RecordTransaction(ctx context.Context, arg RecordTransactionParams) (InventoryTransaction, error) {
	row := q.db.QueryRow(ctx, recordTransaction,
		arg.MovementGroupID,
		arg.ItemID,
		arg.BatchID,
		arg.Direction,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.PerformedBy,
		arg.Notes,
	)
	var i InventoryTransaction
	err := row.Scan(
		&i.ID,
		&i.MovementGroupID,
		&i.ItemID,
		&i.BatchID,
		&i.Direction,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateBatchQuantity = `-- name: UpdateBatchQuantity :one
UPDATE inventory_batches
SET remaining_qty = remaining_qty + $2, 
    updated_at = NOW(),
    status = CASE 
        WHEN remaining_qty + $2 <= 0 THEN 'EXHAUSTED'::batch_status 
        ELSE status 
    END
WHERE id = $1
RETURNING id, item_id, batch_code, initial_qty, remaining_qty, unit_cost, status, created_at, updated_at
`

type UpdateBatchQuantityParams struct {
	ID           pgtype.UUID    `json:"id"`
	RemainingQty pgtype.Numeric `json:"remaining_qty"`
}

func (q *Queries) UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, updateBatchQuantity, arg.ID, arg.RemainingQty)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchCode,
		&i.InitialQty,
		&i.RemainingQty,
		&i.UnitCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
