// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    parent_id, sku, name, category, base_unit, specs
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, parent_id, sku, name, category, base_unit, specs, is_active, created_at, updated_at, min_qty, max_qty
`

type CreateItemParams struct {
	ParentID pgtype.UUID  `json:"parent_id"`
	Sku      pgtype.Text  `json:"sku"`
	Name     string       `json:"name"`
	Category ItemCategory `json:"category"`
	BaseUnit BaseUnitType `json:"base_unit"`
	Specs    []byte       `json:"specs"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ParentID,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.BaseUnit,
		arg.Specs,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.BaseUnit,
		&i.Specs,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinQty,
		&i.MaxQty,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, parent_id, sku, name, category, base_unit, specs, is_active, created_at, updated_at, min_qty, max_qty FROM items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.BaseUnit,
		&i.Specs,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinQty,
		&i.MaxQty,
	)
	return i, err
}

const getSelectableItems = `-- name: GetSelectableItems :many
SELECT id, name, category, specs
FROM items
WHERE is_active = true
ORDER BY category, name
`

type GetSelectableItemsRow struct {
	ID       pgtype.UUID  `json:"id"`
	Name     string       `json:"name"`
	Category ItemCategory `json:"category"`
	Specs    []byte       `json:"specs"`
}

func (q *Queries) GetSelectableItems(ctx context.Context) ([]GetSelectableItemsRow, error) {
	rows, err := q.db.Query(ctx, getSelectableItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSelectableItemsRow
	for rows.Next() {
		var i GetSelectableItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Specs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveItemsByCategory = `-- name: ListActiveItemsByCategory :many
SELECT id, parent_id, sku, name, category, base_unit, specs, is_active, created_at, updated_at, min_qty, max_qty FROM items
WHERE category = $1 AND is_active = true
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListActiveItemsByCategoryParams struct {
	Category ItemCategory `json:"category"`
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
}

func (q *Queries) ListActiveItemsByCategory(ctx context.Context, arg ListActiveItemsByCategoryParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listActiveItemsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.BaseUnit,
			&i.Specs,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinQty,
			&i.MaxQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByParent = `-- name: ListVariantsByParent :many
SELECT id, parent_id, sku, name, category, base_unit, specs, is_active, created_at, updated_at, min_qty, max_qty FROM items
WHERE parent_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVariantsByParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListVariantsByParent(ctx context.Context, arg ListVariantsByParentParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listVariantsByParent, arg.ParentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.BaseUnit,
			&i.Specs,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinQty,
			&i.MaxQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
