// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO inventory_locations (
    code, name, type, parent_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, code, name, type, parent_id, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	Code     string       `json:"code"`
	Name     string       `json:"name"`
	Type     LocationType `json:"type"`
	ParentID pgtype.UUID  `json:"parent_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (InventoryLocation, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.ParentID,
	)
	var i InventoryLocation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationsByType = `-- name: ListLocationsByType :many
SELECT id, code, name, type, parent_id, is_active, created_at, updated_at FROM inventory_locations
WHERE type = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListLocationsByType(ctx context.Context, type_ LocationType) ([]InventoryLocation, error) {
	rows, err := q.db.Query(ctx, listLocationsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLocation
	for rows.Next() {
		var i InventoryLocation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
