// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryBatch struct {
	ID         pgtype.UUID        `json:"id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	BatchCode  string             `json:"batch_code"`
	Status     pgtype.Text        `json:"status"`
	InitialQty pgtype.Numeric     `json:"initial_qty"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type InventoryTransaction struct {
	ID          pgtype.UUID        `json:"id"`
	BatchID     pgtype.UUID        `json:"batch_id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	TxType      pgtype.Text        `json:"tx_type"`
	ReferenceID pgtype.UUID        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	Specs     []byte             `json:"specs"`
	BaseUnit  pgtype.Text        `json:"base_unit"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	FullName           pgtype.Text        `json:"full_name"`
	Role               pgtype.Text        `json:"role"`
	MustChangePassword pgtype.Bool        `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
