// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (
    order_number,
    customer_id,
    status,
    notes,
    reserved_at,
    dispatched_at,
    cancelled_at,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, order_number, customer_id, status, notes, order_date, reserved_at, dispatched_at, cancelled_at, created_by, created_at, updated_at
`

type CreateSalesOrderParams struct {
	OrderNumber  string             `json:"order_number"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Status       string             `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	ReservedAt   pgtype.Timestamptz `json:"reserved_at"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.OrderNumber,
		arg.CustomerID,
		arg.Status,
		arg.Notes,
		arg.ReservedAt,
		arg.DispatchedAt,
		arg.CancelledAt,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.Notes,
		&i.OrderDate,
		&i.ReservedAt,
		&i.DispatchedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesOrderLine = `-- name: CreateSalesOrderLine :one
INSERT INTO sales_order_lines (
    sales_order_id,
    finished_good_item_id,
    ordered_qty,
    dispatched_qty,
    unit_price,
    line_total
) VALUES (
    $1,
    $2,
    $3,
    0,
    $4,
    $5
)
RETURNING id, sales_order_id, finished_good_item_id, ordered_qty, dispatched_qty, unit_price, line_total, created_at
`

type CreateSalesOrderLineParams struct {
	SalesOrderID       pgtype.UUID    `json:"sales_order_id"`
	FinishedGoodItemID pgtype.UUID    `json:"finished_good_item_id"`
	OrderedQty         pgtype.Numeric `json:"ordered_qty"`
	UnitPrice          pgtype.Numeric `json:"unit_price"`
	LineTotal          pgtype.Numeric `json:"line_total"`
}

func (q *Queries) CreateSalesOrderLine(ctx context.Context, arg CreateSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, createSalesOrderLine,
		arg.SalesOrderID,
		arg.FinishedGoodItemID,
		arg.OrderedQty,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.FinishedGoodItemID,
		&i.OrderedQty,
		&i.DispatchedQty,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesOrderByID = `-- name: GetSalesOrderByID :one
SELECT id, order_number, customer_id, status, notes, order_date, reserved_at, dispatched_at, cancelled_at, created_by, created_at, updated_at
FROM sales_orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSalesOrderByID(ctx context.Context, id pgtype.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderByID, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.Notes,
		&i.OrderDate,
		&i.ReservedAt,
		&i.DispatchedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderByIDForUpdate = `-- name: GetSalesOrderByIDForUpdate :one
SELECT id, order_number, customer_id, status, notes, order_date, reserved_at, dispatched_at, cancelled_at, created_by, created_at, updated_at
FROM sales_orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSalesOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderByIDForUpdate, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.Notes,
		&i.OrderDate,
		&i.ReservedAt,
		&i.DispatchedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderDetail = `-- name: GetSalesOrderDetail :one
WITH line_totals AS (
    SELECT
        sol.sales_order_id,
        COALESCE(SUM(sol.ordered_qty), 0)::numeric AS total_qty,
        COALESCE(SUM(sol.dispatched_qty), 0)::numeric AS dispatched_qty
    FROM sales_order_lines sol
    WHERE sol.sales_order_id = $1
    GROUP BY sol.sales_order_id
),
allocation_totals AS (
    SELECT
        sol.sales_order_id,
        COALESCE(
            SUM(
                CASE
                    WHEN sba.status IN ('RESERVED', 'PARTIALLY_DISPATCHED')
                    THEN GREATEST(sba.allocated_qty - sba.dispatched_qty, 0)
                    ELSE 0
                END
            ),
            0
        )::numeric AS reserved_qty
    FROM sales_order_lines sol
    LEFT JOIN sales_batch_allocations sba ON sba.sales_order_line_id = sol.id
    WHERE sol.sales_order_id = $1
    GROUP BY sol.sales_order_id
)
SELECT
    so.id,
    so.order_number,
    so.customer_id,
    so.status,
    so.notes,
    so.order_date,
    so.reserved_at,
    so.dispatched_at,
    so.cancelled_at,
    so.created_by,
    so.created_at,
    so.updated_at,
    c.display_name AS customer_display_name,
    COALESCE(c.company_name, '') AS customer_company_name,
    COALESCE(c.phone_number, '') AS customer_phone_number,
    COALESCE(lt.total_qty, 0)::numeric AS total_qty,
    COALESCE(at.reserved_qty, 0)::numeric AS reserved_qty,
    COALESCE(lt.dispatched_qty, 0)::numeric AS dispatched_qty
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
LEFT JOIN line_totals lt ON lt.sales_order_id = so.id
LEFT JOIN allocation_totals at ON at.sales_order_id = so.id
WHERE so.id = $1
LIMIT 1
`

type GetSalesOrderDetailRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OrderNumber         string             `json:"order_number"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	Status              string             `json:"status"`
	Notes               pgtype.Text        `json:"notes"`
	OrderDate           pgtype.Timestamptz `json:"order_date"`
	ReservedAt          pgtype.Timestamptz `json:"reserved_at"`
	DispatchedAt        pgtype.Timestamptz `json:"dispatched_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CustomerDisplayName string             `json:"customer_display_name"`
	CustomerCompanyName string             `json:"customer_company_name"`
	CustomerPhoneNumber string             `json:"customer_phone_number"`
	TotalQty            pgtype.Numeric     `json:"total_qty"`
	ReservedQty         pgtype.Numeric     `json:"reserved_qty"`
	DispatchedQty       pgtype.Numeric     `json:"dispatched_qty"`
}

func (q *Queries) GetSalesOrderDetail(ctx context.Context, id pgtype.UUID) (GetSalesOrderDetailRow, error) {
	row := q.db.QueryRow(ctx, getSalesOrderDetail, id)
	var i GetSalesOrderDetailRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.Notes,
		&i.OrderDate,
		&i.ReservedAt,
		&i.DispatchedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerDisplayName,
		&i.CustomerCompanyName,
		&i.CustomerPhoneNumber,
		&i.TotalQty,
		&i.ReservedQty,
		&i.DispatchedQty,
	)
	return i, err
}

const getSalesOrderLineByIDForUpdate = `-- name: GetSalesOrderLineByIDForUpdate :one
SELECT id, sales_order_id, finished_good_item_id, ordered_qty, dispatched_qty, unit_price, line_total, created_at
FROM sales_order_lines
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSalesOrderLineByIDForUpdate(ctx context.Context, id pgtype.UUID) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, getSalesOrderLineByIDForUpdate, id)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.FinishedGoodItemID,
		&i.OrderedQty,
		&i.DispatchedQty,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesOrderLineDetails = `-- name: GetSalesOrderLineDetails :many
SELECT
    sol.id,
    sol.sales_order_id,
    sol.finished_good_item_id,
    sol.ordered_qty,
    sol.dispatched_qty,
    sol.unit_price,
    sol.line_total,
    sol.created_at,
    COALESCE(i.sku, '') AS item_sku,
    i.name AS item_name,
    COALESCE(
        SUM(
            CASE
                WHEN sba.status IN ('RESERVED', 'PARTIALLY_DISPATCHED')
                THEN GREATEST(sba.allocated_qty - sba.dispatched_qty, 0)
                ELSE 0
            END
        ),
        0
    )::numeric AS reserved_qty
FROM sales_order_lines sol
JOIN items i ON i.id = sol.finished_good_item_id
LEFT JOIN sales_batch_allocations sba ON sba.sales_order_line_id = sol.id
WHERE sol.sales_order_id = $1
GROUP BY sol.id, sol.sales_order_id, sol.finished_good_item_id, sol.ordered_qty, sol.dispatched_qty, sol.unit_price, sol.line_total, sol.created_at, i.sku, i.name
ORDER BY sol.created_at ASC, sol.id ASC
`

type GetSalesOrderLineDetailsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SalesOrderID       pgtype.UUID        `json:"sales_order_id"`
	FinishedGoodItemID pgtype.UUID        `json:"finished_good_item_id"`
	OrderedQty         pgtype.Numeric     `json:"ordered_qty"`
	DispatchedQty      pgtype.Numeric     `json:"dispatched_qty"`
	UnitPrice          pgtype.Numeric     `json:"unit_price"`
	LineTotal          pgtype.Numeric     `json:"line_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ItemSku            string             `json:"item_sku"`
	ItemName           string             `json:"item_name"`
	ReservedQty        pgtype.Numeric     `json:"reserved_qty"`
}

func (q *Queries) GetSalesOrderLineDetails(ctx context.Context, salesOrderID pgtype.UUID) ([]GetSalesOrderLineDetailsRow, error) {
	rows, err := q.db.Query(ctx, getSalesOrderLineDetails, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSalesOrderLineDetailsRow
	for rows.Next() {
		var i GetSalesOrderLineDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderID,
			&i.FinishedGoodItemID,
			&i.OrderedQty,
			&i.DispatchedQty,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
			&i.ItemSku,
			&i.ItemName,
			&i.ReservedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderLinesByOrder = `-- name: ListSalesOrderLinesByOrder :many
SELECT id, sales_order_id, finished_good_item_id, ordered_qty, dispatched_qty, unit_price, line_total, created_at
FROM sales_order_lines
WHERE sales_order_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSalesOrderLinesByOrder(ctx context.Context, salesOrderID pgtype.UUID) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLinesByOrder, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderLine
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderID,
			&i.FinishedGoodItemID,
			&i.OrderedQty,
			&i.DispatchedQty,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderLinesByOrderForUpdate = `-- name: ListSalesOrderLinesByOrderForUpdate :many
SELECT id, sales_order_id, finished_good_item_id, ordered_qty, dispatched_qty, unit_price, line_total, created_at
FROM sales_order_lines
WHERE sales_order_id = $1
ORDER BY created_at ASC, id ASC
FOR UPDATE
`

func (q *Queries) ListSalesOrderLinesByOrderForUpdate(ctx context.Context, salesOrderID pgtype.UUID) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLinesByOrderForUpdate, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderLine
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderID,
			&i.FinishedGoodItemID,
			&i.OrderedQty,
			&i.DispatchedQty,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
WITH line_totals AS (
    SELECT
        sol.sales_order_id,
        COALESCE(SUM(sol.ordered_qty), 0)::numeric AS total_qty,
        COALESCE(SUM(sol.dispatched_qty), 0)::numeric AS dispatched_qty
    FROM sales_order_lines sol
    GROUP BY sol.sales_order_id
),
allocation_totals AS (
    SELECT
        sol.sales_order_id,
        COALESCE(
            SUM(
                CASE
                    WHEN sba.status IN ('RESERVED', 'PARTIALLY_DISPATCHED')
                    THEN GREATEST(sba.allocated_qty - sba.dispatched_qty, 0)
                    ELSE 0
                END
            ),
            0
        )::numeric AS reserved_qty
    FROM sales_order_lines sol
    LEFT JOIN sales_batch_allocations sba ON sba.sales_order_line_id = sol.id
    GROUP BY sol.sales_order_id
)
SELECT
    so.id,
    so.order_number,
    so.customer_id,
    so.status,
    so.notes,
    so.order_date,
    so.reserved_at,
    so.dispatched_at,
    so.cancelled_at,
    so.created_by,
    so.created_at,
    so.updated_at,
    c.display_name AS customer_display_name,
    COALESCE(c.company_name, '') AS customer_company_name,
    COALESCE(lt.total_qty, 0)::numeric AS total_qty,
    COALESCE(at.reserved_qty, 0)::numeric AS reserved_qty,
    COALESCE(lt.dispatched_qty, 0)::numeric AS dispatched_qty
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
LEFT JOIN line_totals lt ON lt.sales_order_id = so.id
LEFT JOIN allocation_totals at ON at.sales_order_id = so.id
WHERE (
    $1::text IS NULL
    OR so.status = $1::text
)
ORDER BY so.order_date DESC, so.created_at DESC, so.order_number DESC
LIMIT $3
OFFSET $2
`

type ListSalesOrdersParams struct {
	StatusFilter pgtype.Text `json:"status_filter"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type ListSalesOrdersRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OrderNumber         string             `json:"order_number"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	Status              string             `json:"status"`
	Notes               pgtype.Text        `json:"notes"`
	OrderDate           pgtype.Timestamptz `json:"order_date"`
	ReservedAt          pgtype.Timestamptz `json:"reserved_at"`
	DispatchedAt        pgtype.Timestamptz `json:"dispatched_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CustomerDisplayName string             `json:"customer_display_name"`
	CustomerCompanyName string             `json:"customer_company_name"`
	TotalQty            pgtype.Numeric     `json:"total_qty"`
	ReservedQty         pgtype.Numeric     `json:"reserved_qty"`
	DispatchedQty       pgtype.Numeric     `json:"dispatched_qty"`
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, arg.StatusFilter, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesOrdersRow
	for rows.Next() {
		var i ListSalesOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.Status,
			&i.Notes,
			&i.OrderDate,
			&i.ReservedAt,
			&i.DispatchedAt,
			&i.CancelledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerDisplayName,
			&i.CustomerCompanyName,
			&i.TotalQty,
			&i.ReservedQty,
			&i.DispatchedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderDispatchProgress = `-- name: UpdateOrderDispatchProgress :one
UPDATE sales_order_lines
SET
    dispatched_qty = $1,
    line_total = COALESCE($2::numeric(12,4), line_total)
WHERE id = $3
RETURNING id, sales_order_id, finished_good_item_id, ordered_qty, dispatched_qty, unit_price, line_total, created_at
`

type UpdateOrderDispatchProgressParams struct {
	DispatchedQty pgtype.Numeric `json:"dispatched_qty"`
	LineTotal     pgtype.Numeric `json:"line_total"`
	ID            pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateOrderDispatchProgress(ctx context.Context, arg UpdateOrderDispatchProgressParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, updateOrderDispatchProgress, arg.DispatchedQty, arg.LineTotal, arg.ID)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.FinishedGoodItemID,
		&i.OrderedQty,
		&i.DispatchedQty,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const updateSalesOrderStatus = `-- name: UpdateSalesOrderStatus :one
UPDATE sales_orders
SET
    status = $1,
    notes = COALESCE($2::text, notes),
    reserved_at = COALESCE($3::timestamptz, reserved_at),
    dispatched_at = $4::timestamptz,
    cancelled_at = $5::timestamptz,
    updated_at = NOW()
WHERE id = $6
RETURNING id, order_number, customer_id, status, notes, order_date, reserved_at, dispatched_at, cancelled_at, created_by, created_at, updated_at
`

type UpdateSalesOrderStatusParams struct {
	Status       string             `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	ReservedAt   pgtype.Timestamptz `json:"reserved_at"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	ID           pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderStatus,
		arg.Status,
		arg.Notes,
		arg.ReservedAt,
		arg.DispatchedAt,
		arg.CancelledAt,
		arg.ID,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.Notes,
		&i.OrderDate,
		&i.ReservedAt,
		&i.DispatchedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
