// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournal = `-- name: CreateJournal :one
INSERT INTO production_journals (
    movement_group_id,
    source_batch_id,
    input_qty,
    finished_qty,
    scrap_qty,
    loss_reason,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type CreateJournalParams struct {
	MovementGroupID pgtype.UUID    `json:"movement_group_id"`
	SourceBatchID   pgtype.UUID    `json:"source_batch_id"`
	InputQty        pgtype.Numeric `json:"input_qty"`
	FinishedQty     pgtype.Numeric `json:"finished_qty"`
	ScrapQty        pgtype.Numeric `json:"scrap_qty"`
	LossReason      pgtype.Text    `json:"loss_reason"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createJournal,
		arg.MovementGroupID,
		arg.SourceBatchID,
		arg.InputQty,
		arg.FinishedQty,
		arg.ScrapQty,
		arg.LossReason,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getJournalByMovementGroup = `-- name: GetJournalByMovementGroup :one
SELECT id, production_order_id, movement_group_id, source_batch_id, input_qty, finished_qty, scrap_qty, loss_reason, created_by, created_at FROM production_journals
WHERE movement_group_id = $1
LIMIT 1
`

func (q *Queries) GetJournalByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (ProductionJournal, error) {
	row := q.db.QueryRow(ctx, getJournalByMovementGroup, movementGroupID)
	var i ProductionJournal
	err := row.Scan(
		&i.ID,
		&i.ProductionOrderID,
		&i.MovementGroupID,
		&i.SourceBatchID,
		&i.InputQty,
		&i.FinishedQty,
		&i.ScrapQty,
		&i.LossReason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
