// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBatch(ctx context.Context, arg CreateBatchParams) (InventoryBatch, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateJournal(ctx context.Context, arg CreateJournalParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveBatchesByItem(ctx context.Context, itemID pgtype.UUID) ([]GetActiveBatchesByItemRow, error)
	GetBatch(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	GetInventoryAggregated(ctx context.Context) ([]GetInventoryAggregatedRow, error)
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetJournalByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (ProductionJournal, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error)
	GetSelectableItems(ctx context.Context) ([]GetSelectableItemsRow, error)
	GetTotalFinishedPipesWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTotalRawMaterialWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTransactionByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (InventoryTransaction, error)
	GetUserWithRoleByEmail(ctx context.Context, email string) (GetUserWithRoleByEmailRow, error)
	ListActiveItemsByCategory(ctx context.Context, arg ListActiveItemsByCategoryParams) ([]Item, error)
	ListTransactionsByBatch(ctx context.Context, arg ListTransactionsByBatchParams) ([]InventoryTransaction, error)
	ListVariantsByParent(ctx context.Context, arg ListVariantsByParentParams) ([]Item, error)
	RecordTransaction(ctx context.Context, arg RecordTransactionParams) (InventoryTransaction, error)
	UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (InventoryBatch, error)
}

var _ Querier = (*Queries)(nil)
