// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveJournal(ctx context.Context, arg ApproveJournalParams) (ProductionJournal, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (InventoryBatch, error)
	CreateDerivedBatch(ctx context.Context, arg CreateDerivedBatchParams) (InventoryBatch, error)
	CreateInventoryBatch(ctx context.Context, arg CreateInventoryBatchParams) (InventoryBatch, error)
	CreateInventoryTransaction(ctx context.Context, arg CreateInventoryTransactionParams) (InventoryTransaction, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateJournal(ctx context.Context, arg CreateJournalParams) (pgtype.UUID, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWIPJournal(ctx context.Context, arg CreateWIPJournalParams) (ProductionJournal, error)
	ExhaustBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	FinalizeBatchReservation(ctx context.Context, arg FinalizeBatchReservationParams) (InventoryBatch, error)
	GetActiveBatchesByItem(ctx context.Context, itemID pgtype.UUID) ([]GetActiveBatchesByItemRow, error)
	GetActiveBatchesByItemAndType(ctx context.Context, arg GetActiveBatchesByItemAndTypeParams) ([]GetActiveBatchesByItemAndTypeRow, error)
	GetActiveBatchesByType(ctx context.Context, type_ BatchType) ([]GetActiveBatchesByTypeRow, error)
	GetBatch(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	GetBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	GetInventoryAggregated(ctx context.Context) ([]GetInventoryAggregatedRow, error)
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetJournalByIDForUpdate(ctx context.Context, id pgtype.UUID) (ProductionJournal, error)
	GetJournalByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (ProductionJournal, error)
	GetProcurementDetail(ctx context.Context, id pgtype.UUID) (GetProcurementDetailRow, error)
	GetProcurementList(ctx context.Context, arg GetProcurementListParams) ([]GetProcurementListRow, error)
	GetProcurementReceiptTransactionForUpdate(ctx context.Context, id pgtype.UUID) (InventoryTransaction, error)
	GetPurchaseOrderByID(ctx context.Context, id pgtype.UUID) (PurchaseOrder, error)
	GetPurchaseOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (PurchaseOrder, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error)
	GetSelectableItems(ctx context.Context) ([]GetSelectableItemsRow, error)
	GetTotalFinishedPipesWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTotalRawMaterialWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTransactionByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (InventoryTransaction, error)
	GetUserWithRoleByEmail(ctx context.Context, email string) (GetUserWithRoleByEmailRow, error)
	InsertPurchaseOrderLog(ctx context.Context, arg InsertPurchaseOrderLogParams) (PurchaseOrderLog, error)
	ListActiveItemsByCategory(ctx context.Context, arg ListActiveItemsByCategoryParams) ([]Item, error)
	ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ListPendingApprovalsRow, error)
	ListTransactionsByBatch(ctx context.Context, arg ListTransactionsByBatchParams) ([]InventoryTransaction, error)
	ListVariantsByParent(ctx context.Context, arg ListVariantsByParentParams) ([]Item, error)
	ListWIPActivityEntries(ctx context.Context, arg ListWIPActivityEntriesParams) ([]ListWIPActivityEntriesRow, error)
	RecordTransaction(ctx context.Context, arg RecordTransactionParams) (InventoryTransaction, error)
	RejectJournal(ctx context.Context, arg RejectJournalParams) (ProductionJournal, error)
	ReleaseBatchReservation(ctx context.Context, arg ReleaseBatchReservationParams) (InventoryBatch, error)
	ReserveBatchStock(ctx context.Context, arg ReserveBatchStockParams) (InventoryBatch, error)
	UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (InventoryBatch, error)
	UpdateInventoryBatchStatus(ctx context.Context, arg UpdateInventoryBatchStatusParams) (InventoryBatch, error)
	UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error)
}

var _ Querier = (*Queries)(nil)
