// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AllocateNextDocumentNumber(ctx context.Context, documentType string) (AllocateNextDocumentNumberRow, error)
	ApproveJournal(ctx context.Context, arg ApproveJournalParams) (ProductionJournal, error)
	ChangeUserPasswordCommand(ctx context.Context, arg ChangeUserPasswordCommandParams) error
	CreateBatch(ctx context.Context, arg CreateBatchParams) (InventoryBatch, error)
	// =============================================================================
	// SECTION 3 — BATCH LINEAGE
	// =============================================================================
	CreateBatchConsumption(ctx context.Context, arg CreateBatchConsumptionParams) (BatchConsumption, error)
	CreateDerivedBatch(ctx context.Context, arg CreateDerivedBatchParams) (InventoryBatch, error)
	CreateInventoryBatch(ctx context.Context, arg CreateInventoryBatchParams) (InventoryBatch, error)
	CreateInventoryTransaction(ctx context.Context, arg CreateInventoryTransactionParams) (InventoryTransaction, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateJournal(ctx context.Context, arg CreateJournalParams) (pgtype.UUID, error)
	// Creates the output inventory batch from a production run (molded or finished).
	// Use this instead of CreateDerivedBatch for WIP flows: named args (not positional
	// $n), explicit RETURNING columns, and parent_batch_id for optional quick-reference
	// to the immediate upstream batch. Full many-to-many lineage is stored separately
	// in batch_consumptions — parent_batch_id here is convenience only.
	// NOTE: diameter is intentionally excluded — specification belongs to item, not batch.
	CreateProducedBatch(ctx context.Context, arg CreateProducedBatchParams) (CreateProducedBatchRow, error)
	// =============================================================================
	// SECTION 2 — PRODUCTION RUNS
	// =============================================================================
	CreateProductionRun(ctx context.Context, arg CreateProductionRunParams) (ProductionRun, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateSalesBatchAllocation(ctx context.Context, arg CreateSalesBatchAllocationParams) (SalesBatchAllocation, error)
	CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error)
	CreateSalesOrderLine(ctx context.Context, arg CreateSalesOrderLineParams) (SalesOrderLine, error)
	CreateUserCommand(ctx context.Context, arg CreateUserCommandParams) (CreateUserCommandRow, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	CreateWIPJournal(ctx context.Context, arg CreateWIPJournalParams) (ProductionJournal, error)
	DecrementBatchReservedQty(ctx context.Context, arg DecrementBatchReservedQtyParams) (InventoryBatch, error)
	// Deducts qty_to_deduct from remaining_qty in a single atomic operation.
	// PostgreSQL computes the new remaining — the caller never passes a pre-calculated value.
	// Auto-exhausts the batch when remaining_qty reaches zero after deduction.
	//
	// WHY remaining_qty > 0 instead of remaining_qty >= qty_to_deduct:
	// The FIFO allocation loop intentionally does PARTIAL consumption. When a batch
	// has less than needed (e.g. 50kg available, 100kg needed), the loop already
	// computes actual_deduct = MIN(needed, remaining). Enforcing >= qty_to_deduct
	// would cause 0 rows returned mid-allocation, silently breaking the loop.
	// The FOR UPDATE lock on GetFIFOBatchesForUpdate already guarantees no concurrent
	// modification. remaining_qty > 0 is the correct guard here.
	DeductBatchForProduction(ctx context.Context, arg DeductBatchForProductionParams) (DeductBatchForProductionRow, error)
	DeductBatchRemainingQty(ctx context.Context, arg DeductBatchRemainingQtyParams) (InventoryBatch, error)
	ExhaustBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	FinalizeBatchReservation(ctx context.Context, arg FinalizeBatchReservationParams) (InventoryBatch, error)
	GetActiveBatchesByItem(ctx context.Context, itemID pgtype.UUID) ([]GetActiveBatchesByItemRow, error)
	GetActiveBatchesByItemAndType(ctx context.Context, arg GetActiveBatchesByItemAndTypeParams) ([]GetActiveBatchesByItemAndTypeRow, error)
	GetActiveBatchesByType(ctx context.Context, type_ BatchType) ([]GetActiveBatchesByTypeRow, error)
	// Returns the number of ACTIVE batches available for FIFO allocation.
	// Use for UI fragmentation visibility (e.g. "3 batches available") and
	// pre-flight checks before starting an allocation transaction.
	GetAllocatableBatchCountForItem(ctx context.Context, itemID pgtype.UUID) (int32, error)
	GetBatch(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	// =============================================================================
	// BATCH TRACEABILITY QUERIES
	// =============================================================================
	GetBatchByCode(ctx context.Context, batchCode string) (GetBatchByCodeRow, error)
	GetBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	// Forward traceability: raw batch → all downstream production runs and output batches.
	// Hits idx_batch_consumptions_source_batch_id.
	GetBatchConsumersBySourceBatch(ctx context.Context, sourceBatchID pgtype.UUID) ([]GetBatchConsumersBySourceBatchRow, error)
	// Returns all consumption events where this batch was the SOURCE.
	GetBatchConsumptionEvents(ctx context.Context, sourceBatchID pgtype.UUID) ([]GetBatchConsumptionEventsRow, error)
	GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (InventoryBatch, error)
	// Reverse traceability: finished/molded batch → all source raw batches consumed.
	// Hits idx_batch_consumptions_lineage (target_batch_id, source_batch_id).
	GetBatchLineageByTargetBatch(ctx context.Context, targetBatchID pgtype.UUID) ([]GetBatchLineageByTargetBatchRow, error)
	// Gets the production run that CREATED this batch (target_batch_id = this batch).
	GetBatchProductionRun(ctx context.Context, targetBatchID pgtype.UUID) (GetBatchProductionRunRow, error)
	// Returns the FULL upstream chain for a batch:
	// For a FINISHED batch: FINISHED -> MOLDED -> RAW
	// For a MOLDED batch: MOLDED -> RAW
	// Each row = one upstream batch with its consumption details.
	GetBatchUpstreamLineage(ctx context.Context, targetBatchID pgtype.UUID) ([]GetBatchUpstreamLineageRow, error)
	// Gets vendor traceability for a RAW batch via its parent_po_id.
	GetBatchVendorInfo(ctx context.Context, id pgtype.UUID) (GetBatchVendorInfoRow, error)
	GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomerByNormalizedGST(ctx context.Context, normalizedGst pgtype.Text) (Customer, error)
	GetCustomerByNormalizedPhone(ctx context.Context, normalizedPhone pgtype.Text) (Customer, error)
	GetCustomerByNormalizedWhatsApp(ctx context.Context, normalizedWhatsapp pgtype.Text) (Customer, error)
	// =============================================================================
	// SECTION 1 — FIFO BATCH ALLOCATION
	// =============================================================================
	// Returns all allocatable ACTIVE batches for a given item in strict FIFO order.
	// Caller MUST be inside a transaction. FOR UPDATE prevents phantom reads
	// and concurrent double-allocation during FIFO deduction.
	GetFIFOBatchesForUpdate(ctx context.Context, itemID pgtype.UUID) ([]GetFIFOBatchesForUpdateRow, error)
	GetFinanceLedgerRows(ctx context.Context, arg GetFinanceLedgerRowsParams) ([]GetFinanceLedgerRowsRow, error)
	GetFinancePayablesRows(ctx context.Context) ([]GetFinancePayablesRowsRow, error)
	GetFinishedGoodBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodBatchesRow, error)
	GetFinishedGoodByRecipe(ctx context.Context, arg GetFinishedGoodByRecipeParams) (Item, error)
	// =============================================================================
	// SECTION 4 — FINISHED GOODS TRACEABILITY
	// =============================================================================
	// Returns the full production audit trail for a finished-good item.
	// One row per production run. Source batch aggregation avoids N+1:
	// source_batch_codes is a comma-joined aggregate for display.
	// Hits idx_production_runs_output_item_id + idx_batch_consumptions_production_run_id.
	GetFinishedGoodProductionHistory(ctx context.Context, arg GetFinishedGoodProductionHistoryParams) ([]GetFinishedGoodProductionHistoryRow, error)
	GetFinishedGoodRecentPolishingOutput(ctx context.Context, arg GetFinishedGoodRecentPolishingOutputParams) ([]GetFinishedGoodRecentPolishingOutputRow, error)
	GetFinishedGoodReservationSummary(ctx context.Context, itemID pgtype.UUID) (GetFinishedGoodReservationSummaryRow, error)
	GetFinishedGoodSourceMoldedBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodSourceMoldedBatchesRow, error)
	GetFinishedGoodSourceRawBatches(ctx context.Context, itemID pgtype.UUID) ([]GetFinishedGoodSourceRawBatchesRow, error)
	GetFinishedGoodSummary(ctx context.Context, id pgtype.UUID) (GetFinishedGoodSummaryRow, error)
	GetFinishedGoodsMaster(ctx context.Context) ([]GetFinishedGoodsMasterRow, error)
	GetInventoryAggregated(ctx context.Context) ([]GetInventoryAggregatedRow, error)
	GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error)
	GetInvoiceByOrder(ctx context.Context, orderID pgtype.UUID) (Invoice, error)
	GetItem(ctx context.Context, id pgtype.UUID) (Item, error)
	GetJournalByIDForUpdate(ctx context.Context, id pgtype.UUID) (ProductionJournal, error)
	GetJournalByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (ProductionJournal, error)
	GetNextActiveBatch(ctx context.Context, itemID pgtype.UUID) (GetNextActiveBatchRow, error)
	GetProcurementDetail(ctx context.Context, id pgtype.UUID) (GetProcurementDetailRow, error)
	GetProcurementList(ctx context.Context, arg GetProcurementListParams) ([]GetProcurementListRow, error)
	GetProcurementReceiptTransactionForUpdate(ctx context.Context, id pgtype.UUID) (InventoryTransaction, error)
	GetProductionRunByID(ctx context.Context, id pgtype.UUID) (GetProductionRunByIDRow, error)
	GetPurchaseOrderByID(ctx context.Context, id pgtype.UUID) (PurchaseOrder, error)
	GetPurchaseOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (PurchaseOrder, error)
	GetRawMaterialBatches(ctx context.Context, itemID pgtype.UUID) ([]GetRawMaterialBatchesRow, error)
	GetRawMaterialMaster(ctx context.Context) ([]GetRawMaterialMasterRow, error)
	GetRawMaterialSummary(ctx context.Context, id pgtype.UUID) (GetRawMaterialSummaryRow, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetReservableFinishedBatchesForUpdate(ctx context.Context, itemID pgtype.UUID) ([]GetReservableFinishedBatchesForUpdateRow, error)
	GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error)
	GetSalesOrderByID(ctx context.Context, id pgtype.UUID) (SalesOrder, error)
	GetSalesOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (SalesOrder, error)
	GetSalesOrderDetail(ctx context.Context, id pgtype.UUID) (GetSalesOrderDetailRow, error)
	GetSalesOrderLineByIDForUpdate(ctx context.Context, id pgtype.UUID) (SalesOrderLine, error)
	GetSalesOrderLineDetails(ctx context.Context, salesOrderID pgtype.UUID) ([]GetSalesOrderLineDetailsRow, error)
	GetSelectableItems(ctx context.Context) ([]GetSelectableItemsRow, error)
	GetSetting(ctx context.Context, arg GetSettingParams) (SystemSetting, error)
	GetSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error)
	// =============================================================================
	// SECTION 5 — AGGREGATED INVENTORY SUPPORT
	// =============================================================================
	// Returns total allocatable quantity across all ACTIVE batches for an item.
	// HOLD and EXHAUSTED batches are excluded by the status filter.
	// Returns 0 if no allocatable stock exists (COALESCE guards NULL from empty set).
	GetTotalAllocatableQtyForItem(ctx context.Context, itemID pgtype.UUID) (pgtype.Numeric, error)
	GetTotalFinishedPipesWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTotalRawMaterialWeight(ctx context.Context) (pgtype.Numeric, error)
	GetTransactionByMovementGroup(ctx context.Context, movementGroupID pgtype.UUID) (InventoryTransaction, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserWithRoleByEmail(ctx context.Context, email string) (GetUserWithRoleByEmailRow, error)
	GetUserWithRoleByID(ctx context.Context, id pgtype.UUID) (GetUserWithRoleByIDRow, error)
	GetVendorByID(ctx context.Context, id pgtype.UUID) (Vendor, error)
	GetVendorFinancialSummary(ctx context.Context, dollar_1 pgtype.UUID) (GetVendorFinancialSummaryRow, error)
	GetVendorRecentPOs(ctx context.Context, vendorID pgtype.UUID) ([]GetVendorRecentPOsRow, error)
	GetVendorRecentPayments(ctx context.Context, vendorID pgtype.UUID) ([]GetVendorRecentPaymentsRow, error)
	IncrementBatchReservedQty(ctx context.Context, arg IncrementBatchReservedQtyParams) (InventoryBatch, error)
	InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error)
	InsertCustomerAlias(ctx context.Context, arg InsertCustomerAliasParams) error
	InsertPurchaseOrderLog(ctx context.Context, arg InsertPurchaseOrderLogParams) (PurchaseOrderLog, error)
	ListActiveItemsByCategory(ctx context.Context, arg ListActiveItemsByCategoryParams) ([]Item, error)
	ListAllocationsForBatch(ctx context.Context, inventoryBatchID pgtype.UUID) ([]ListAllocationsForBatchRow, error)
	ListAllocationsForLineForUpdate(ctx context.Context, salesOrderLineID pgtype.UUID) ([]ListAllocationsForLineForUpdateRow, error)
	ListAllocationsForOrder(ctx context.Context, salesOrderID pgtype.UUID) ([]ListAllocationsForOrderRow, error)
	ListAllocationsForOrderForUpdate(ctx context.Context, salesOrderID pgtype.UUID) ([]ListAllocationsForOrderForUpdateRow, error)
	ListCustomerFuzzyCandidates(ctx context.Context, arg ListCustomerFuzzyCandidatesParams) ([]ListCustomerFuzzyCandidatesRow, error)
	ListCustomerSearchCandidates(ctx context.Context, arg ListCustomerSearchCandidatesParams) ([]ListCustomerSearchCandidatesRow, error)
	ListCustomersByNormalizedAlias(ctx context.Context, normalizedAlias string) ([]Customer, error)
	ListFinishedGoodReservations(ctx context.Context, itemID pgtype.UUID) ([]ListFinishedGoodReservationsRow, error)
	ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ListPendingApprovalsRow, error)
	// Newest first. Offset-based pagination (limit + offset). Switch to cursor
	// pagination when production history volumes grow large.
	// Optionally filter by output_item_id (pass NULL to list all).
	ListProductionRuns(ctx context.Context, arg ListProductionRunsParams) ([]ListProductionRunsRow, error)
	ListSalesOrderLinesByOrder(ctx context.Context, salesOrderID pgtype.UUID) ([]SalesOrderLine, error)
	ListSalesOrderLinesByOrderForUpdate(ctx context.Context, salesOrderID pgtype.UUID) ([]SalesOrderLine, error)
	ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error)
	ListTransactionsByBatch(ctx context.Context, arg ListTransactionsByBatchParams) ([]InventoryTransaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVariantsByParent(ctx context.Context, arg ListVariantsByParentParams) ([]Item, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	ListWIPActivityEntries(ctx context.Context, arg ListWIPActivityEntriesParams) ([]ListWIPActivityEntriesRow, error)
	RecordTransaction(ctx context.Context, arg RecordTransactionParams) (InventoryTransaction, error)
	RejectJournal(ctx context.Context, arg RejectJournalParams) (ProductionJournal, error)
	ReleaseAllocations(ctx context.Context, arg ReleaseAllocationsParams) ([]SalesBatchAllocation, error)
	ReleaseBatchReservation(ctx context.Context, arg ReleaseBatchReservationParams) (InventoryBatch, error)
	ReserveBatchStock(ctx context.Context, arg ReserveBatchStockParams) (InventoryBatch, error)
	SetBatchStatus(ctx context.Context, arg SetBatchStatusParams) (InventoryBatch, error)
	UpdateAllocationDispatch(ctx context.Context, arg UpdateAllocationDispatchParams) (SalesBatchAllocation, error)
	UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (InventoryBatch, error)
	UpdateInventoryBatchStatus(ctx context.Context, arg UpdateInventoryBatchStatusParams) (InventoryBatch, error)
	UpdateItemThreshold(ctx context.Context, arg UpdateItemThresholdParams) (Item, error)
	UpdateOrderDispatchProgress(ctx context.Context, arg UpdateOrderDispatchProgressParams) (SalesOrderLine, error)
	UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error)
	UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) (SalesOrder, error)
	UpdateUserCommand(ctx context.Context, arg UpdateUserCommandParams) (UpdateUserCommandRow, error)
	UpdateVendorMutableFields(ctx context.Context, arg UpdateVendorMutableFieldsParams) (Vendor, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (SystemSetting, error)
}

var _ Querier = (*Queries)(nil)
